const data = [
    {
        "orgName": "Lucid Medical Diagnostics",
        "orgKey": "LUCIDMD",
        "locName": "Hitech City",
        "orgId": 2,
        "locId": 3,
        "vendor": "ACL",
        "logFileName":"lucid",

        "env": "P",
        "uat": {
            "enterpriseId": "lucidmuat",
            "user": "lucidmuat",
            "pass": "lucidmuat15",
            "sender": "919154703913",
            "token": "ad4ee476-1032-466f-a94d-6bd30fe83583",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        },
        "prod": {
            "enterpriseId": "lucidmpd",
            "user": "lucidmpd",
            "pass": "lucidmpd15",
            "sender": "919154703915",
            "token": "99a2290f-97b5-4620-91e1-1b782a0b3cd3",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        }
    },
    {
        "orgName": "GY Diagnostics",
        "orgKey": "GYD",
        "locName": "Hitech City",
        "orgId": 0002,
        "locId": 0002,
        "vendor": "ACL",
        "logFileName":"gyd",

        "env": "P",
        "uat": {
            "enterpriseId": "gydpd",
            "user": "gydpd",
            "pass": "gydpd10",
            "sender": "917337339695",
            "token": "b6c3679b-8653-47c1-b900-eb93de10ccc3",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        },
        "prod": {
            "enterpriseId": "gydpd",
            "user": "gydpd",
            "pass": "gydpd10",
            "sender": "917337339695",
            "token": "b6c3679b-8653-47c1-b900-eb93de10ccc3",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        }
    },
    {
        "orgName": "Pace Hospitals",
        "locName": "Hitech City",
        "orgKey": "PACE",
        "orgId": 0003,
        "locId": 0003,
        "vendor": "ACL",
        "logFileName":"pace",
        "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
        "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        "env": "P",
        "uat": {
            "enterpriseId": "paceuat",
            "user": "paceuat",
            "pass": "paceuat03",
            "sender": "919154862569",
            "token": "a3b09c27-23f0-48fe-993f-fd7faa6cb81e",
             "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        },
        "prod": {
            "enterpriseId": "pacepd",
            "user": "pacepd",
            "pass": "pacepd03",
            "sender": "919154862568",
            "token": "ecdd8c2c-32ba-418f-a48c-2b92540664ef",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        }
    },
    {
        "orgName": "Ramesh Hospitals",
        "locName": "Vijayawada",
        "orgKey": "RAMESH",
        "orgId": 0004,
        "locId": 0004,
        "vendor": "ACL",
        "logFileName":"ramesh",
        "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
        "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        "env": "P",
        "uat": {
            "enterpriseId": "ramespd",
            "user": "ramespd",
            "pass": "ramespd25",
            "sender": "917799773641",
            "token": "fd55075e-e497-4b9b-8056-913437478f80",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        },
        "prod": {
            "enterpriseId": "ramespd",
            "user": "ramespd",
            "pass": "ramespd25",
            "sender": "917799773641",
            "token": "fd55075e-e497-4b9b-8056-913437478f80",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        }
    },
    {
        "orgName": "SoftHealth",
        "locName": "Hyderabad",
        "orgKey": "SOFTHEALTH",
        "orgId": 0005,
        "locId": 0005,
        "vendor": "ACL",
        "logFileName":"softhealth",
        "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
        "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        "env": "P",
        "uat": {
            "enterpriseId": "softhpd",
            "user": "softhpd",
            "pass": "softhpd24",
            "sender": "919100121531",
            "token": "dc844acf-35a4-42c8-8bbd-fd3e63cf809e",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        },
        "prod": {
            "enterpriseId": "softhpd",
            "user": "softhpd",
            "pass": "softhpd24",
            "sender": "919100121531",
            "token": "dc844acf-35a4-42c8-8bbd-fd3e63cf809e",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        }
    },
    {
        "orgName": "PRK Hospitals",
        "locName": "Hyderabad",
        "orgKey": "PRK",
        "orgId": 0006,
        "locId": 0006,
        "vendor": "ACL",
        "logFileName":"Prk",
        "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
        "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        "env": "P",
        "uat": {
            "enterpriseId": "prkhpd",
            "user": "prkhpd",
            "pass": "prkhpd14",
            "sender": "919154904292",
            "token": "c350055d-922b-436a-b6a0-8ef5cd7a3277",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        },
        "prod": {
            "enterpriseId": "prkhpd",
            "user": "prkhpd",
            "pass": "prkhpd14",
            "sender": "919154904292",
            "token": "c350055d-922b-436a-b6a0-8ef5cd7a3277",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        }
    },
    {
        "orgName": "NM Diagnostics Pvt Ltd",
        "locName": "Mumbai",
        "orgKey": "NMH",
        "orgId": 0007,
        "locId": 0007,
        "vendor": "ACL",
        "logFileName":"nmh",
        "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
        "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        "env": "P",
        "uat": {
            "enterpriseId": "nmmedpd",
            "user": "nmmedpd",
            "pass": "nmmedpd31",
            "sender": "918657530465",
            "token": "ede4ceba-4cbf-4d0c-b841-88ef627ed35a",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        },
        "prod": {
            "enterpriseId": "nmmedpd",
            "user": "nmmedpd",
            "pass": "nmmedpd31",
            "sender": "918657530465",
            "token": "ede4ceba-4cbf-4d0c-b841-88ef627ed35a",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        }
    },
    {
        "orgName": "Likhitha Diagnostics",
        "locName": "Hyderabad",
        "orgKey": "LIKHITHA",
        "orgId": 0008,
        "locId": 0008,
        "vendor": "ACL",
        "logFileName":"likhitha",
        "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
        "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        "env": "P",
        "uat": {
            "enterpriseId": "likhitpd",
            "user": "likhitpd",
            "pass": "likhitpd10",
            "sender": "919100089201",
            "token": "8d2fd00c-aa12-4072-9c00-09147119e278",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        },
        "prod": {
            "enterpriseId": "likhitpd",
            "user": "likhitpd",
            "pass": "likhitpd10",
            "sender": "919100089201",
            "token": "8d2fd00c-aa12-4072-9c00-09147119e278",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        }
    },
    {
        "orgName": "Jariwala Laboratory",
        "locName": "Mumbai",
        "orgKey": "JARIWALA",
        "orgId": 0009,
        "locId": 0009,
        "vendor": "ACL",
        "logFileName":"jariwala",
        "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
        "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        "env": "P",
        "uat": {
            "enterpriseId": "softhpd",
            "user": "softhpd",
            "pass": "softhpd24",
            "sender": "919100121531",
            "token": "dc844acf-35a4-42c8-8bbd-fd3e63cf809e",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        },
        "prod": {
            "enterpriseId": "softhpd",
            "user": "softhpd",
            "pass": "softhpd24",
            "sender": "919100121531",
            "token": "dc844acf-35a4-42c8-8bbd-fd3e63cf809e",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        }
    },
    {
        "orgName": "Medicover Hospitals",
        "locName": "Hydearabad",
        "orgKey": "MEDICOVER",
        "orgId": 0010,
        "locId": 0010,
        "vendor": "ACL",
        "logFileName":"medicover",
        "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
        "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        "env": "P",
        "uat": {
            "enterpriseId": "softhpd",
            "user": "softhpd",
            "pass": "softhpd24",
            "sender": "919100121531",
            "token": "dc844acf-35a4-42c8-8bbd-fd3e63cf809e",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        },
        "prod": {
            "enterpriseId": "softhpd",
            "user": "softhpd",
            "pass": "softhpd24",
            "sender": "919100121531",
            "token": "dc844acf-35a4-42c8-8bbd-fd3e63cf809e",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        }
    },
    {
        "orgName": "Dr. Khanna's Pathcare Pvt. Ltd",
        "locName": "Delhi",
        "orgKey": "KHANNA",
        "orgId":  0011,
        "locId":  0011,
        "vendor": "ACL",
        "logFileName":"Pathcare",
        "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
        "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        "env": "P",
        "uat": {
            "enterpriseId": "khanapd",
            "user": "khanapd",
            "pass": "khanapd08",
            "sender": "919599184361",
            "token": "31262d22-ec81-437b-8beb-0ae3d65fd75e",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        },
        "prod": {
            "enterpriseId": "khanapd",
            "user": "khanapd",
            "pass": "khanapd08",
            "sender": "919599184361",
            "token": "31262d22-ec81-437b-8beb-0ae3d65fd75e",
            "optInUrl": "https://waoptin.aclwhatsapp.com/api/v1/addoptinpost",
            "pushUrl": "https://push.aclwhatsapp.com/pull-platform-receiver/wa/messages",
        }
    },
];

module.exports = data;
