
/**
 * getOrganizations
 * getLocation
 * getSlotsForRsrc 
 */
module.exports = {
    getAllDoctorsGeolocV9: {
        SpName: "UPR_GET_ALL_DOCTORS_GEOLOC_V9",
        Schema: [{ type: "VARCHAR", column: "IP_CITY_ID", direction: "IN", alias: "IP_CITY_ID" },
        { type: "VARCHAR", column: "IP_AREA_ID", direction: "IN", alias: "IP_AREA_ID" },
        { type: "VARCHAR", column: "IP_LATITUDE", direction: "IN", alias: "IP_LATITUDE" },
        { type: "VARCHAR", column: "IP_LONGITUDE", direction: "IN", alias: "IP_LONGITUDE" },
        { type: "VARCHAR", column: "IP_SPECILIZATION_ID", direction: "IN", alias: "IP_SPECILIZATION_ID" },
        { type: "VARCHAR", column: "IP_ORG_ID", direction: "IN", alias: "IP_ORG_ID" },
        { type: "VARCHAR", column: "IP_LOC_ID", direction: "IN", alias: "IP_LOC_ID" },
        { type: "VARCHAR", column: "PRICE", direction: "IN", alias: "PRICE" },
        { type: "BIGINT", column: "IP_DOCTOR_ID", direction: "IN", alias: "IP_DOCTOR_ID" },
        { type: "VARCHAR", column: "IP_DOCTOR_NAME", direction: "IN", alias: "IP_DOCTOR_NAME" },
        { type: "INT", column: "IP_PAGENUM", direction: "IN", alias: "IP_PAGENUM" },
        { type: "VARCHAR", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPTV9"
    },
    getAllOrganizations: {
        SpName: "UPR_GET_ORGANIZAITON_V9",
        Schema: [{ type: "VARCHAR", column: "ORG_UID", direction: "IN", alias: "ORG_UID" },
        { type: "VARCHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "VARCHAR", column: "IP_ORG_KEY", direction: "IN", alias: "IP_ORG_KEY" },
        { type: "VARCHAR", column: "IP_ORG_MIG_KEY", direction: "IN", alias: "IP_ORG_MIG_KEY" },
        { type: "VARCHAR", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPTV9"
    },
    /*
    getOrganizations: {
        SpName: "UPR_GETALL_ORGANIZATION_V1",
        Schema: [{ type: "BIGINT", column: "IP_ORG_ID", direction: "IN", alias: "IP_ORG_ID" },
        { type: "VARCHAR", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPTV9"
    },
    
    getLocation: {
        SpName: "UPR_GETALL_LOCATION_V1",
        Schema: [{ type: "BIGINT", column: "IP_ORG_ID", direction: "IN", alias: "IP_ORG_ID" },
        { type: "BIGINT", column: "IP_LOC_ID", direction: "IN", alias: "IP_LOC_ID" },
        { type: "VARCHAR", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPTV9"
    },
    */

    getAllLocations: {
        SpName: "UPR_GET_LOCATION_V9",
        Schema: [{ type: "VARCHAR", column: "LOC_UID", direction: "IN", alias: "LOC_UID" },
        { type: "VARCHAR", column: "ORG_UID", direction: "IN", alias: "ORG_UID" },
        { type: "VARCHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "VARCHAR", column: "IP_ORG_KEY", direction: "IN", alias: "IP_ORG_KEY" },
        { type: "VARCHAR", column: "IP_ORG_MIG_KEY", direction: "IN", alias: "IP_ORG_MIG_KEY" },
        { type: "VARCHAR", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPTV9"
    },
    getSpecialitySpecialization: {
        SpName: "UPR_GET_SPECIALITY_SPECIALIZATION_V9",
        Schema: [{ type: "BIGINT", column: "SPECIALITY_ID", direction: "IN", alias: "SPECIALITY_ID" },
        { type: "VARCHAR", column: "SPECIALITY_NAME", direction: "IN", alias: "SPECIALITY_NAME" },
        { type: "BIGINT", column: "SPECIALIZATION_ID", direction: "IN", alias: "SPECIALIZATION_ID" },
        { type: "VARCHAR", column: "ORG_MIG_KEY", direction: "IN", alias: "ORG_MIG_KEY" },
        { type: "VARCHAR", column: "ORG_UID", direction: "IN", alias: "ORG_UID" },
        { type: "VARCHAR", column: "LOC_UID", direction: "IN", alias: "LOC_UID" },
        { type: "VARCHAR", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPTV9"
    },
    getSlotsForRsrc: {
        SpName: "UPR_GET_SLOTS_FOR_A_RSRC_V1",
        Schema: [{ type: "BIGINT", column: "RSRC_ID", direction: "IN", alias: "RSRC_ID" },
        { type: "BIGINT", column: "OLR_ID", direction: "IN", alias: "OLR_ID" },
        { type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "TO_DT" },
        { type: "VARCHAR", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPTV9"
    },
    getPatientUmrV9: {
        SpName: "UPR_GET_PP_PATIENT_UMR_V9",
        Schema: [{ type: "UNIQUEIDENTIFIER", column: "PP_USER_UID", direction: "IN", alias: "PP_USER_UID" },
        { type: "VARCHAR", column: "UMR_NO", direction: "IN", alias: "UMR_NO" }],
        Server: "SQL", Database: "APPTV9"
    },
    getPatientV9: {
        SpName: "UPR_GET_PP_PATIENT_V9",
        Schema: [{ type: "VARCHAR", column: "MOBILE_NO", direction: "IN", alias: "MOBILE_NO" },
        { type: "UNIQUEIDENTIFIER", column: "PP_USER_UID", direction: "IN", alias: "PP_USER_UID" },
        { type: "UNIQUEIDENTIFIER", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPTV9"
    },
    insUpdPatientV9: {
        SpName: "UPR_INSUPD_PP_PATIENT_V9",
        Schema: [{ type: "UNIQUEIDENTIFIER", column: "PP_PATIENT_UID", direction: "IN", alias: "PP_PATIENT_UID" },
        { type: "UNIQUEIDENTIFIER", column: "PP_USER_UID", direction: "IN", alias: "PP_USER_UID" },
        { type: "BIGINT", column: "RELATION_TYPE_ID", direction: "IN", alias: "RELATION_TYPE_ID" },
        { type: "VARCHAR", column: "MOBILE_NO", direction: "IN", alias: "MOBILE_NO" },
        { type: "VARCHAR", column: "COUNTRY_CODE", direction: "IN", alias: "COUNTRY_CODE" },
        { type: "CHAR", column: "RECORD_STATUS", direction: "IN", alias: "RECORD_STATUS" },
        { type: "VARCHAR", column: "DISPLAYNAME", direction: "IN", alias: "DISPLAYNAME" },
        { type: "VARCHAR", column: "EMAIL_ID", direction: "IN", alias: "EMAIL_ID" },
        { type: "VARCHAR", column: "GENDER", direction: "IN", alias: "GENDER" },
        { type: "DATE_TIME_2", column: "DOB", direction: "IN", alias: "DOB" },
        { type: "VARCHAR", column: "FIRST_NAME", direction: "IN", alias: "FIRST_NAME" },
        { type: "VARCHAR", column: "MIDDLE_NAME", direction: "IN", alias: "MIDDLE_NAME" },
        { type: "VARCHAR", column: "LAST_NAME", direction: "IN", alias: "LAST_NAME" },
        { type: "VARCHAR", column: "MOTHER_NAME", direction: "IN", alias: "MOTHER_NAME" },
        { type: "VARCHAR", column: "RES_PER_NAME", direction: "IN", alias: "RES_PER_NAME" },
        { type: "VARCHAR", column: "ALT_MOBILE_NO", direction: "IN", alias: "ALT_MOBILE_NO" },
        { type: "VARCHAR", column: "REFERRED_BY", direction: "IN", alias: "REFERRED_BY" },
        { type: "VARCHAR", column: "ADDRESS1", direction: "IN", alias: "ADDRESS1" },
        { type: "VARCHAR", column: "ADDRESS2", direction: "IN", alias: "ADDRESS2" },
        { type: "VARCHAR", column: "AREA_NAME", direction: "IN", alias: "AREA_NAME" },
        { type: "VARCHAR", column: "CITY_NAME", direction: "IN", alias: "CITY_NAME" },
        { type: "VARCHAR", column: "STATE_NAME", direction: "IN", alias: "STATE_NAME" },
        { type: "VARCHAR", column: "COUNTRY_NAME", direction: "IN", alias: "COUNTRY_NAME" },
        { type: "BIGINT", column: "ZIPCODE", direction: "IN", alias: "ZIPCODE" }],
        Server: "SQL", Database: "APPTV9"
    },
    getPatientDetByUmrV9: {
        SpName: "UPR_GET_PATIENT_DET_BYUMR_V9",
        Schema: [{ type: "VARCHAR", column: "UMR_NO", direction: "IN", alias: "UMR_NO" },
        { type: "VARCHAR", column: "MOBILE_NO", direction: "IN", alias: "MOBILE_NO" },
        { type: "UNIQUEIDENTIFIER", column: "PP_USER_UID", direction: "IN", alias: "PP_USER_UID" },
        { type: "VARCHAR", column: "RELATION", direction: "IN", alias: "RELATION" },
        { type: "BIGINT", column: "ORG_ID", direction: "IN", alias: "ORG_ID" },
        { type: "BIGINT", column: "LOC_ID", direction: "IN", alias: "LOC_ID" }],
        Server: "SQL", Database: "APPTV9"
    },
    getPatientOtpLogin: {
        SpName: "UPR_GET_PATIENT_OTP_LOGIN_V9",
        Schema: [{ type: "VARCHAR", column: "MOBILE_NO", direction: "IN", alias: "MOBILE_NO" },
        { type: "VARCHAR", column: "COUNTRY_CODE", direction: "IN", alias: "COUNTRY_CODE" },
        { type: "VARCHAR", column: "PASSWORD", direction: "IN", alias: "PASSWORD" },
        { type: "VARCHAR", column: "USER_NAME", direction: "IN", alias: "USER_NAME" },
        { type: "BIGINT", column: "PAT_OTP", direction: "IN", alias: "PAT_OTP" },
        { type: "CHAR", column: "IP_FLAG", direction: "IN", alias: "IP_FLAG" },
        { type: "UNIQUEIDENTIFIER", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "VARCHAR", column: "IP_MACHINE", direction: "IN", alias: "IP_MACHINE" },
        { type: "VARCHAR", column: "IP_VERSION", direction: "IN", alias: "IP_VERSION" },
        { type: "VARCHAR", column: "IP_TERMINAL", direction: "IN", alias: "IP_TERMINAL" },
        { type: "VARCHAR", column: "IP_OSUSER", direction: "IN", alias: "IP_OSUSER" },
        { type: "UNIQUEIDENTIFIER", column: "IP_USER_ID", direction: "IN", alias: "IP_USER_ID" },
        { type: "VARCHAR", column: "IP_GUID", direction: "IN", alias: "IP_GUID" },
        { type: "DATE_TIME_2", column: "IP_START_TIME", direction: "IN", alias: "IP_START_TIME" },
        { type: "DATE_TIME_2", column: "IP_END_TIME", direction: "IN", alias: "IP_END_TIME" },
        { type: "INT", column: "IP_ORG_ID", direction: "IN", alias: "IP_ORG_ID" },
        { type: "INT", column: "IP_ROLE_ID", direction: "IN", alias: "IP_ROLE_ID" },
        { type: "INT", column: "IP_CREATE_BY", direction: "IN", alias: "IP_CREATE_BY" },
        { type: "INT", column: "IP_LOC_ID", direction: "IN", alias: "IP_LOC_ID" },
        { type: "INT", column: "IP_TIMEZONE_ID", direction: "IN", alias: "IP_TIMEZONE_ID" },
        { type: "INT", column: "IP_REFERENCE_TYPE_ID", direction: "IN", alias: "IP_REFERENCE_TYPE_ID" },
        { type: "INT", column: "IP_MINUTES", direction: "IN", alias: "IP_MINUTES" },
        { type: "VARCHAR", column: "IP_ORG_KEY", direction: "IN", alias: "IP_ORG_KEY" },
        { type: "VARCHAR", column: "IP_ORG_MIG_KEY", direction: "IN", alias: "IP_ORG_MIG_KEY" },
        { type: "VARCHAR", column: "BROWSER", direction: "IN", alias: "BROWSER" },
        { type: "VARCHAR", column: "BROWSER_VER", direction: "IN", alias: "BROWSER_VER" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "CHAR", column: "TYPE", direction: "IN", alias: "TYPE" },
        { type: "BIGINT", column: "PAT_UMR_ID", direction: "IN", alias: "PAT_UMR_ID" },
        { type: "UNIQUEIDENTIFIER", column: "PAT_UMR_UID", direction: "IN", alias: "PAT_UMR_UID" },
        { type: "UNIQUEIDENTIFIER", column: "PP_USER_UID", direction: "IN", alias: "PP_USER_UID" },
        { type: "UNIQUEIDENTIFIER", column: "PP_PATIENT_UID", direction: "IN", alias: "PP_PATIENT_UID" },
        { type: "BIGINT", column: "ORG_ID", direction: "IN", alias: "ORG_ID" },
        { type: "BIGINT", column: "LOC_ID", direction: "IN", alias: "LOC_ID" },
        { type: "VARCHAR", column: "UMR_NO", direction: "IN", alias: "UMR_NO" },
        { type: "BIGINT", column: "PATIENT_ID", direction: "IN", alias: "PATIENT_ID" },
        { type: "BIGINT", column: "RELATION_ID", direction: "IN", alias: "RELATION_ID" },
        { type: "VARCHAR", column: "ORG_MIG_KEY", direction: "IN", alias: "ORG_MIG_KEY" },
        { type: "VARCHAR", column: "ORG_KEY", direction: "IN", alias: "ORG_KEY" }],
        Server: "SQL", Database: "APPTV9"
    },
    insPatienMapV9: {
        SpName: "UPR_INS_PATIENT_MAP_MAPING_V9",
        Schema: [{ type: "BIGINT", column: "PAT_UMR_ID", direction: "IN", alias: "PAT_UMR_ID" },
        { type: "UNIQUEIDENTIFIER", column: "PAT_UMR_UID", direction: "IN", alias: "PAT_UMR_UID" },
        { type: "UNIQUEIDENTIFIER", column: "PP_USER_UID", direction: "IN", alias: "PP_USER_UID" },
        { type: "BIGINT", column: "ORG_ID", direction: "IN", alias: "ORG_ID" },
        { type: "BIGINT", column: "LOC_ID", direction: "IN", alias: "LOC_ID" },
        { type: "VARCHAR", column: "UMR_NO", direction: "IN", alias: "UMR_NO" },
        { type: "BIGINT", column: "RELATION_ID", direction: "IN", alias: "RELATION_ID" },
        { type: "VARCHAR", column: "MOBILE_NO", direction: "IN", alias: "MOBILE_NO" },
        { type: "CHAR", column: "IP_FLAG", direction: "IN", alias: "IP_FLAG" },
        { type: "BIGINT", column: "PAT_OTP", direction: "IN", alias: "PAT_OTP" }],
        Server: "SQL", Database: "APPTV9"
    },
    uprGetDoctorsSearchbyNameSpclGeoloc: {
        SpName: "UPR_GET_DOCTORS_SRCHBY_NAME_SPCL_GEOLOC_V9",
        Schema: [{ type: "VARCHAR", column: "IP_PREFIX_TEXT", direction: "IN", alias: "IP_PREFIX_TEXT" },
        { type: "BIGINT", column: "IP_ORG_ID", direction: "IN", alias: "IP_ORG_ID" },
        { type: "BIGINT", column: "IP_LOC_ID", direction: "IN", alias: "IP_LOC_ID" },
        { type: "INT", column: "IP_FLAG", direction: "IN", alias: "IP_FLAG" },
        { type: "VARCHAR", column: "IP_LATITUDE", direction: "IN", alias: "IP_LATITUDE" },
        { type: "VARCHAR", column: "IP_LONGITUDE", direction: "IN", alias: "IP_LONGITUDE" },
        { type: "UNIQUEIDENTIFIER", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPTV9"
    },
    getOrgKey: {
        SpName: "UPR_GET_ORG_KEY_V9",
        Schema: [{ type: "VARCHAR", column: "IP_ORG_MIG_KEY", direction: "IN", alias: "IP_ORG_MIG_KEY" },
        { type: "VARCHAR", column: "IP_ORG_KEY", direction: "IN", alias: "IP_ORG_KEY" },
        { type: "VARCHAR", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPTV9"
    },
    getPortalSession: {
        SpName: "UPR_GET_PORTAL_SESSION",
        Schema: [{ type: "VARCHAR", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "BIGINT", column: "OP_ORG_ID", direction: "OUT", alias: "OP_ORG_ID" },
        { type: "BIGINT", column: "OP_LOC_ID", direction: "OUT", alias: "OP_LOC_ID" },
        { type: "BIGINT", column: "OP_USER_ID", direction: "OUT", alias: "OP_USER_ID" },
        { type: "INT", column: "OP_MINUTES", direction: "OUT", alias: "OP_MINUTES" },
        { type: "VARCHAR", column: "OP_USER_NAME", direction: "OUT", alias: "OP_USER_NAME" },
        { type: "VARCHAR", column: "OP_TERMINAL", direction: "OUT", alias: "OP_TERMINAL" },
        { type: "VARCHAR", column: "OP_MACHINE", direction: "OUT", alias: "OP_MACHINE" },
        { type: "VARCHAR", column: "OP_VERSION", direction: "OUT", alias: "OP_VERSION" },
        { type: "VARCHAR", column: "OP_OSUSER", direction: "OUT", alias: "OP_OSUSER" }],
        Server: "SQL", Database: "APPTV9"
    },
    insPortalUserSession: {
        SpName: "UPR_INS_PORTAL_USER_SESSION",
        Schema: [{ type: "VARCHAR", column: "IP_MACHINE", direction: "IN", alias: "IP_MACHINE" },
        { type: "VARCHAR", column: "IP_VERSION", direction: "IN", alias: "IP_VERSION" },
        { type: "VARCHAR", column: "IP_TERMINAL", direction: "IN", alias: "IP_TERMINAL" },
        { type: "VARCHAR", column: "IP_OSUSER", direction: "IN", alias: "IP_OSUSER" },
        { type: "UNIQUEIDENTIFIER", column: "IP_USER_ID", direction: "IN", alias: "IP_USER_ID" },
        { type: "VARCHAR", column: "IP_GUID", direction: "IN", alias: "IP_GUID" },
        { type: "DATE_TIME_2", column: "IP_START_TIME", direction: "IN", alias: "IP_START_TIME" },
        { type: "DATE_TIME_2", column: "IP_END_TIME", direction: "IN", alias: "IP_END_TIME" },
        { type: "INT", column: "IP_ORG_ID", direction: "IN", alias: "IP_ORG_ID" },
        { type: "INT", column: "IP_ROLE_ID", direction: "IN", alias: "IP_ROLE_ID" },
        { type: "INT", column: "IP_CREATE_BY", direction: "IN", alias: "IP_CREATE_BY" },
        { type: "INT", column: "IP_LOC_ID", direction: "IN", alias: "IP_LOC_ID" },
        { type: "INT", column: "IP_TIMEZONE_ID", direction: "IN", alias: "IP_TIMEZONE_ID" },
        { type: "INT", column: "IP_REFERENCE_TYPE_ID", direction: "IN", alias: "IP_REFERENCE_TYPE_ID" },
        { type: "INT", column: "IP_MINUTES", direction: "IN", alias: "IP_MINUTES" },
        { type: "VARCHAR", column: "IP_ORG_MIG_KEY", direction: "IN", alias: "IP_ORG_MIG_KEY" },
        { type: "VARCHAR", column: "IP_ORG_KEY", direction: "IN", alias: "IP_ORG_KEY" },
        { type: "VARCHAR", column: "BROWSER", direction: "IN", alias: "BROWSER" },
        { type: "VARCHAR", column: "BROWSER_VER", direction: "IN", alias: "BROWSER_VER" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "VARCHAR", column: "IP_MODULE_NAME", direction: "IN", alias: "IP_MODULE_NAME" },
        { type: "DATE_TIME_2", column: "CURRENT_TIME", direction: "IN", alias: "CURRENT_TIME" },
        { type: "VARCHAR", column: "OP_SESSION_ID", direction: "OUT", alias: "OP_SESSION_ID" },
        { type: "VARCHAR", column: "OP_ORG_IMG", direction: "OUT", alias: "OP_ORG_IMG" },
        { type: "BIGINT", column: "OP_ORG_ID", direction: "OUT", alias: "OP_ORG_ID" },
        { type: "VARCHAR", column: "OP_MSG", direction: "OUT", alias: "OP_MSG" }],
        Server: "SQL", Database: "APPTV9"
    },
    getAllDoctors: {
        SpName: "UPR_GET_DOCTOR_PP",
        Schema: [{ type: "VARCHAR", column: "ORG_UID", direction: "IN", alias: "ORG_UID" },
        { type: "VARCHAR", column: "LOC_UID", direction: "IN", alias: "LOC_UID" },
        { type: "VARCHAR", column: "DOC_UID", direction: "IN", alias: "DOC_UID" },
        { type: "VARCHAR", column: "ORG_KEY", direction: "IN", alias: "ORG_KEY" },
        { type: "VARCHAR", column: "ORG_MIG_KEY", direction: "IN", alias: "ORG_MIG_KEY" },
        { type: "VARCHAR", column: "DOC_NAME", direction: "IN", alias: "DOC_NAME" },
        { type: "VARCHAR", column: "SPEC_NAME", direction: "IN", alias: "SPEC_NAME" },
        { type: "VARCHAR", column: "SPEC_UID", direction: "IN", alias: "SPEC_UID" },
        { type: "VARCHAR", column: "IP_PAGENUM", direction: "IN", alias: "IP_PAGENUM" },
        { type: "VARCHAR", column: "IP_GENDER", direction: "IN", alias: "IP_GENDER" },
        { type: "INT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPTV9"
    },
}