'use strict';
module.exports = {
    admnReqProcessEstlBill: {
        SpName: "UPR_INSUPD_ADMN_REQ_PROCESS_ESTI_BILL",
        Schema: [{ type: "BIGINT", column: "ARPE_ID", direction: "IN", alias: "ARPE_ID" },
        { type: "BIGINT", column: "ADMN_PROC_ID", direction: "IN", alias: "ADMN_PROC_ID" },
        { type: "BIGINT", column: "ADMN_REQ_ID", direction: "IN", alias: "ADMN_REQ_ID" },
        { type: "CHAR", column: "RECORD_STATUS", direction: "IN", alias: "RECORD_STATUS" },
        { type: "VARCHAR", column: "REC_TYPE", direction: "IN", alias: "REC_TYPE" },
        { type: "VARCHAR", column: "REC_NAME", direction: "IN", alias: "REC_NAME" },
        { type: "VARCHAR", column: "ADMN_PLAN", direction: "IN", alias: "ADMN_PLAN" },
        { type: "VARCHAR", column: "WARD", direction: "IN", alias: "WARD" },
        { type: "VARCHAR", column: "DOCTOR", direction: "IN", alias: "DOCTOR" },
        { type: "INT", column: "ESTIMATION_LOS", direction: "IN", alias: "ESTIMATION_LOS" },
        { type: "VARCHAR", column: "PAYMENT_BY", direction: "IN", alias: "PAYMENT_BY" },
        { type: "VARCHAR", column: "PAYER_SPONSER", direction: "IN", alias: "PAYER_SPONSER" },
        { type: "NUMERIC", column: "SUM_INSURED", direction: "IN", alias: "SUM_INSURED" },
        { type: "NUMERIC", column: "AVAIABLE_LIMIT", direction: "IN", alias: "AVAIABLE_LIMIT" },
        { type: "VARCHAR", column: "PAYER_SPONSER_PAY", direction: "IN", alias: "PAYER_SPONSER_PAY" },
        { type: "VARCHAR", column: "CO_PAY", direction: "IN", alias: "CO_PAY" },
        { type: "VARCHAR", column: "ELIGIBLE_WARD", direction: "IN", alias: "ELIGIBLE_WARD" },
        { type: "VARCHAR", column: "BILLING_HEAD", direction: "IN", alias: "BILLING_HEAD" },
        { type: "NUMERIC", column: "AMOUNT", direction: "IN", alias: "AMOUNT" },
        { type: "NUMERIC", column: "BILL_AMOUNT", direction: "IN", alias: "BILL_AMOUNT" },
        { type: "NUMERIC", column: "PAYBLE_AMOUNT", direction: "IN", alias: "PAYBLE_AMOUNT" },
        { type: "NUMERIC", column: "PAYER_SPONSER_BILL", direction: "IN", alias: "PAYER_SPONSER_BILL" },
        { type: "NUMERIC", column: "PAYER_SPONSER_BILL_AMOUNT", direction: "IN", alias: "PAYER_SPONSER_BILL_AMOUNT" },
        { type: "NUMERIC", column: "PAYER_SPONSER_PAYBLE_AMOUNT", direction: "IN", alias: "PAYER_SPONSER_PAYBLE_AMOUNT" },
        { type: "VARCHAR", column: "REMARKS", direction: "IN", alias: "REMARKS" },
        { type: "DATE_TIME_2", column: "ADMN_REQ_DT", direction: "IN", alias: "ADMN_REQ_DT" },
        { type: "BIGINT", column: "PATIENT_ID", direction: "IN", alias: "PATIENT_ID" },
        { type: "VARCHAR", column: "REC_DATA", direction: "IN", alias: "REC_DATA" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getAdmnReqProcessAll: {
        SpName: "UPR_GET_ADMN_REQ_PROCESS_ALL",
        Schema: [{ type: "BIGINT", column: "ADMN_ALL", direction: "IN", alias: "ADMN_ALL" },
        { type: "BIGINT", column: "PATIENT_ID", direction: "IN", alias: "PATIENT_ID" },
        { type: "IP_SESSION_ID	BIGINT", column: "", direction: "IN", alias: "" }],
        Server: "SQL", Database: "APPT"
    },
    admnReqProcessEnqiStatus: {
        SpName: "UPR_INSUPD_ADMN_REQ_PROCESS_ENQI_STATUS",
        Schema: [{ type: "BIGINT", column: "ARPE_ID", direction: "IN", alias: "ARPE_ID" },
        { type: "BIGINT", column: "ADMN_PROC_ID", direction: "IN", alias: "ADMN_PROC_ID" },
        { type: "BIGINT", column: "ADMN_REQ_ID", direction: "IN", alias: "ADMN_REQ_ID" },
        { type: "CHAR", column: "RECORD_STATUS", direction: "IN", alias: "RECORD_STATUS" },
        { type: "VARCHAR", column: "REC_TYPE", direction: "IN", alias: "REC_TYPE" },
        { type: "VARCHAR", column: "REC_NAME", direction: "IN", alias: "REC_NAME" },
        { type: "VARCHAR", column: "CALL_STATUS", direction: "IN", alias: "CALL_STATUS" },
        { type: "VARCHAR", column: "REFERRAL_NAME", direction: "IN", alias: "REFERRAL_NAME" },
        { type: "VARCHAR", column: "PRIORITY", direction: "IN", alias: "PRIORITY" },
        { type: "DATE_TIME_2", column: "PRE_PONE_DATE", direction: "IN", alias: "PRE_PONE_DATE" },
        { type: "VARCHAR", column: "REMARKS", direction: "IN", alias: "REMARKS" },
        { type: "DATE_TIME_2", column: "ADMN_REQ_DT", direction: "IN", alias: "ADMN_REQ_DT" },
        { type: "BIGINT", column: "PATIENT_ID", direction: "IN", alias: "PATIENT_ID" },
        { type: "VARCHAR", column: "REC_DATA", direction: "IN", alias: "REC_DATA" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    admnReqProcessCouns: {
        SpName: "UPR_INSUPD_ADMNUPR_INSUPD_ADMN_REQ_PROCESS_COUNS",
        Schema: [{ type: "BIGINT", column: "ARPC_ID", direction: "IN", alias: "ARPC_ID" },
        { type: "BIGINT", column: "ADMN_PROC_ID", direction: "IN", alias: "ADMN_PROC_ID" },
        { type: "BIGINT", column: "ADMN_REQ_ID", direction: "IN", alias: "ADMN_REQ_ID" },
        { type: "CHAR", column: "RECORD_STATUS", direction: "IN", alias: "RECORD_STATUS" },
        { type: "VARCHAR", column: "REC_TYPE", direction: "IN", alias: "REC_TYPE" },
        { type: "VARCHAR", column: "REC_NAME", direction: "IN", alias: "REC_NAME" },
        { type: "CHAR", column: "COUNSELLING", direction: "IN", alias: "COUNSELLING" },
        { type: "CHAR", column: "AGREED_ADMN", direction: "IN", alias: "AGREED_ADMN" },
        { type: "CHAR", column: "NEED_HIGH_COUNS", direction: "IN", alias: "NEED_HIGH_COUNS" },
        { type: "CHAR", column: "NEED_HIGH_COUNS_OPTION1", direction: "IN", alias: "NEED_HIGH_COUNS_OPTION1" },
        { type: "CHAR", column: "NEED_HIGH_COUNS_OPTION2", direction: "IN", alias: "NEED_HIGH_COUNS_OPTION2" },
        { type: "CHAR", column: "FINANCE_AST_REQ", direction: "IN", alias: "FINANCE_AST_REQ" },
        { type: "VARCHAR", column: "REMARKS", direction: "IN", alias: "REMARKS" },
        { type: "DATE_TIME_2", column: "ADMN_REQ_DT", direction: "IN", alias: "ADMN_REQ_DT" },
        { type: "BIGINT", column: "PATIENT_ID", direction: "IN", alias: "PATIENT_ID" },
        { type: "VARCHAR", column: "REC_DATA", direction: "IN", alias: "REC_DATA" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    }
}
