'use strict';
module.exports = {
    InsUsrSession: {
        SpName: "UPR_INS_USER_SESSION",
        Schema: [{ type: "VARCHAR", column: "MACHINE", direction: "IN", alias: "MACHINE" },
        { type: "VARCHAR", column: "VERSION", direction: "IN", alias: "VERSION" },
        { type: "VARCHAR", column: "TERMINAL", direction: "IN", alias: "TERMINAL" },
        { type: "VARCHAR", column: "OSUSER", direction: "IN", alias: "OSUSER" },
        { type: "INT", column: "USER_ID", direction: "IN", alias: "USER_ID" },
        { type: "VARCHAR", column: "SESSION_ID", direction: "IN", alias: "SESSION_ID" },
        { type: "DATE_TIME_2", column: "START_TIME", direction: "IN", alias: "START_TIME" },
        { type: "DATE_TIME_2", column: "END_TIME", direction: "IN", alias: "END_TIME" },
        { type: "INT", column: "ORG_ID", direction: "IN", alias: "ORG_ID" },
        { type: "INT", column: "ROLE_ID", direction: "IN", alias: "ROLE_ID" },
        { type: "INT", column: "CREATE_BY", direction: "IN", alias: "CREATE_BY" },
        { type: "INT", column: "LOC_ID", direction: "IN", alias: "LOC_ID" },
        { type: "INT", column: "TIMEZONE_ID", direction: "IN", alias: "TIMEZONE_ID" },
        { type: "INT", column: "REFERENCE_TYPE_ID", direction: "IN", alias: "REFERENCE_TYPE_ID" },
        { type: "INT", column: "MINUTES", direction: "IN", alias: "MINUTES" },
        { type: "VARCHAR", column: "ORG_KEY", direction: "IN", alias: "ORG_KEY" },
        { type: "VARCHAR", column: "BROWSER", direction: "IN", alias: "BROWSER" },
        { type: "VARCHAR", column: "BROWSER_VER", direction: "IN", alias: "BROWSER_VER" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "BIGINT", column: "OP_SESSION_ID", direction: "OUT", alias: "OP_SESSION_ID" },
        { type: "VARCHAR", column: "OP_ORG_IMG", direction: "OUT", alias: "OP_ORG_IMG" },
		//{ type: "BIGINT", column: "OP_ORG_ID", direction: "OUT", alias: "OP_ORG_ID" },
        { type: "VARCHAR", column: "LOC_KEY", direction: "IN", alias: "LOC_KEY" }],
        Server: "SQL", Database: "FB"
    },
    insupdPatientFeedbackInfo: {
        SpName: "UPR_INSUPD_FEEDBACK_FORM_MOBILE",
        Schema: [{ type: "BIGINT", column: "FEEDBACK_ID", direction: "IN", alias: "FEEDBACK_ID" },
        { type: "BIGINT", column: "PATIENT_ID", direction: "IN", alias: "PATIENT_ID" },
        { type: "VARCHAR", column: "UMR_NO", direction: "IN", alias: "UMR_NO" },
        { type: "VARCHAR", column: "ADMIN_NO", direction: "IN", alias: "ADMIN_NO" },
        { type: "BIGINT", column: "TEMPLATE_ID", direction: "IN", alias: "TEMPLATE_ID" },
        { type: "VARCHAR", column: "QUESTION_ID", direction: "IN", alias: "QUESTION_ID" },
        { type: "VARCHAR", column: "QUESTION_GROUP_ID", direction: "IN", alias: "QUESTION_GROUP_ID" },
        { type: "VARCHAR", column: "CV_SCORE", direction: "IN", alias: "CV_SCORE" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "VARCHAR", column: "REMARKS", direction: "IN", alias: "REMARKS" },
        { type: "VARCHAR", column: "CONTROL_VAL_ID", direction: "IN", alias: "CONTROL_VAL_ID" },
        { type: "CHAR", column: "SOURCE_FROM", direction: "IN", alias: "SOURCE_FROM" },
        { type: "BIGINT", column: "SLOT_ID", direction: "IN", alias: "SLOT_ID" },
        { type: "VARCHAR", column: "PATIENT_REMARKS", direction: "IN", alias: "PATIENT_REMARKS" }],
        //{ type: "VARCHAR", column: "FB_TAKEN_BY", direction: "IN", alias: "FB_TAKEN_BY" }],
        Server: "SQL", Database: "FB"
    },
    getPatientFeedbackInfo: {
        SpName: "UPR_GET_FB_FORM_DATA_MBL",
        Schema: [{ type: "INT", column: "TEMPLATE_ID", direction: "IN", alias: "TEMPLATE_ID" },
        { type: "VARCHAR", column: "PATIENT_ID", direction: "IN", alias: "PATIENT_ID" },
        { type: "VARCHAR", column: "UMR_NO", direction: "IN", alias: "UMR_NO" },
        { type: "BIGINT", column: "SLOT_ID", direction: "IN", alias: "SLOT_ID" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "VARCHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "BIGINT", column: "ORG_ID", direction: "IN", alias: "ORG_ID" },
        { type: "BIGINT", column: "LOC_ID", direction: "IN", alias: "LOC_ID" },
        { type: "VARCHAR", column: "ADMN_NO", direction: "IN", alias: "ADMN_NO" }],
        Server: "SQL", Database: "FB"
    },
    getCheckPatFbStatus: {
        SpName: "UPR_GET_CHECK_FB_STATUS",
        Schema: [{ type: "BIGINT", column: "SLOTS_ID", direction: "IN", alias: "SLOTS_ID" },
        { type: "VARCHAR", column: "ADMN_NO", direction: "IN", alias: "ADMN_NO" },
        { type: "BIGINT", column: "TEMPLATE_ID", direction: "IN", alias: "TEMPLATE_ID" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    insUpdCapaInfo: {
        SpName: "UPR_UPD_FB_KAPA_BY_GROUPHEADS_MBL",
        Schema: [{ type: "BIGINT", column: "FEEDBACK_ID", direction: "IN", alias: "FEEDBACK_ID" },
        { type: "BIGINT", column: "QUESTION_GROUP_ID", direction: "IN", alias: "QUESTION_GROUP_ID" },
        { type: "BIGINT", column: "QUESTION_ID", direction: "IN", alias: "QUESTION_ID" },
        { type: "VARCHAR", column: "ROOT_CAUSES", direction: "IN", alias: "ROOT_CAUSES" },
        { type: "VARCHAR", column: "PREVENTIVE_ACTION", direction: "IN", alias: "PREVENTIVE_ACTION" },
        { type: "VARCHAR", column: "CORRECTIVE_ACTIVE", direction: "IN", alias: "CORRECTIVE_ACTIVE" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "VARCHAR", column: "REMARKS", direction: "IN", alias: "REMARKS" }],
        Server: "SQL", Database: "FB"
    },

    
    getPatientData: {
        SpName: "UPR_GET_PATIENT_DATA",
        Schema: [{ type: "VARCHAR", column: "IP_ADMN_NO", direction: "IN", alias: "IP_ADMN_NO" },
        { type: "VARCHAR", column: "IP_UMR_NO", direction: "IN", alias: "IP_UMR_NO" },
        { type: "CHAR", column: "IP_FLAG", direction: "IN", alias: "IP_FLAG" },
        { type: "INT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "BIGINT", column: "SLOT_ID", direction: "IN", alias: "SLOT_ID" },
        { type: "VARCHAR", column: "PREFIX_TEXT", direction: "IN", alias: "PREFIX_TEXT" },
        { type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "TO_DT" },
        { type: "CHAR", column: "ADMN_STATUS", direction: "IN", alias: "ADMN_STATUS" }],
        Server: "SQL", Database: "FB"
    },
    getFbDeptByScr: {
        SpName: "UPR_GET_FB_DEPARTMENT_BY_SCORE",
        Schema: [{ type: "VARCHAR", column: "FB_TYPE", direction: "IN", alias: "FB_TYPE" },
        { type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "TO_DT" },
        { type: "CHAR", column: "LANUGAE", direction: "IN", alias: "LANUGAE" },
        { type: "INT", column: "QUESTION_GROUP_ID", direction: "IN", alias: "QUESTION_GROUP_ID" },
        { type: "INT", column: "PATIENT_ID", direction: "IN", alias: "PATIENT_ID" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    getFbPatDpScr: {
        SpName: "UPR_GET_FB_PATIENT_DP_SCORE",
        Schema: [{ type: "VARCHAR", column: "FB_TYPE", direction: "IN", alias: "FB_TYPE" },
        { type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "TO_DT" },
        { type: "CHAR", column: "LANUGAE", direction: "IN", alias: "LANUGAE" },
        { type: "INT", column: "QUESTION_GROUP_ID", direction: "IN", alias: "QUESTION_GROUP_ID" },
        { type: "INT", column: "PATIENT_ID", direction: "IN", alias: "PATIENT_ID" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    getFbDepartment: {
        SpName: "UPR_GET_FB_DEPARTMENT",
        Schema: [{ type: "VARCHAR", column: "FB_TYPE", direction: "IN", alias: "FB_TYPE" },
        { type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "TO_DT" },
        { type: "CHAR", column: "LANUGAE", direction: "IN", alias: "LANUGAE" },
        { type: "INT", column: "QUESTION_GROUP_ID", direction: "IN", alias: "QUESTION_GROUP_ID" },
        { type: "INT", column: "PATIENT_ID", direction: "IN", alias: "PATIENT_ID" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    getTempDashBord: {
        SpName: "UPR_GET_FEEDBACK_DASH_BOARD_CNTS",
        Schema: [{ type: "VARCHAR", column: "TEMPLATE_ID", direction: "IN", alias: "TEMPLATE_ID" },
        { type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "TO_DT" },
        { type: "INT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    getFbMastData: {
        SpName: "UPR_GET_FB_MAST_DATA",
        Schema: [{ type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        //{ type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" }],
        Server: "SQL", Database: "FB"
    },
    getFbformPatValGrid: {
        SpName: "UPR_GET_FBFORM_PAT_VAL_GRID",
        Schema: [{ type: "VARCHAR", column: "TEMPLATE_NAME", direction: "IN", alias: "TEMPLATE_NAME" },
        { type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "TO_DT" },
        { type: "INT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "VARCHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "VARCHAR", column: "VALUE", direction: "IN", alias: "VALUE" },
        { type: "INT", column: "QUESTION_ID", direction: "IN", alias: "QUESTION_ID" },
        { type: "BIGINT", column: "TEMPLATE_ID", direction: "IN", alias: "TEMPLATE_ID" }],
        Server: "SQL", Database: "FB"
    },
    getFbTemplte: {
        SpName: "UPR_GET_FB_FORM_RPT",
        Schema: [{ type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "TO_DT" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "CHAR", column: "TEMPLATE_TYPE", direction: "IN", alias: "TEMPLATE_TYPE" },
        { type: "BIGINT", column: "TEMPLATE_ID", direction: "IN", alias: "TEMPLATE_ID" }],
        Server: "SQL", Database: "FB"
    },
    getFbFrmRpt: {
        SpName: "UPR_GET_FB_FORM_NEW",
        Schema: [{ type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "TO_DT" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    getFbComMsgReqById: {
        SpName: "UPR_GET_FB_COM_MSG_REQ_BY_ID",
        Schema: [{ type: "BIGINT", column: "REQ_TYPE_ID", direction: "IN", alias: "REQ_TYPE_ID" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "TO_DT" }],
        Server: "SQL", Database: "FB"
    },
    UserGrid: {
        SpName: "UPR_GET_USER_GRID",
        Schema: [{ type: "VARCHAR", column: "USER_NAME", direction: "IN", alias: "USER_NAME" },
        { type: "VARCHAR", column: "REFERENCE_NAME", direction: "IN", alias: "REFERENCE_NAME" },
        { type: "VARCHAR", column: "USER_TYPE", direction: "IN", alias: "USER_TYPE" },
        { type: "VARCHAR", column: "ROLE_NAME", direction: "IN", alias: "ROLE_NAME" },
        { type: "VARCHAR", column: "EMAIL_ID", direction: "IN", alias: "EMAIL_ID" },
        { type: "VARCHAR", column: "MOBILE_NO", direction: "IN", alias: "MOBILE_NO" },
        { type: "VARCHAR", column: "LOCK_STATUS", direction: "IN", alias: "LOCK_STATUS" },
        { type: "VARCHAR", column: "MODIFY_BY", direction: "IN", alias: "MODIFY_BY" },
        { type: "DATE_TIME_2", column: "MODIFY_DT", direction: "IN", alias: "MODIFY_DT" },
        { type: "VARCHAR", column: "RECORD_STATUS", direction: "IN", alias: "RECORD_STATUS" },
        { type: "INT", column: "PAGENUM", direction: "IN", alias: "PAGENUM" },
        { type: "INT", column: "PAGE_SIZE", direction: "IN", alias: "PAGE_SIZE" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    getRoles: {
        SpName: "UPR_GET_ROLES",
        Schema: [{ type: "BIGINT", column: "ROLE_ID", direction: "IN", alias: "ROLE_ID" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    getQuestionGroup: {
        SpName: "UPR_GET_QUESTION_GROUP",
        Schema: [{ type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    getDocumentsByRoles: {
        SpName: "UPR_GET_DOCUMENTS_BY_ROLES",
        Schema: [{ type: "INT", column: "IP_ROLE_ID", direction: "IN", alias: "IP_ROLE_ID" },
        { type: "INT", column: "IP_MODULE_ID", direction: "IN", alias: "IP_MODULE_ID" },
        { type: "INT", column: "IP_LOC_ID", direction: "IN", alias: "IP_LOC_ID" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    getRoleDocAccess: {
        SpName: "UPR_GET_ROLE_DOC_ACCESS",
        Schema: [{ type: "BIGINT", column: "IP_ROLE_ID", direction: "IN", alias: "IP_ROLE_ID" },
        { type: "BIGINT", column: "IP_MODULE_ID", direction: "IN", alias: "IP_MODULE_ID" },
        { type: "BIGINT", column: "IP_ORG_ID", direction: "IN", alias: "IP_ORG_ID" },
        { type: "BIGINT", column: "IP_LOC_ID", direction: "IN", alias: "IP_LOC_ID" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    getQsgQsPsScr: {
        SpName: "UPR_GET_QSG_QS_POSI_SCORE_DATA",
        Schema: [{ type: "INT", column: "TEMPLATE_ID", direction: "IN", alias: "TEMPLATE_ID" },
        { type: "INT", column: "QUESTION_GROUP_ID", direction: "IN", alias: "QUESTION_GROUP_ID" },
        { type: "INT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    getFBdataByGrpId: {
        SpName: "UPR_GET_FB_DATA_BY_GRPID",
        Schema: [{ type: "INT", column: "QUESTION_GROUP_ID", direction: "IN", alias: "QUESTION_GROUP_ID" },
        { type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "TO_DT" },
        { type: "CHAR", column: "PATIENT_TYPE", direction: "IN", alias: "PATIENT_TYPE" },
        { type: "INT", column: "TEMPLATE_TYPE_ID", direction: "IN", alias: "TEMPLATE_TYPE_ID" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    getIpUsrValdLogin: {
        SpName: "UPR_GET_LOGIN_IP_USER_DET",
        Schema: [{ type: "VARCHAR", column: "USER_NAME", direction: "IN", alias: "USER_NAME" },
        { type: "BIGINT", column: "ORG_ID", direction: "IN", alias: "ORG_ID" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    getLoginUser: {
        SpName: "UPR_GET_LOGIN_USER",
        Schema: [{ type: "VARCHAR", column: "USER_NAME", direction: "IN", alias: "USER_NAME" },
        { type: "VARCHAR", column: "PASSWORD", direction: "IN", alias: "PASSWORD" },
        { type: "VARCHAR", column: "MACHINE", direction: "IN", alias: "MACHINE" },
        { type: "VARCHAR", column: "VERSION", direction: "IN", alias: "VERSION" },
        { type: "VARCHAR", column: "TERMINAL", direction: "IN", alias: "TERMINAL" },
        { type: "VARCHAR", column: "OSUSER", direction: "IN", alias: "OSUSER" },
        { type: "VARCHAR", column: "TIMEZONE_ID", direction: "IN", alias: "TIMEZONE_ID" },
        { type: "BIGINT", column: "OP_MINUTES", direction: "OUT", alias: "OP_MINUTES" },
        { type: "BIGINT", column: "ORG_ID", direction: "IN", alias: "ORG_ID" },
        { type: "DATE_TIME_2", column: "CURRENT_TIME", direction: "IN", alias: "CURRENT_TIME" },
        { type: "VARCHAR", column: "FROM", direction: "IN", alias: "FROM" },
        { type: "VARCHAR", column: "ORG_KEY", direction: "IN", alias: "ORG_KEY" },
        { type: "VARCHAR", column: "LOC_KEY", direction: "IN", alias: "LOC_KEY" },
        { type: "VARCHAR", column: "BROWSER", direction: "IN", alias: "BROWSER" },
        { type: "VARCHAR", column: "BROWSER_VER", direction: "IN", alias: "BROWSER_VER" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    InUpchangePsw: {
        SpName: "UPR_UPD_CHANGE_PASSWORD",
        Schema: [{ type: "BIGINT", column: "USER_ID", direction: "IN", alias: "USER_ID" },
        { type: "VARCHAR", column: "USER_NAME", direction: "IN", alias: "USER_NAME" },
        { type: "N_VARCHAR", column: "OLD_PASSWORD", direction: "IN", alias: "OLD_PASSWORD" },
        { type: "N_VARCHAR", column: "NEW_PASSWORD", direction: "IN", alias: "NEW_PASSWORD" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "INT", column: "OP_COUNT", direction: "OUT", alias: "OP_COUNT" }],
        Server: "SQL", Database: "FB"
    },

    
    InsUpdusers: {
        SpName: "UPR_INSUPD_USERS",
        Schema: [{ type: "BIGINT", column: "IP_USER_ID", direction: "IN", alias: "IP_USER_ID" },
        { type: "VARCHAR", column: "TITLE_CD", direction: "IN", alias: "TITLE_CD" },
        { type: "VARCHAR", column: "FIRST_NAME", direction: "IN", alias: "FIRST_NAME" },
        { type: "VARCHAR", column: "MIDDLE_NAME", direction: "IN", alias: "MIDDLE_NAME" },
        { type: "VARCHAR", column: "LAST_NAME", direction: "IN", alias: "LAST_NAME" },
        { type: "VARCHAR", column: "DISPLAY_NAME", direction: "IN", alias: "DISPLAY_NAME" },
        { type: "VARCHAR", column: "GENDER_CD", direction: "IN", alias: "GENDER_CD" },
        { type: "N_VARCHAR", column: "IP_USER_NAME", direction: "IN", alias: "IP_USER_NAME" },
        { type: "N_VARCHAR", column: "IP_PASSWORD", direction: "IN", alias: "IP_PASSWORD" },
        { type: "CHAR ", column: "IP_LOGINSTATUS", direction: "IN", alias: "IP_LOGINSTATUS" },
        { type: "VARCHAR ", column: "IP_SYSTEMNAME", direction: "IN", alias: "IP_SYSTEMNAME" },
        { type: "BIGINT", column: "IP_REFERENCE_ID", direction: "IN", alias: "IP_REFERENCE_ID" },
        { type: "BIGINT", column: "IP_REFERENCE_TYPE_ID", direction: "IN", alias: "IP_REFERENCE_TYPE_ID" },
        { type: "INT", column: "IP_HINT_ID", direction: "IN", alias: "IP_HINT_ID" },
        { type: "INT", column: "IP_HINT2_ID", direction: "IN", alias: "IP_HINT2_ID" },
        { type: "INT", column: "IP_HINT3_ID", direction: "IN", alias: "IP_HINT3_ID" },
        { type: "VARCHAR", column: "IP_HINT_ANS", direction: "IN", alias: "IP_HINT_ANS" },
        { type: "VARCHAR", column: "IP_HINT2_ANS", direction: "IN", alias: "IP_HINT2_ANS" },
        { type: "VARCHAR", column: "IP_HINT3_ANS", direction: "IN", alias: "IP_HINT3_ANS" },
        { type: "VARCHAR", column: "IP_EMAIL", direction: "IN", alias: "IP_EMAIL" },
        { type: "VARCHAR", column: "IP_MOBILE_NO", direction: "IN", alias: "IP_MOBILE_NO" },
        { type: "VARCHAR", column: "IP_DEPT_ID", direction: "IN", alias: "IP_DEPT_ID" },
        { type: "N_VARCHAR", column: "IP_TRANSACTION_PASSWORD", direction: "IN", alias: "IP_TRANSACTION_PASSWORD" },
        { type: "INT", column: "IP_ROLE_ID", direction: "IN", alias: "IP_ROLE_ID" },
        { type: "CHAR", column: "IP_APPLY_PWD_RULE", direction: "IN", alias: "IP_APPLY_PWD_RULE" },
        { type: "CHAR", column: "IP_NOTIFICATIONS", direction: "IN", alias: "IP_NOTIFICATIONS" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "INT", column: "IP_USER_TYPE_ID", direction: "IN", alias: "IP_USER_TYPE_ID" },
        { type: "VARCHAR", column: "IP_TEMPLATE_ID", direction: "IN", alias: "IP_TEMPLATE_ID" }],
        Server: "SQL", Database: "FB"
    },
    UpdResetPwd: {
        SpName: "UPR_UPD_RESET_PWD",
        Schema: [{ type: "BIGINT", column: "USER_ID", direction: "IN", alias: "USER_ID" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "VARCHAR", column: "DEFAULT_PAGE", direction: "IN", alias: "DEFAULT_PAGE" }],
        Server: "SQL", Database: "FB"
    },
    EmployeeDeactive: {
        SpName: "UPR_UPD_FB_ACTIVE_INACTIVE",
        Schema: [{ type: "VARCHAR", column: "TABLE_NAME", direction: "IN", alias: "TABLE_NAME" },
        { type: "VARCHAR", column: "COLUMN_NAME", direction: "IN", alias: "COLUMN_NAME" },
        { type: "N_VARCHAR", column: "COLUMN_VALUE", direction: "IN", alias: "COLUMN_VALUE" },
        { type: "VARCHAR", column: "RECORD_STATUS", direction: "IN", alias: "RECORD_STATUS" },
        { type: "VARCHAR", column: "ID", direction: "IN", alias: "ID" },
        { type: "VARCHAR", column: "STR", direction: "IN", alias: "STR" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    InUpdRoleDocAccess: {
        SpName: "UPR_INSUPD_ROLE_DOC_ACCESS",
        Schema: [{ type: "BIGINT", column: "IP_ROLE_ID", direction: "IN", alias: "IP_ROLE_ID" },
        { type: "VARCHAR", column: "IP_MODULE_ID", direction: "IN", alias: "IP_MODULE_ID" },
        { type: "VARCHAR", column: "IP_DOC_ID", direction: "IN", alias: "IP_DOC_ID" },
        { type: "VARCHAR", column: "IP_ACCESS_ADD", direction: "IN", alias: "IP_ACCESS_ADD" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    InsupdFbTmplteQGrp: {
        SpName: "UPR_INSUPD_FB_TEMPLATE_QUESTION_GROUP",
        Schema: [{ type: "BIGINT", column: "TEMPLATE_ID", direction: "IN", alias: "TEMPLATE_ID" },
        { type: "N_VARCHAR", column: "TEMPLATE_NAME", direction: "IN", alias: "TEMPLATE_NAME" },
        { type: "N_VARCHAR", column: "TEMPLATE_DESC", direction: "IN", alias: "TEMPLATE_DESC" },
        { type: "INT", column: "TEMPLATE_TYPE_ID", direction: "IN", alias: "TEMPLATE_TYPE_ID" },
        { type: "VARCHAR", column: "FORM_META_TEXT", direction: "IN", alias: "FORM_META_TEXT" },
        { type: "INT", column: "AUDIT_AREA_ID", direction: "IN", alias: "AUDIT_AREA_ID" },
        { type: "BIGINT", column: "TEMPLATE_QUESTION_GROUP_ID", direction: "IN", alias: "TEMPLATE_QUESTION_GROUP_ID" },
        { type: "VARCHAR", column: "QUESTION_GROUP_ID", direction: "IN", alias: "QUESTION_GROUP_ID" },
        { type: "VARCHAR", column: "SCORE", direction: "IN", alias: "SCORE" },
        { type: "VARCHAR", column: "POSITION", direction: "IN", alias: "POSITION" },
        { type: "VARCHAR", column: "IS_EQUAL_SCORE_FOR_ALL_QUESTIONS", direction: "IN", alias: "IS_EQUAL_SCORE_FOR_ALL_QUESTIONS" },
        { type: "BIGINT", column: "TEMPLATE_QUESTION_ID", direction: "IN", alias: "TEMPLATE_QUESTION_ID" },
        { type: "VARCHAR", column: "Q_QUESTION_ID", direction: "IN", alias: "Q_QUESTION_ID" },
        { type: "VARCHAR", column: "Q_SCORE", direction: "IN", alias: "Q_SCORE" },
        { type: "VARCHAR", column: "Q_POSITION", direction: "IN", alias: "Q_POSITION" },
        { type: "VARCHAR", column: "Q_QUESTION_GROUP_ID", direction: "IN", alias: "Q_QUESTION_GROUP_ID" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    InsupdFbQuestionScore: {
        SpName: "UPR_INSUPD_FB_QUESTION_SCORE",
        Schema: [{ type: "BIGINT", column: "QUESTION_ID", direction: "IN", alias: "QUESTION_ID" },
        { type: "N_VARCHAR", column: "QUESTION_NAME", direction: "IN", alias: "QUESTION_NAME" },
        { type: "N_VARCHAR", column: "QUESTION_DESC", direction: "IN", alias: "QUESTION_DESC" },
        { type: "BIGINT", column: "CONTROL_ID", direction: "IN", alias: "CONTROL_ID" },
        { type: "BIGINT", column: "CONTROL_VAL_SET_ID", direction: "IN", alias: "CONTROL_VAL_SET_ID" },
        { type: "INT", column: "PARENT_QUESTION_ID", direction: "IN", alias: "PARENT_QUESTION_ID" },
        { type: "VARCHAR", column: "ATTRIBUTE1", direction: "IN", alias: "ATTRIBUTE1" },
        { type: "VARCHAR", column: "ATTRIBUTE2", direction: "IN", alias: "ATTRIBUTE2" },
        { type: "VARCHAR", column: "ATTRIBUTE3", direction: "IN", alias: "ATTRIBUTE3" },
        { type: "INT", column: "QUESTION_TYPE_ID", direction: "IN", alias: "QUESTION_TYPE_ID" },
        { type: "VARCHAR", column: "CONTROL_VAL_ID", direction: "IN", alias: "CONTROL_VAL_ID" },
        { type: "VARCHAR", column: "SCORE", direction: "IN", alias: "SCORE" },
        { type: "VARCHAR", column: "IS_REJECT_BLOOD_SAMPLE", direction: "IN", alias: "IS_REJECT_BLOOD_SAMPLE" },
        { type: "VARCHAR", column: "IS_CORRECT_OPTION", direction: "IN", alias: "IS_CORRECT_OPTION" },
        { type: "VARCHAR", column: "DEPT_HEAD_NAME", direction: "IN", alias: "DEPT_HEAD_NAME" },
        { type: "VARCHAR", column: "MOBILE_NO", direction: "IN", alias: "MOBILE_NO" },
        { type: "VARCHAR", column: "EMAIL_ID", direction: "IN", alias: "EMAIL_ID" },
        { type: "VARCHAR", column: "QUESTION_LANGUAGE", direction: "IN", alias: "QUESTION_LANGUAGE" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    uprInsUserSession: {
        SpName: "UPR_INS_USER_SESSION",
        Schema: [{ type: "VARCHAR", column: "MACHINE", direction: "IN", alias: "IP_MACHINE" },
        { type: "VARCHAR", column: "VERSION", direction: "IN", alias: "IP_VERSION" },
        { type: "VARCHAR", column: "TERMINAL", direction: "IN", alias: "IP_TERMINAL" },
        { type: "VARCHAR", column: "OSUSER", direction: "IN", alias: "IP_OSUSER" },
        { type: "INT", column: "USER_ID", direction: "IN", alias: "IP_USER_ID" },
        { type: "VARCHAR", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "DATE_TIME_2", column: "START_TIME", direction: "IN", alias: "IP_START_TIME" },
        { type: "DATE_TIME_2", column: "END_TIME", direction: "IN", alias: "IP_END_TIME" },
        { type: "INT", column: "ORG_ID", direction: "IN", alias: "IP_ORG_ID" },
        { type: "INT", column: "ROLE_ID", direction: "IN", alias: "IP_ROLE_ID" },
        { type: "INT", column: "CREATE_BY", direction: "IN", alias: "IP_CREATE_BY" },
        { type: "INT", column: "LOC_ID", direction: "IN", alias: "IP_LOC_ID" },
        { type: "INT", column: "TIMEZONE_ID", direction: "IN", alias: "IP_TIMEZONE_ID" },
        { type: "INT", column: "REFERENCE_TYPE_ID", direction: "IN", alias: "IP_REFERENCE_TYPE_ID" },
        { type: "INT", column: "MINUTES", direction: "IN", alias: "IP_MINUTES" },
        { type: "VARCHAR", column: "ORG_KEY", direction: "IN", alias: "IP_ORG_KEY" },
        { type: "VARCHAR", column: "BROWSER", direction: "IN", alias: "BROWSER" },
        { type: "VARCHAR", column: "BROWSER_VER", direction: "IN", alias: "BROWSER_VER" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "BIGINT", column: "OP_SESSION_ID", direction: "OUT", alias: "OP_SESSION_ID" },
        { type: "VARCHAR", column: "OP_ORG_IMG", direction: "OUT", alias: "OP_ORG_IMG" },
        { type: "VARCHAR", column: "LOC_KEY", direction: "IN", alias: "LOC_KEY" }],
        Server: "SQL", Database: "FB"
    },
    InsupdFbControlValueSet: {
        SpName: "UPR_INSUPD_FB_CONTROL_VALUE_SET",
        Schema: [{ type: "INT", column: "CONTROL_VAL_SET_ID", direction: "IN", alias: "CONTROL_VAL_SET_ID" },
        { type: "N_VARCHAR", column: "CONTROL_VAL_SET_NAME", direction: "IN", alias: "CONTROL_VAL_SET_NAME" },
        { type: "N_VARCHAR", column: "CONTROL_VAL_SET_DESC", direction: "IN", alias: "CONTROL_VAL_SET_DESC" },
        { type: "VARCHAR", column: "CONTROL_VAL_ID", direction: "IN", alias: "CONTROL_VAL_ID" },
        { type: "N_VARCHAR", column: "CONTROL_VAL_NAME", direction: "IN", alias: "CONTROL_VAL_NAME" },
        { type: "N_VARCHAR", column: "CONTROL_VAL_DESC", direction: "IN", alias: "CONTROL_VAL_DESC" },
        { type: "VARCHAR", column: "POSITION", direction: "IN", alias: "POSITION" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    InsupdQuestionGroup: {
            SpName: "UPR_INSUPD_FB_QUESTION_GROUP",
            Schema: [{ type: "BIGINT", column: "QUESTION_GROUP_ID", direction: "IN", alias: "QUESTION_GROUP_ID" },
            { type: "N_VARCHAR", column: "QUESTION_GROUP_NAME", direction: "IN", alias: "QUESTION_GROUP_NAME" },
            { type: "N_VARCHAR", column: "QUESTION_GROUP_DESC", direction: "IN", alias: "QUESTION_GROUP_DESC" },
            { type: "INT", column: "PARENT_QUESTION_GROUP_ID", direction: "IN", alias: "PARENT_QUESTION_GROUP_ID" },
            { type: "VARCHAR", column: "QUESTION_GROUP_LANGUAGE", direction: "IN", alias: "QUESTION_GROUP_LANGUAGE" },
            { type: "INT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
            Server: "SQL", Database: "FB"
    },
    DltTmpltQstions: {
        SpName: "UPR_DEL_TMPLT_QUESTIONS",
        Schema: [{ type: "BIGINT", column: "TEMPLATE_ID", direction: "IN", alias: "TEMPLATE_ID" },
        { type: "BIGINT", column: "QUESTION_ID", direction: "IN", alias: "QUESTION_ID" },
        { type: "BIGINT", column: "QUESTION_GROUP_ID", direction: "IN", alias: "QUESTION_GROUP_ID" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "CHAR", column: "RECORD_STATUS", direction: "IN", alias: "RECORD_STATUS" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    getEntSingle: {
        SpName: "UPR_GET_ENTITY_SINGLE",
        Schema: [{ type: "VARCHAR", column: "ENTITY_CD", direction: "IN", alias: "ENTITY_CD" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    FbActnData: {
        SpName: "UPR_GET_FB_ACTIONS_DATA",
        Schema: [{ type: "INT", column: "TEMPLATE_ID", direction: "IN", alias: "TEMPLATE_ID" },
        { type: "VARCHAR", column: "PATIENT_ID", direction: "IN", alias: "PATIENT_ID" },
        { type: "VARCHAR", column: "UMR_NO", direction: "IN", alias: "UMR_NO" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    uprGetTemplateQsdtls: {
        SpName: "UPR_GET_TEMPLATE_QSDTLS",
        Schema: [{ type: "INT", column: "TEMPLATE_ID", direction: "IN", alias: "TEMPLATE_ID" },
        { type: "INT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    getFbFormData: {
        SpName: "UPR_GET_FB_FORM_DATA",
        Schema: [{ type: "INT", column: "TEMPLATE_ID", direction: "IN", alias: "TEMPLATE_ID" },
        { type: "VARCHAR", column: "PATIENT_ID", direction: "IN", alias: "PATIENT_ID" },
        { type: "VARCHAR", column: "UMR_NO", direction: "IN", alias: "UMR_NO" },
        { type: "BIGINT", column: "SLOT_ID", direction: "IN", alias: "SLOT_ID" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    InsupdFeedbackFormControl: {
        SpName: "UPR_INSUPD_FEEDBACK_FORM_CONTROL",
        Schema: [{ type: "INT", column: "FEEDBACK_ID", direction: "IN", alias: "FEEDBACK_ID" },
        { type: "DATE_TIME_2", column: "FEEDBACK_DT", direction: "IN", alias: "FEEDBACK_DT" },
        { type: "VARCHAR", column: "PATIENT_ID", direction: "IN", alias: "PATIENT_ID" },
        { type: "VARCHAR", column: "UMR_NO", direction: "IN", alias: "UMR_NO" },
        { type: "VARCHAR", column: "ADMIN_NO", direction: "IN", alias: "ADMIN_NO" },
        { type: "VARCHAR", column: "MOBILE_NO", direction: "IN", alias: "MOBILE_NO" },
        { type: "VARCHAR", column: "EMAIL_ID", direction: "IN", alias: "EMAIL_ID" },
        { type: "VARCHAR", column: "QUALIFICATION", direction: "IN", alias: "QUALIFICATION" },
        { type: "BIGINT", column: "TEMPLATE_ID", direction: "IN", alias: "TEMPLATE_ID" },
        { type: "VARCHAR", column: "NOTES", direction: "IN", alias: "NOTES" },
        { type: "VARCHAR", column: "FORM_TEXT", direction: "IN", alias: "FORM_TEXT" },
        { type: "BIGINT", column: "SERVICE_ID", direction: "IN", alias: "SERVICE_ID" },
        { type: "BIGINT", column: "BILL_ID", direction: "IN", alias: "BILL_ID" },
        { type: "VARCHAR", column: "FEEDBACK_CD", direction: "IN", alias: "FEEDBACK_CD" },
        { type: "INT", column: "APPROVED_BY", direction: "IN", alias: "APPROVED_BY" },
        { type: "DATE_TIME_2", column: "APPROVED_DT", direction: "IN", alias: "APPROVED_DT" },
        { type: "INT", column: "AUDIT_AREA_ID", direction: "IN", alias: "AUDIT_AREA_ID" },
        { type: "VARCHAR", column: "QUESTION_ID", direction: "IN", alias: "QUESTION_ID" },
        { type: "VARCHAR", column: "QUESTION_GROUP_ID", direction: "IN", alias: "QUESTION_GROUP_ID" },
        { type: "VARCHAR", column: "CONTROL_VALUE", direction: "IN", alias: "CONTROL_VALUE" },
        { type: "VARCHAR", column: "Q_GRP_SCORE", direction: "IN", alias: "Q_GRP_SCORE" },
        { type: "VARCHAR", column: "Q_SCORE", direction: "IN", alias: "Q_SCORE" },
        { type: "VARCHAR", column: "CV_SCORE", direction: "IN", alias: "CV_SCORE" },
        { type: "VARCHAR", column: "NOTES1", direction: "IN", alias: "NOTES1" },
        { type: "VARCHAR", column: "NOTES2", direction: "IN", alias: "NOTES2" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "VARCHAR", column: "REMARKS", direction: "IN", alias: "REMARKS" },
        { type: "VARCHAR", column: "CONTROL_VAL_ID", direction: "IN", alias: "CONTROL_VAL_ID" },
        { type: "BIGINT", column: "SLOT_ID", direction: "IN", alias: "SLOT_ID" },
        { type: "VARCHAR", column: "PATIENT_NAME", direction: "IN", alias: "PATIENT_NAME" },
        { type: "VARCHAR", column: "GENDER_CD", direction: "IN", alias: "GENDER_CD" },
        { type: "VARCHAR", column: "DOB", direction: "IN", alias: "DOB" },
        { type: "VARCHAR", column: "PATIENT_ADRESS", direction: "IN", alias: "PATIENT_ADRESS" },
        { type: "VARCHAR", column: "AGE", direction: "IN", alias: "AGE" },
        { type: "VARCHAR", column: "CONSULTANT_NAME", direction: "IN", alias: "CONSULTANT_NAME" },
        { type: "VARCHAR", column: "DIAGNOSIS", direction: "IN", alias: "DIAGNOSIS" },
        { type: "VARCHAR", column: "WGT", direction: "IN", alias: "WGT" },
        { type: "DATE_TIME_2", column: "ADMN_DT", direction: "IN", alias: "ADMN_DT" },
        { type: "VARCHAR", column: "WARD", direction: "IN", alias: "WARD" },
        { type: "VARCHAR", column: "ROOM", direction: "IN", alias: "ROOM" },
        { type: "VARCHAR", column: "BED", direction: "IN", alias: "BED" },
        { type: "VARCHAR", column: "FLR", direction: "IN", alias: "FLR" },
        { type: "VARCHAR", column: "REF_DOCTOR", direction: "IN", alias: "REF_DOCTOR" },
        { type: "VARCHAR", column: "PATIENT_TYPE_CD", direction: "IN", alias: "PATIENT_TYPE_CD" },
        { type: "VARCHAR", column: "CONS_TYPE", direction: "IN", alias: "CONS_TYPE" },
        { type: "VARCHAR", column: "NEW_OR_OLD_PATIENT", direction: "IN", alias: "NEW_OR_OLD_PATIENT" },
        { type: "VARCHAR", column: "PAY_MODE", direction: "IN", alias: "PAY_MODE" },
        { type: "BIGINT", column: "MIG_ID", direction: "IN", alias: "MIG_ID" }],
        Server: "SQL", Database: "FB"
    },
    uprGetFbTemplate: {
        SpName: "UPR_GET_FB_TEMPLATE",
        Schema: [{ type: "BIGINT", column: "IP_TEMPLATE_ID", direction: "IN", alias: "IP_TEMPLATE_ID" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    GetFBAnalyticsRpt: {
        SpName: "UPR_GET_FB_ANALYTICS_RPT",
        Schema: [{ type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "TO_DT" },
        { type: "CHAR", column: "TEMPLATE_TYPE", direction: "IN", alias: "TEMPLATE_TYPE" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    getFbMnthTrnds: {
        SpName: "UPR_GET_FB_MONTHLY_TRENDS",
        Schema: [{ type: "VARCHAR", column: "FB_TYPE", direction: "IN", alias: "FB_TYPE" },
        { type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "TO_DT" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    GetPatFBSmsCountRpt: {
        SpName: "UPR_GET_PATIENT_FB_DET_SMS_INFO",
        Schema: [{ type: "DATE", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE", column: "TO_DT", direction: "IN", alias: "TO_DT" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "CHAR", column: "IP_OP_TYPE", direction: "IN", alias: "IP_OP_TYPE" }],
        Server: "SQL", Database: "FB"
    },
    chkUsrLogin: {
        SpName: "UPR_GET_RSRC_LOGIN_USER",
        Schema: [{ type: "VARCHAR", column: "IP_USER_NAME", direction: "IN", alias: "IP_USER_NAME" },
        { type: "VARCHAR", column: "IP_PASSWORD", direction: "IN", alias: "IP_PASSWORD" },
        { type: "VARCHAR", column: "IP_MACHINE", direction: "IN", alias: "IP_MACHINE" },
        { type: "VARCHAR", column: "IP_VERSION", direction: "IN", alias: "IP_VERSION" },
        { type: "VARCHAR", column: "IP_TERMINAL", direction: "IN", alias: "IP_TERMINAL" },
        { type: "VARCHAR", column: "IP_OSUSER", direction: "IN", alias: "IP_OSUSER" },
        { type: "VARCHAR", column: "IP_TIMEZONE_ID", direction: "IN", alias: "IP_TIMEZONE_ID" },
        { type: "CHAR", column: "IP_FLAG", direction: "IN", alias: "IP_FLAG" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        //{ type: "BIGINT", column: "OP_MINUTES", direction: "OUT", alias: "OP_MINUTES" },
        { type: "BIGINT", column: "IP_ORG_ID", direction: "IN", alias: "IP_ORG_ID" },
        { type: "CHAR", column: "IP_LOGIN_TYPE", direction: "IN", alias: "IP_LOGIN_TYPE" },
        { type: "BIGINT", column: "IP_LOC_ID", direction: "IN", alias: "IP_LOC_ID" },
        { type: "CHAR", column: "PATIENT_TYPE", direction: "IN", alias: "PATIENT_TYPE" },
        { type: "DATE_TIME_2", column: "CURRENT_TIME", direction: "IN", alias: "CURRENT_TIME" },
        { type: "VARCHAR", column: "FROM", direction: "IN", alias: "FROM" },
        { type: "VARCHAR", column: "IP_ORG_KEY", direction: "IN", alias: "IP_ORG_KEY" },
        { type: "VARCHAR", column: "BROWSER", direction: "IN", alias: "BROWSER" },
        { type: "VARCHAR", column: "BROWSER_VER", direction: "IN", alias: "BROWSER_VER" }],
        Server: "SQL", Database: "APPT"
    },
    getApiData: {
        SpName: "UPR_GET_API_DATA",
        Schema: [{ type: "VARCHAR", column: "lkApiName", direction: "IN", alias: "LOOKUP_NAME" },
        { type: "VARCHAR", column: "apiQry", direction: "IN", alias: "LOOKUP_QRY" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    FbGridData: {
        SpName: "UPR_GET_FBFORM_PAT_VAL_GRID",
        Schema: [{ type: "VARCHAR", column: "TEMPLATE_NAME", direction: "IN", alias: "TEMPLATE_NAME" },
        { type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "TO_DT" },
        { type: "INT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "VARCHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "VARCHAR", column: "VALUE", direction: "IN", alias: "VALUE" },
        { type: "INT", column: "QUESTION_ID", direction: "IN", alias: "QUESTION_ID" },
        { type: "BIGINT", column: "TEMPLATE_ID", direction: "IN", alias: "TEMPLATE_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getTmpQsDtls: {
        SpName: "UPR_GET_TEMPLATE_QSDTLS_MBL",
        Schema: [{ type: "INT", column: "TEMPLATE_ID", direction: "IN", alias: "TEMPLATE_ID" },
        { type: "INT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" }],
        Server: "SQL", Database: "FB"
    },
    getChartGrid: {
        SpName: "UPR_GET_FB_DEPARTMENT",
        Schema: [{ type: "VARCHAR", column: "FB_TYPE", direction: "IN", alias: "FB_TYPE" },
        { type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "TO_DT" },
        { type: "CHAR", column: "LANUGAE", direction: "IN", alias: "LANUGAE" },
        { type: "INT", column: "QUESTION_GROUP_ID", direction: "IN", alias: "QUESTION_GROUP_ID" },
        { type: "INT", column: "PATIENT_ID", direction: "IN", alias: "PATIENT_ID" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    getFbFrmRptNew: {
        SpName: "UPR_GET_FB_FORM_NEW",
        Schema: [{ type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "TO_DT" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
    UprUpdfbKapaGroupHead: {
        SpName: "UPR_UPD_FB_KAPA_BY_GROUPHEADS",
        Schema: [{ type: "BIGINT", column: "FEEDBACK_ID", direction: "IN", alias: "FEEDBACK_ID" },
        { type: "bigint", column: "QUESTION_GROUP_ID", direction: "IN", alias: "QUESTION_GROUP_ID" },
        { type: "bigint", column: "QUESTION_ID", direction: "IN", alias: "QUESTION_ID" },
        { type: "VARCHAR", column: "ROOT_CAUSES", direction: "IN", alias: "ROOT_CAUSES" },
        { type: "VARCHAR", column: "PREVENTIVE_ACTION", direction: "IN", alias: "PREVENTIVE_ACTION" },
        { type: "VARCHAR", column: "CORRECTIVE_ACTIVE", direction: "IN", alias: "CORRECTIVE_ACTIVE" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    updFbFormPrevAct: {
        SpName: "UPR_UPD_FB_FORM_PREV_ACT",
        Schema: [{ type: "INT", column: "FEEDBACK_ID", direction: "IN", alias: "FEEDBACK_ID" },
        { type: "VARCHAR", column: "ROOT_CAUSES", direction: "IN", alias: "ROOT_CAUSES" },
        { type: "VARCHAR", column: "PREVENTIVE_ACTION", direction: "IN", alias: "PREVENTIVE_ACTION" },
        { type: "VARCHAR", column: "CORRECTIVE_ACTIVE", direction: "IN", alias: "CORRECTIVE_ACTIVE" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getQuesAgstCtrlValSet: {
        SpName: "UPR_GET_QUEST_BSD_CNT_VAL_SETID",
        Schema: [{ type: "INT", column: "IP_CNT_VAL_SET_ID", direction: "IN", alias: "IP_CNT_VAL_SET_ID" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    InsupdDelFbCtrlValSet: {
        SpName: "UPR_DEL_FB_CONTROL_VALUE_SET",
        Schema: [{ type: "CHAR", column: "RECORD_STATUS", direction: "IN", alias: "RECORD_STATUS" },
        { type: "BIGINT", column: "IP_CONTROL_VAL_SET_ID", direction: "IN", alias: "IP_CONTROL_VAL_SET_ID" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
	getNpsUsage: {
        SpName: "UPR_GET_EMR_FB_NPS_USAGE",
        Schema: [{ type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "FB"
    },
  
    
}
