'use strict';
module.exports = {
    chkUserLogin: {
        SpName: "UPR_GET_RSRC_LOGIN_USER",
        Schema: [{ type: "CHAR", column: "USER_NAME", direction: "IN", alias: "IP_USER_NAME" },
        { type: "VARCHAR", column: "PASSWORD", direction: "IN", alias: "IP_PASSWORD" },
        { type: "VARCHAR", column: "MACHINE", direction: "IN", alias: "IP_MACHINE" },
        { type: "VARCHAR", column: "VERSION", direction: "IN", alias: "IP_VERSION" },
        { type: "VARCHAR", column: "TERMINAL", direction: "IN", alias: "IP_TERMINAL" },
        { type: "VARCHAR", column: "OSUSER", direction: "IN", alias: "IP_OSUSER" },
        { type: "VARCHAR", column: "TIMEZONE_ID", direction: "IN", alias: "IP_TIMEZONE_ID" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "IP_FLAG" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "BIGINT", column: "ORG_ID", direction: "IN", alias: "IP_ORG_ID" },
        { type: "CHAR", column: "LOGIN_TYPE", direction: "IN", alias: "IP_LOGIN_TYPE" },
        { type: "BIGINT", column: "LOC_ID", direction: "IN", alias: "IP_LOC_ID" },
        { type: "CHAR", column: "PATIENT_TYPE", direction: "IN", alias: "PATIENT_TYPE" },
        { type: "DATE_TIME_2", column: "CURRENT_TIME", direction: "IN", alias: "CURRENT_TIME" },
        { type: "VARCHAR", column: "FROM", direction: "IN", alias: "FROM" },
        { type: "VARCHAR", column: "ORG_KEY ", direction: "IN", alias: "IP_ORG_KEY" },
        { type: "VARCHAR", column: "BROWSER", direction: "IN", alias: "BROWSER" },
        { type: "VARCHAR", column: "BROWSER_VER", direction: "IN", alias: "BROWSER_VER" }],
        Server: "SQL", Database: "APPT"
    },
    getOrgKey: {
        SpName: "UPR_GET_ORG_KEY_V1",
        Schema: [{ type: "VARCHAR", column: "ORG_KEY", direction: "IN", alias: "ORG_KEY" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    insPortalUserSession: {
        SpName: "UPR_INS_PORTAL_USER_SESSION",
        Schema: [{ type: "VARCHAR", column: "IP_MACHINE", direction: "IN", alias: "IP_MACHINE" },
        { type: "VARCHAR", column: "IP_VERSION", direction: "IN", alias: "IP_VERSION" },
        { type: "VARCHAR", column: "IP_TERMINAL", direction: "IN", alias: "IP_TERMINAL" },
        { type: "VARCHAR", column: "IP_OSUSER", direction: "IN", alias: "IP_OSUSER" },
        { type: "INT", column: "IP_USER_ID", direction: "IN", alias: "IP_USER_ID" },
        { type: "VARCHAR", column: "IP_GUID", direction: "IN", alias: "IP_GUID" },
        { type: "DATE_TIME_2", column: "IP_START_TIME", direction: "IN", alias: "IP_START_TIME" },
        { type: "DATE_TIME_2", column: "IP_END_TIME", direction: "IN", alias: "IP_END_TIME" },
        { type: "INT", column: "IP_ORG_ID", direction: "IN", alias: "IP_ORG_ID" },
        { type: "INT", column: "IP_ROLE_ID", direction: "IN", alias: "IP_ROLE_ID" },
        { type: "INT", column: "IP_CREATE_BY", direction: "IN", alias: "IP_CREATE_BY" },
        { type: "INT", column: "IP_LOC_ID", direction: "IN", alias: "IP_LOC_ID" },
        { type: "INT", column: "IP_TIMEZONE_ID", direction: "IN", alias: "IP_TIMEZONE_ID" },
        { type: "INT", column: "IP_REFERENCE_TYPE_ID", direction: "IN", alias: "IP_REFERENCE_TYPE_ID" },
        { type: "INT", column: "IP_MINUTES", direction: "IN", alias: "IP_MINUTES" },
        { type: "VARCHAR", column: "IP_ORG_KEY", direction: "IN", alias: "IP_ORG_KEY" },
        { type: "VARCHAR", column: "BROWSER", direction: "IN", alias: "BROWSER" },
        { type: "VARCHAR", column: "BROWSER_VER", direction: "IN", alias: "BROWSER_VER" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "VARCHAR", column: "OP_SESSION_ID", direction: "OUT", alias: "OP_SESSION_ID" },
        { type: "VARCHAR", column: "OP_ORG_IMG", direction: "OUT", alias: "OP_ORG_IMG" },
        { type: "BIGINT", column: "OP_ORG_ID", direction: "OUT", alias: "OP_ORG_ID" },
        { type: "VARCHAR", column: "IP_WARD_ID", direction: "IN", alias: "IP_WARD_ID" },
        { type: "VARCHAR", column: "IP_MODULE_NAME", direction: "IN", alias: "IP_MODULE_NAME" },
        { type: "DATE_TIME_2", column: "CURRENT_TIME", direction: "IN", alias: "CURRENT_TIME" },
        { type: "VARCHAR", column: "OP_MSG", direction: "OUT", alias: "OP_MSG" }],
        Server: "SQL", Database: "APPT"
    },
    getPortalSession: {
        SpName: "UPR_GET_PORTAL_SESSION",
        Schema: [{ type: "VARCHAR", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "BIGINT", column: "OP_ORG_ID", direction: "OUT", alias: "OP_ORG_ID" },
        { type: "BIGINT", column: "OP_LOC_ID", direction: "OUT", alias: "OP_LOC_ID" },
        { type: "BIGINT", column: "OP_USER_ID", direction: "OUT", alias: "OP_USER_ID" },
        { type: "INT", column: "OP_MINUTES", direction: "OUT", alias: "OP_MINUTES" },
        { type: "VARCHAR", column: "OP_USER_NAME", direction: "OUT", alias: "OP_USER_NAME" },
        { type: "VARCHAR", column: "OP_TERMINAL", direction: "OUT", alias: "OP_TERMINAL" },
        { type: "VARCHAR", column: "OP_MACHINE", direction: "OUT", alias: "OP_MACHINE" },
        { type: "VARCHAR", column: "OP_VERSION", direction: "OUT", alias: "OP_VERSION" },
        { type: "VARCHAR", column: "OP_OSUSER", direction: "OUT", alias: "OP_OSUSER" }],
        Server: "SQL", Database: "APPT"
    },
    GetPatDoc: {
        SpName: "UPR_GET_PAT_DOC",
        Schema: [{ type: "VARCHAR", column: "IP_MRN_NO", direction: "IN", alias: "IP_MRN_NO" },
        { type: "BIGINT", column: "IP_SLOT_ID", direction: "IN", alias: "IP_SLOT_ID" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "BIGINT", column: "IP_OLR_ID", direction: "IN", alias: "IP_OLR_ID" },
        { type: "BIGINT", column: "IP_PATIENT_ID", direction: "IN", alias: "IP_PATIENT_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getPatAdtDschrgSum: {
        SpName: "UPR_GET_PAT_ADT_DSCHRG_SUM",
        Schema: [{ type: "VARCHAR", column: "ADMN_NO", direction: "IN", alias: "ADMN_NO" },
        { type: "VARCHAR", column: "UMR_NO", direction: "IN", alias: "UMR_NO" },
        { type: "BIGINT", column: "SUMMARY_ID", direction: "IN", alias: "SUMMARY_ID" },
        { type: "VARCHAR", column: "FLAG", direction: "IN", alias: "FLAG" }],
        Server: "SQL", Database: "APPT"
    },
    getLoginPatDet: {
        SpName: "UPR_GET_LOGIN_PAT_DET",
        Schema: [{ type: "VARCHAR", column: "USER_NAME", direction: "IN", alias: "USER_NAME" },
        { type: "BIGINT", column: "ORG_ID", direction: "IN", alias: "ORG_ID" },
        { type: "VARCHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getPatApmnts: {
        SpName: "UPR_MOBI_GET_PAT_SCH",
        Schema: [{ type: "BIGINT", column: "PAT_ID", direction: "IN", alias: "IP_PAT_ID" },
        { type: "VARCHAR", column: "UHR_NO", direction: "IN", alias: "IP_UHR_NO" },
        { type: "VARCHAR", column: "UMR_NO", direction: "IN", alias: "IP_UMR_NO" },
        { type: "BIGINT", column: "SLOT_ID", direction: "IN", alias: "IP_SLOT_ID" },
        { type: "INT", column: "FLAG", direction: "IN", alias: "IP_FLAG" },
        { type: "VARCHAR", column: "PATIENT_NAME", direction: "IN", alias: "IP_PATIENT_NAME" },
        { type: "VARCHAR", column: "MOBILE_NO", direction: "IN", alias: "IP_MOBILE_NO" },
        { type: "INT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    insUpdOtp: {
        SpName: "UPR_INSUPD_OTP",
        Schema: [{ type: "BIGINT", column: "OTP_ID", direction: "IN", alias: "OTP_ID" },
        { type: "VARCHAR", column: "USER_NAME", direction: "IN", alias: "USER_NAME" },
        { type: "VARCHAR", column: "UHR_NO", direction: "IN", alias: "UHR_NO" },
        { type: "VARCHAR", column: "UMR_NO", direction: "IN", alias: "UMR_NO" },
        { type: "VARCHAR", column: "MOBILE_NO", direction: "IN", alias: "MOBILE_NO" },
        { type: "BIGINT", column: "ROLE_ID", direction: "IN", alias: "ROLE_ID" },
        { type: "VARCHAR", column: "REMARKS", direction: "IN", alias: "REMARKS" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    updOtp: {
        SpName: "UPR_UPD_OTP",
        Schema: [{ type: "VARCHAR", column: "PASSWORD", direction: "IN", alias: "PASSWORD" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "VARCHAR", column: "USER_NAME", direction: "IN", alias: "USER_NAME" },
        { type: "VARCHAR", column: "UHR_NO", direction: "IN", alias: "UHR_NO" },
        { type: "VARCHAR", column: "UMR_NO", direction: "IN", alias: "UMR_NO" },
        { type: "VARCHAR", column: "EMAIL_ID", direction: "IN", alias: "EMAIL_ID" },
        { type: "VARCHAR", column: "MOBILE_NO", direction: "IN", alias: "MOBILE_NO" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getOtp: {
        SpName: "UPR_GET_OTP",
        Schema: [{ type: "VARCHAR", column: "OTP", direction: "IN", alias: "OTP" },
        { type: "VARCHAR", column: "USER_NAME", direction: "IN", alias: "USER_NAME" },
        { type: "VARCHAR", column: "UHR_NO", direction: "IN", alias: "UHR_NO" },
        { type: "VARCHAR", column: "UMR_NO", direction: "IN", alias: "UMR_NO" },
        { type: "VARCHAR", column: "MOBILE_NO", direction: "IN", alias: "MOBILE_NO" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getLocByOrg: {
        SpName: "UPR_GET_LOC_BYORG",
        Schema: [{ type: "BIGINT", column: "ORG_ID", direction: "IN", alias: "IP_ORG_ID" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }], 
        Server: "SQL", Database: "APPT"
    },
    get7AvlDtsFrOlr: {
        SpName: "UPR_GET_AVL_7_DTS_FOR_A_OLR",
        Schema: [{ type: "BIGINT", column: "OLR_ID", direction: "IN", alias: "OLR_ID" },
        { type: "DATE_TIME_2", column: "DT", direction: "IN", alias: "DT" },
        { type: "CHAR", column: "DT_FLAG", direction: "IN", alias: "DT_FLAG" },
        { type: "CHAR", column: "AVB_FLAG", direction: "IN", alias: "AVB_FLAG" },
        { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getSltsFrOlr: {
        SpName: "UPR_GET_SLOTS_FOR_A_OLR_V1",
        Schema: [{ type: "BIGINT", column: "OLR_ID", direction: "IN", alias: "OLR_ID" },
        { type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "TO_DT" },
        { type: "VARCHAR", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    
    getOrganizations: {
        SpName: "UPR_GETALL_ORGANIZATION_V1",
        Schema: [{ type: "BIGINT", column: "IP_ORG_ID", direction: "IN", alias: "IP_ORG_ID" },
        { type: "VARCHAR", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getDoctors: {
        SpName: "UPR_GETALL_DOCTOR",
        Schema: [{ type: "BIGINT", column: "IP_RSRC_ID", direction: "IN", alias: "IP_RSRC_ID" },
        { type: "BIGINT", column: "IP_OLR_ID", direction: "IN", alias: "IP_OLR_ID" },
        { type: "BIGINT", column: "IP_SPECIALITY_ID", direction: "IN", alias: "IP_SPECIALITY_ID" },
        { type: "VARCHAR", column: "IP_TYPE", direction: "IN", alias: "IP_TYPE" },
        { type: "BIGINT", column: "IP_LOC_ID", direction: "IN", alias: "IP_LOC_ID" },
        { type: "BIGINT", column: "IP_ORG_ID", direction: "IN", alias: "IP_ORG_ID" },
        { type: "VARCHAR", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getLocation: {
        SpName: "UPR_GETALL_LOCATION_V1",
        Schema: [{ type: "BIGINT", column: "IP_ORG_ID", direction: "IN", alias: "IP_ORG_ID" },
        { type: "BIGINT", column: "IP_LOC_ID", direction: "IN", alias: "IP_LOC_ID" },
        { type: "VARCHAR", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getSlotsForRsrc: {
        SpName: "UPR_GET_SLOTS_FOR_A_RSRC_V1",
        Schema: [{ type: "BIGINT", column: "RSRC_ID", direction: "IN", alias: "RSRC_ID" },
        { type: "BIGINT", column: "OLR_ID", direction: "IN", alias: "OLR_ID" },
        { type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "TO_DT" },
        { type: "VARCHAR", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
         
    getOrgLogo: {
        SpName: "UPR_GET_ORG_IMAGE  ",
        Schema: [{ type: "BIGINT", column: "ORG_ID", direction: "IN", alias: "ORG_ID" },
        { type: "BIGINT", column: "LOC_ID", direction: "IN", alias: "LOC_ID" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    
    getDocSrchByName: {
        SpName: "UPR_GET_DOCTORS_SRCHBY_NAME_SPCL",
        Schema: [{ type: "VARCHAR", column: "COLUMN_NAME", direction: "IN", alias: "IP_COLUMN_NAME" },
        { type: "VARCHAR", column: "PREFIX_TEXT", direction: "IN", alias: "IP_PREFIX_TEXT" },
        { type: "BIGINT", column: "ORG_ID", direction: "IN", alias: "IP_ORG_ID" },
        { type: "BIGINT", column: "LOC_ID", direction: "IN", alias: "IP_LOC_ID" },
        { type: "INT", column: "FLAG", direction: "IN", alias: "IP_FLAG" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getAllDoctors: {
        SpName: "UPR_GET_ALL_DOCTORS",
        Schema: [{ type: "VARCHAR", column: "CITY_ID", direction: "IN", alias: "IP_CITY_ID" },
        { type: "VARCHAR", column: "SPECILIZATION_ID", direction: "IN", alias: "IP_SPECILIZATION_ID" },
        { type: "DATE_TIME_2", column: "FROM_DT", direction: "IN", alias: "IP_FROM_DT" },
        { type: "DATE_TIME_2", column: "TO_DT", direction: "IN", alias: "IP_TO_DT" },
        { type: "BIGINT", column: "DOCTOR_ID", direction: "IN", alias: "IP_DOCTOR_ID" },
        { type: "VARCHAR", column: "DOCTOR_NAME", direction: "IN", alias: "IP_DOCTOR_NAME" },
        { type: "INT", column: "PAGENUM", direction: "IN", alias: "IP_PAGENUM" },
        { type: "BIGINT", column: "COUNT", direction: "IN", alias: "OP_COUNT" },
        { type: "VARCHAR", column: "ORG_ID", direction: "IN", alias: "IP_ORG_ID" },
        { type: "VARCHAR", column: "LOC_ID", direction: "IN", alias: "IP_LOC_ID" },
        { type: "INT", column: "REFERENCE_TYPE_ID", direction: "IN", alias: "IP_REFERENCE_TYPE_ID" },
        { type: "VARCHAR", column: "AREA_ID", direction: "IN", alias: "IP_AREA_ID" },
        { type: "VARCHAR", column: "PREFIEX_TEXT", direction: "IN", alias: "IP_PREFIEX_TEXT" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getRsRcSpelz: {
        SpName: "UPR_GET_RSRC_SPECIALIZATION",
        Schema: [{ type: "BIGINT", column: "DOC_ID", direction: "IN", alias: "IP_DOC_ID" },
        { type: "BIGINT", column: "REFERENCE_TYPE_ID", direction: "IN", alias: "IP_REFERENCE_TYPE_ID" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getDocQualification: {
        SpName: "UPR_GET_DOC_QUALIFICATION",
        Schema: [{ type: "INT", column: "RSRC_ID", direction: "IN", alias: "IP_RSRC_ID" },
        { type: "BIGINT", column: "REFERENCE_TYPE_ID", direction: "IN", alias: "IP_REFERENCE_TYPE_ID" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getDocAwards: {
        SpName: "UPR_GET_DOC_AWARDS",
        Schema: [{ type: "INT", column: "DOCTOR_ID", direction: "IN", alias: "IP_DOCTOR_ID" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getDocMemb: {
        SpName: "UPR_GET_DOC_MEMBER_SHIP",
        Schema: [{ type: "INT", column: "DOCTOR_ID", direction: "IN", alias: "IP_DOCTOR_ID" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getDocReg: {
        SpName: "UPR_GET_DOC_REG",
        Schema: [{ type: "INT", column: "DOCTOR_ID", direction: "IN", alias: "IP_DOCTOR_ID" },
        { type: "BIGINT", column: "REFERENCE_TYPE_ID", direction: "IN", alias: "IP_REFERENCE_TYPE_ID" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getSlotsByOlr: {
        SpName: "UPR_MOBI_GET_OLR_SLOTS",
        Schema: [{ type: "BIGINT", column: "OLR_ID", direction: "IN", alias: "IP_OLR_ID" },
        { type: "BIGINT", column: "ORG_ID", direction: "IN", alias: "IP_ORG_ID" },
        { type: "BIGINT", column: "LOC_ID", direction: "IN", alias: "IP_LOC_ID" },
        { type: "BIGINT", column: "RSRC_ID", direction: "IN", alias: "IP_RSRC_ID" },
        { type: "INT", column: "REFERENCE_TYPE_ID", direction: "IN", alias: "IP_REFERENCE_TYPE_ID" },
        { type: "DATE_TIME_2", column: "APMNT_DT", direction: "IN", alias: "IP_APMNT_DT" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    insUpdDropReq: {
        SpName: "UPR_INSUPD_DROP_REQUEST",
        Schema: [{ type: "BIGINT", column: "DROP_REQUEST_ID", direction: "IN", alias: "IP_DROP_REQUEST_ID" },
        { type: "BIGINT", column: "OLR_ID", direction: "IN", alias: "IP_OLR_ID" },
        { type: "BIGINT", column: "RSRC_ID", direction: "IN", alias: "IP_RSRC_ID" },
        { type: "BIGINT", column: "REFERENCE_ID", direction: "IN", alias: "IP_REFERENCE_ID" },
        { type: "DATE_TIME_2", column: "APMNT_DT", direction: "IN", alias: "IP_APMNT_DT" },
        { type: "DATE_TIME_2", column: "SCH_START_TIME", direction: "IN", alias: "IP_SCH_START_TIME" },
        { type: "VARCHAR", column: "REASON_FOR_VISIT", direction: "IN", alias: "IP_REASON_FOR_VISIT" },
        { type: "VARCHAR", column: "DISPLAY_NAME", direction: "IN", alias: "IP_DISPLAY_NAME" },
        { type: "VARCHAR", column: "EMAIL_ID", direction: "IN", alias: "IP_EMAIL_ID" },
        { type: "VARCHAR", column: "MOBILE", direction: "IN", alias: "IP_MOBILE" },
        { type: "BIGINT", column: "REQ_TYPE_ID", direction: "IN", alias: "IP_REQ_TYPE_ID" },
        { type: "VARCHAR", column: "NOTES", direction: "IN", alias: "IP_NOTES" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    holdSlot: {
        SpName: "UPR_UPD_SLOT_HOLD_STATUS",
        Schema: [{ type: "BIGINT", column: "SLOT_ID", direction: "IN", alias: "IP_SLOT_ID" },
        { type: "BIGINT", column: "TO_SLOT_ID", direction: "IN", alias: "IP_TO_SLOT_ID" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "IP_FLAG" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "INT", column: "OP_COUNT", direction: "OUT", alias: "OP_COUNT" }],
        Server: "SQL", Database: "APPT"
    },
    updSlot: {
        SpName: "UPR_UPD_SLOT",
        Schema: [{ type: "BIGINT", column: "SLOTS_ID", direction: "IN", alias: "IP_SLOTS_ID" },
        { type: "BIGINT", column: "REFERENCE_ID", direction: "IN", alias: "IP_REFERENCE_ID" },
        { type: "BIGINT", column: "REFERENCE_TYPE_ID", direction: "IN", alias: "IP_REFERENCE_TYPE_ID" },
        { type: "BIGINT", column: "STATUS_ID", direction: "IN", alias: "IP_STATUS_ID" },
        { type: "BIGINT", column: "STATUS_REASON_ID", direction: "IN", alias: "IP_STATUS_REASON_ID" },
        { type: "VARCHAR", column: "REMARKS", direction: "IN", alias: "IP_REMARKS" },
        { type: "BIGINT", column: "BILL_ID", direction: "IN", alias: "IP_BILL_ID" },
        { type: "VARCHAR", column: "DISPLAY_NAME", direction: "IN", alias: "IP_DISPLAY_NAME" },
        { type: "VARCHAR", column: "REASON_FOR_VISIT", direction: "IN", alias: "IP_REASON_FOR_VISIT" },
        { type: "VARCHAR", column: "EMAIL_ID", direction: "IN", alias: "IP_EMAIL_ID" },
        { type: "VARCHAR", column: "MOBILE", direction: "IN", alias: "IP_MOBILE" },
        { type: "BIGINT", column: "REQ_TYPE_ID", direction: "IN", alias: "IP_REQ_TYPE_ID" },
        { type: "VARCHAR", column: "NOTES", direction: "IN", alias: "IP_NOTES" },
        { type: "BIGINT", column: "ACCESS_TYPE", direction: "IN", alias: "IP_ACCESS_TYPE" },
        { type: "INT", column: "CONSULTATION_TYPE_ID", direction: "IN", alias: "IP_CONSULTATION_TYPE_ID" },
        { type: "INT", column: "APMNT_TYPE_ID", direction: "IN", alias: "IP_APMNT_TYPE_ID" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "BIGINT", column: "COUNT", direction: "OUT", alias: "OP_COUNT" },
        { type: "BIGINT", column: "REFERENCE_TYPE_ID1", direction: "IN", alias: "IP_REFERENCE_TYPE_ID1" },
        { type: "BIGINT", column: "SERVICE_ID", direction: "IN", alias: "IP_SERVICE_ID" },
        { type: "VARCHAR", column: "CONSULTATION_NO", direction: "IN", alias: "IP_CONSULTATION_NO" },
        { type: "VARCHAR", column: "IS_VIP", direction: "IN", alias: "IP_IS_VIP" },
        { type: "VARCHAR", column: "FROM_AREA", direction: "IN", alias: "IP_FROM_AREA" },
        { type: "BIGINT", column: "REFEREL_ID", direction: "IN", alias: "IP_REFEREL_ID" },
        { type: "VARCHAR", column: "REFEREL_NAME", direction: "IN", alias: "IP_REFEREL_NAME" },
        { type: "VARCHAR", column: "VISIT_TYPE", direction: "IN", alias: "IP_VISIT_TYPE" },
        { type: "VARCHAR", column: "PATIENT_TYPE_CD", direction: "IN", alias: "IP_PATIENT_TYPE_CD" },
        { type: "VARCHAR", column: "TITLE_CD", direction: "IN", alias: "IP_TITLE_CD" },
        { type: "VARCHAR", column: "FIRST_NAME", direction: "IN", alias: "IP_FIRST_NAME" },
        { type: "VARCHAR", column: "MIDDLE_NAME", direction: "IN", alias: "IP_MIDDLE_NAME" },
        { type: "VARCHAR", column: "LAST_NAME", direction: "IN", alias: "IP_LAST_NAME" },
        { type: "CHAR", column: "GENDER_CD", direction: "IN", alias: "IP_GENDER_CD" },
        { type: "DATE_TIME_2", column: "DOB", direction: "IN", alias: "IP_DOB" },
        { type: "VARCHAR", column: "MOTHER_MAIDEN_NAME", direction: "IN", alias: "IP_MOTHER_MAIDEN_NAME" },
        { type: "VARCHAR", column: "ADDRESS", direction: "IN", alias: "IP_ADDRESS" },
        { type: "BIGINT", column: "COUNTRY_ID ", direction: "IN", alias: "IP_COUNTRY_ID" },
        { type: "BIGINT", column: "STATE_ID", direction: "IN", alias: "IP_STATE_ID" },
        { type: "BIGINT", column: "CITY_ID", direction: "IN", alias: "IP_CITY_ID" },
        { type: "BIGINT", column: "AREA_ID", direction: "IN", alias: "IP_AREA_ID" },
        { type: "VARCHAR", column: "ZIPCODE", direction: "IN", alias: "IP_ZIPCODE" },
        { type: "CHAR", column: "PRE_REGISTER", direction: "IN", alias: "IP_PRE_REGISTER" },
        { type: "VARCHAR", column: "BILL_NO", direction: "IN", alias: "IP_BILL_NO" },
        { type: "VARCHAR", column: "PATIENT_TYPE_NAME", direction: "IN", alias: "IP_PATIENT_TYPE_NAME" },
        { type: "VARCHAR", column: "SOURCE", direction: "IN", alias: "IP_SOURCE" },
        { type: "VARCHAR", column: "REFERRAL_TYPE_ID", direction: "IN", alias: "IP_REFERRAL_TYPE_ID" },
        { type: "VARCHAR", column: "APMNT_NOTES", direction: "IN", alias: "IP_APMNT_NOTES" }],
        Server: "SQL", Database: "APPT"
    },
    getReasForVisit: {
        SpName: "UPR_GET_REASON_FOR_VISIT",
        Schema: [{ type: "INT", column: "PREFIXTEXT", direction: "IN", alias: "IP_PREFIXTEXT" },
        { type: "BIGINT", column: "SESSION_ID ", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getPatRelMap: {
        SpName: " UPR_GET_PATIENT_REL_MAP",
        Schema: [{ type: "VARCHAR", column: "UHR_NO", direction: "IN", alias: "UHR_NO" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getPatient: {
        SpName: "UPR_GET_PATIENT",
        Schema: [{ type: "VARCHAR", column: "UHR_NO", direction: "IN", alias: "IP_UHR_NO" },
        { type: "BIGINT", column: "PATIENT_ID", direction: "IN", alias: "IP_PATIENT_ID" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "VARCHAR", column: "LAST_NAME", direction: "IN", alias: "IP_LAST_NAME" },
        { type: "VARCHAR", column: "MOTHER_MAIDEN_NAME", direction: "IN", alias: "IP_MOTHER_MAIDEN_NAME" },
        { type: "DATE_TIME_2", column: "DOB", direction: "IN", alias: "IP_DOB" },
        { type: "VARCHAR", column: "RES_PERSON_NAME", direction: "IN", alias: "RES_PERSON_NAME" },
        { type: "VARCHAR", column: "FIRST_NAME", direction: "IN", alias: "FIRST_NAME" }],
        Server: "SQL", Database: "APPT"
    },
    getPincdDet: {
        SpName: "UPR_GET_PINCODE_DETAILS",
        Schema: [{ type: "VARCHAR", column: "AREA_NAME", direction: "IN", alias: "AREA_NAME" },
        { type: "VARCHAR", column: "CITY_NAME", direction: "IN", alias: "CITY_NAME" },
        { type: "VARCHAR", column: "PINCODE", direction: "IN", alias: "IP_PINCODE" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    updPatInfo: {
        SpName: "UPR_MOBI_UPD_PAT_INFO",
        Schema: [{ type: "BIGINT", column: "USER_ID", direction: "IN", alias: "IP_USER_ID" },
        { type: "BIGINT", column: "PATIENT_ID", direction: "IN", alias: "IP_PATIENT_ID" },
        { type: "VARCHAR", column: "FIRST_NAME", direction: "IN", alias: "IP_FIRST_NAME" },
        { type: "VARCHAR", column: "MIDDLE_NAME", direction: "IN", alias: "IP_MIDDLE_NAME" },
        { type: "VARCHAR", column: "LAST_NAME", direction: "IN", alias: "IP_LAST_NAME" },
        { type: "VARCHAR", column: "DISPLAY_NAME", direction: "IN", alias: "IP_DISPLAY_NAME" },
        { type: "VARCHAR", column: "PHOTO", direction: "IN", alias: "IP_PHOTO" },
        { type: "CHAR", column: "GENDER_CD", direction: "IN", alias: "IP_GENDER_CD" },
        { type: "VARCHAR", column: "MARITAL_STATUS_CD", direction: "IN", alias: "IP_MARITAL_STATUS_CD" },
        { type: "DATE_TIME_2", column: "DOB", direction: "IN", alias: "IP_DOB" },
        { type: "VARCHAR", column: "OCCUPATION_CD", direction: "IN", alias: "IP_OCCUPATION_CD" },
        { type: "VARCHAR", column: "NATIONALITY_CD", direction: "IN", alias: "IP_NATIONALITY_CD" },
        { type: "VARCHAR", column: "BLOOD_GROUP_CD", direction: "IN", alias: "IP_BLOOD_GROUP_CD" },
        { type: "VARCHAR", column: "RELIGION_CD", direction: "IN", alias: "IP_RELIGION_CD" },
        { type: "VARCHAR", column: "EDUCATION_CD", direction: "IN", alias: "IP_EDUCATION_CD" },
        { type: "VARCHAR", column: "MOBILE_NO1", direction: "IN", alias: "IP_MOBILE_NO1" },
        { type: "VARCHAR", column: "MOBILE_NO2", direction: "IN", alias: "IP_MOBILE_NO2" },
        { type: "VARCHAR", column: "EMAIL_ID", direction: "IN", alias: "IP_EMAIL_ID" },
        { type: "VARCHAR", column: "ADDRESS1", direction: "IN", alias: "IP_ADDRESS1" },
        { type: "VARCHAR", column: "ADDRESS2", direction: "IN", alias: "IP_ADDRESS2" },
        { type: "BIGINT", column: "COUNTRY_ID", direction: "IN", alias: "IP_COUNTRY_ID" },
        { type: "BIGINT", column: "STATE_ID", direction: "IN", alias: "IP_STATE_ID" },
        { type: "BIGINT", column: "CITY_ID", direction: "IN", alias: "IP_CITY_ID" },
        { type: "BIGINT", column: "AREA_ID", direction: "IN", alias: "IP_AREA_ID" },
        { type: "VARCHAR", column: "AREA_NAME", direction: "IN", alias: "IP_AREA_NAME" },
        { type: "VARCHAR", column: "ZIPCODE", direction: "IN", alias: "IP_ZIPCODE" },
        { type: "VARCHAR", column: "IMAGE_URL", direction: "IN", alias: "IP_IMAGE_URL" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
        Server: "SQL", Database: "APPT"
    },
    insUpdPatReq: {
        SpName: "UPR_INSUPD_PATIENT_REQUESTS",
        Schema: [{ type: "BIGINT", column: "PAT_REQUEST_ID", direction: "IN", alias: "PAT_REQUEST_ID" },
        { type: "VARCHAR", column: "UHR_NO", direction: "IN", alias: "UHR_NO" },
        { type: "VARCHAR", column: "UMR_NO", direction: "IN", alias: "UMR_NO" },
        { type: "BIGINT", column: "PATIENT_ID", direction: "IN", alias: "PATIENT_ID" },
        { type: "VARCHAR", column: "PAT_MOBILE_NO", direction: "IN", alias: "PAT_MOBILE_NO" },
        { type: "BIGINT", column: "REQUEST_ID", direction: "IN", alias: "REQUEST_ID" },
        { type: "CHAR", column: "RECORD_STATUS", direction: "IN", alias: "RECORD_STATUS" },
        { type: "VARCHAR", column: "PAT_REMARKS", direction: "IN", alias: "PAT_REMARKS" },
        { type: "VARCHAR", column: "PAT_REQ_STATUS", direction: "IN", alias: "PAT_REQ_STATUS" },
        { type: "VARCHAR", column: "PAT_REQ_STATUS_DESC", direction: "IN", alias: "PAT_REQ_STATUS_DESC" },
        { type: "VARCHAR", column: "ADMN_REMARKS", direction: "IN", alias: "ADMN_REMARKS" },
        { type: "VARCHAR", column: "CALLCENTER_REMARKS", direction: "IN", alias: "CALLCENTER_REMARKS" },
        { type: "VARCHAR", column: "CALLCENTER_STATUS", direction: "IN", alias: "CALLCENTER_STATUS" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "DATE_TIME_2", column: "REQUEST_DT", direction: "IN", alias: "REQUEST_DT" },
        { type: "DATE_TIME_2", column: "RESPONSE_DT", direction: "IN", alias: "RESPONSE_DT" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "VARCHAR", column: "ADMN_STATUS", direction: "IN", alias: "ADMN_STATUS" },
        { type: "DATE_TIME_2", column: "CALL_BACK_DT", direction: "IN", alias: "CALL_BACK_DT" },
        { type: "DATE_TIME_2", column: "CALL_REQ_DATE", direction: "IN", alias: "CALL_REQ_DATE" },
        { type: "DATE_TIME_2", column: "CALL_COMPLT_DATE", direction: "IN", alias: "CALL_COMPLT_DATE" },
        { type: "VARCHAR", column: "CALL_BACK_TIME", direction: "IN", alias: "CALL_BACK_TIME" },
        { type: "VARCHAR", column: "CALL_REQ_TIME", direction: "IN", alias: "CALL_REQ_TIME" },
        { type: "VARCHAR", column: "CALL_COMPLT_TIME", direction: "IN", alias: "CALL_COMPLT_TIME" },
        { type: "CHAR", column: "SERVICE_INITIATED", direction: "IN", alias: "SERVICE_INITIATED" },
        { type: "VARCHAR", column: "SERVICE_INITIATED_REMARKS", direction: "IN", alias: "SERVICE_INITIATED_REMARKS" },
        { type: "DATE_TIME_2", column: "SERVICE_INITIATED_DT", direction: "IN", alias: "SERVICE_INITIATED_DT" },
        { type: "CHAR", column: "SERVICE_COMPLETED", direction: "IN", alias: "SERVICE_COMPLETED" },
        { type: "VARCHAR", column: "SERVICE_COMPLETED_REMARKS", direction: "IN", alias: "SERVICE_COMPLETED_REMARKS" },
        { type: "DATE_TIME_2", column: "SERVICE_COMPLETED_DT", direction: "IN", alias: "SERVICE_COMPLETED_DT" },
        { type: "N_VARCHAR", column: "LONGITUDE", direction: "IN", alias: "LONGITUDE" },
        { type: "N_VARCHAR", column: "LATITUDE", direction: "IN", alias: "LATITUDE" },
        { type: "N_VARCHAR", column: "ADDR", direction: "IN", alias: "ADDR" },
        { type: "VARCHAR", column: "CITY", direction: "IN", alias: "CITY" },
        { type: "VARCHAR", column: "STATE", direction: "IN", alias: "STATE" },
        { type: "VARCHAR", column: "COUNTRY ", direction: "IN", alias: "COUNTRY" },
        { type: "VARCHAR", column: "POSTAL_CODE", direction: "IN", alias: "POSTAL_CODE" },
        { type: "VARCHAR", column: "REQ_DESC", direction: "IN", alias: "REQ_DESC" },
        { type: "BIGINT", column: "ORG_ID", direction: "IN", alias: "ORG_ID" },
        { type: "BIGINT", column: "LOC_ID", direction: "IN", alias: "LOC_ID" }],
        Server: "SQL", Database: "APPT"
    },
    getPatReq: {
        SpName: "UPR_GET_PATIENT_REQUESTS",
        Schema: [{ type: "BIGINT", column: "PAT_REQUEST_ID", direction: "IN", alias: "PAT_REQUEST_ID" },
        { type: "BIGINT", column: "PATIENT_ID", direction: "IN", alias: "PATIENT_ID" },
        { type: "VARCHAR", column: "UMR_NO", direction: "IN", alias: "UMR_NO" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "BIGINT", column: "REQUEST_ID", direction: "IN", alias: "REQUEST_ID" },
        { type: "VARCHAR", column: "PAT_MOBILE_NO", direction: "IN", alias: "PAT_MOBILE_NO" }],
        Server: "SQL", Database: "APPT"
    },
    changePassword: {
        SpName: "UPR_UPD_CHANGE_PASSWORD",
        Schema: [{ type: "BIGINT", column: "USER_ID", direction: "IN", alias: "USER_ID" },
        { type: "N_VARCHAR", column: "OLD_PASSWORD", direction: "IN", alias: "OLD_PASSWORD" },
        { type: "N_VARCHAR", column: "NEW_PASSWORD", direction: "IN", alias: "NEW_PASSWORD" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "BIGINT", column: "COUNT", direction: "OUT", alias: "OP_COUNT" }],
        Server: "SQL", Database: "APPT"
    },
    updSessLoc: {
        SpName: "UPR_UPD_SESSION_LOC",
        Schema: [{ type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "BIGINT", column: "LOC_ID", direction: "IN", alias: "LOC_ID" },
        { type: "CHAR", column: "LOGOFF", direction: "IN", alias: "LOGOFF" }],
        Server: "SQL", Database: "APPT"
    },
    varifiUMRNumber: {
        SpName: "UPR_GET_PAT_OTP",
        Schema: [{ type: "BIGINT", column: "PAT_OTP_ID", direction: "IN", alias: "PAT_OTP_ID" },
        { type: "BIGINT", column: "REFERENCE_ID", direction: "IN", alias: "REFERENCE_ID" },
        { type: "BIGINT", column: "REFRENCE_TYPE_ID", direction: "IN", alias: "REFRENCE_TYPE_ID" },
        { type: "VARCHAR", column: "UMR_NO", direction: "IN", alias: "UMR_NO" },
        { type: "VARCHAR", column: "MOBILE_NO", direction: "IN", alias: "MOBILE_NO" },
        { type: "VARCHAR", column: "OTP", direction: "IN", alias: "OTP" },
        { type: "CHAR", column: "SENT", direction: "IN", alias: "IS_SENT" },
        { type: "CHAR", column: "FLAG", direction: "IN", alias: "FLAG" },
        { type: "VARCHAR", column: "LOGIN_TYPE", direction: "IN", alias: "IP_LOGIN_TYPE" },
        { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" },
        { type: "VARCHAR", column: "SMS_JOBNO", direction: "IN", alias: "SMS_JOBNO" },
        { type: "BIGINT", column: "ORG_ID", direction: "IN", alias: "ORG_ID" }],
        Server: "SQL", Database: "APPT"
    }
    // getOrgKey: {
    //     SpName: "UPR_GET_ORG_KEY ",
    //     Schema: [{ type: "VARCHAR", column: "ORG_KEY", direction: "IN", alias: "ORG_KEY" },
    //     { type: "BIGINT", column: "SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
    //     Server: "SQL", Database: "APPT"
    // },
    // getSltsFrOlr: {
    //     SpName: "UPR_GET_SLOTS_FOR_A_OLR",
    //     Schema: [{ type: "BIGINT", column: "OLR_ID", direction: "IN", alias: "OLR_ID" },
    //     { type: "DATE_TIME_2", column: "DT", direction: "IN", alias: "DT" },
    //     { type: "BIGINT", column: "IP_SESSION_ID", direction: "IN", alias: "IP_SESSION_ID" }],
    //     Server: "SQL", Database: "APPT"
    // },
};