module.exports = {
    insFinanceData: {
        SpName: "upr_insupd_finance_app",
        Schema: [{ type: "bigint", column: "FINAN_APP_ID", direction: "IN", alias: "par_finan_app_id" },
        { type: "character", column: "DOC_CD", direction: "IN", alias: "par_doc_cd" },
        { type: "character", column: "ORG_CD", direction: "IN", alias: "par_org_cd" },
        { type: "character", column: "LOC_CD", direction: "IN", alias: "par_loc_cd" },
        { type: "character", column: "COS_CD", direction: "IN", alias: "par_cos_cd" },
        { type: "timestamp", column: "FROM_DT", direction: "IN", alias: "par_from_dt" },
        { type: "timestamp", column: "TO_DT", direction: "IN", alias: "par_to_dt" },
        { type: "character", column: "RENDER_BY", direction: "IN", alias: "par_render_by" },
        { type: "character", column: "DATE_RANGE", direction: "IN", alias: "par_date_range" },
        { type: "character", column: "FLAG", direction: "IN", alias: "par_flag" },
        { type: "json", column: "JSON_DATA", direction: "IN", alias: "par_json_data" },
        { type: "character", column: "SMS_TIME", direction: "IN", alias: "par_sms_time" },
        { type: "bigint", column: "SESSION_ID", direction: "IN", alias: "par_session_id" }],
        Server: "PG", Database: "APK_MIS"
    },
    getFinanceData: {
        SpName: "upr_get_finance_app",
        Schema: [{ type: "character", column: "DOC_CD", direction: "IN", alias: "par_doc_cd" },
        { type: "character", column: "ORG_CD", direction: "IN", alias: "par_org_cd" },
        { type: "character", column: "LOC_CD", direction: "IN", alias: "par_loc_cd" },
        { type: "character", column: "COS_CD", direction: "IN", alias: "par_cos_cd" },
        { type: "timestamp", column: "FROM_DT", direction: "IN", alias: "par_from_dt" },
        { type: "timestamp", column: "TO_DT", direction: "IN", alias: "par_to_dt" },
        { type: "character", column: "RENDER_BY", direction: "IN", alias: "par_render_by" },
        { type: "character", column: "DATE_RANGE", direction: "IN", alias: "par_date_range" },
        { type: "character", column: "FLAG", direction: "IN", alias: "par_flag" },
        { type: "character", column: "SMS_TIME", direction: "IN", alias: "par_sms_time" },
        { type: "character", column: "USER_NAME", direction: "IN", alias: "par_user_name" },
        { type: "character", column: "DOCUMENT_NAME", direction: "IN", alias: "par_document_name" },
        { type: "character", column: "REMARKS", direction: "IN", alias: "par_remarks" },
        { type: "bigint", column: "SESSION_ID", direction: "IN", alias: "par_session_id" }],
        Server: "PG", Database: "APK_MIS"
    },
    getFindOrgLocCosById: {
        SpName: "upr_get_find_org_loc_cos_byid",
        Schema: [{ type: "character", column: "LOC_ID", direction: "IN", alias: "par_id" },
        { type: "character", column: "RENDER_BY", direction: "IN", alias: "par_render_by" }],
        Server: "PG", Database: "APK_MIS"
    },
    getVerifyUser: {
        SpName: "upr_get_user_validate",
        Schema: [{ type: "character", column: "USER_NAME", direction: "IN", alias: "par_user_name" },
        { type: "character", column: "PASSWORD", direction: "IN", alias: "par_password" },
        { type: "json", column: "USER_LOG_INFO", direction: "IN", alias: "par_user_log_info" }],
        Server: "PG", Database: "APK_MIS"
    },
    getOrgLocCos: {
        SpName: "upr_get_org_loc_cost_center",
        Schema: [],
        Server: "PG", Database: "APK_MIS"
    },
    getAllDocuments: {
        SpName: "upr_get_all_document",
        Schema: [],
        Server: "PG", Database: "APK_MIS"
    },
    getInsUpdOrgLocCos: {
        SpName: "upr_getinsupd_org_loc_cost_center",
        Schema: [{ type: "bigint", column: "org_id", direction: "IN", alias: "par_org_id" },
        { type: "character", column: "org_cd", direction: "IN", alias: "par_org_cd" },
        { type: "character", column: "org_name", direction: "IN", alias: "par_org_name" },
        { type: "character", column: "org_logo", direction: "IN", alias: "par_org_logo" },
        { type: "json", column: "theme", direction: "IN", alias: "par_theme" },
        { type: "character", column: "email_id", direction: "IN", alias: "par_email_id" },
        { type: "character", column: "mobile_no", direction: "IN", alias: "par_mobile_no" },
        { type: "character", column: "address", direction: "IN", alias: "par_address" },
        { type: "character", column: "parent_org_cd", direction: "IN", alias: "par_parent_org_cd" },
        { type: "bigint", column: "loc_id", direction: "IN", alias: "par_loc_id" },
        { type: "character", column: "loc_cd", direction: "IN", alias: "par_loc_cd" },
        { type: "character", column: "loc_name", direction: "IN", alias: "par_loc_name" },
        { type: "character", column: "default_org_cd", direction: "IN", alias: "par_default_org_cd" },
        { type: "character", column: "api_url", direction: "IN", alias: "par_api_url" },
        { type: "character", column: "loc_email_id", direction: "IN", alias: "par_loc_email_id" },
        { type: "character", column: "loc_mobile_no", direction: "IN", alias: "par_loc_mobile_no" },
        { type: "character", column: "loc_address", direction: "IN", alias: "par_loc_address" },
        { type: "character", column: "methods", direction: "IN", alias: "par_methods" },
        { type: "bigint", column: "cc_id", direction: "IN", alias: "par_cc_id" },
        { type: "character", column: "cc_cd", direction: "IN", alias: "par_cc_cd" },
        { type: "character", column: "cc_name", direction: "IN", alias: "par_cc_name" },
        { type: "character", column: "cc_org_cd", direction: "IN", alias: "par_cc_org_cd" },
        { type: "character", column: "cc_loc_cd", direction: "IN", alias: "par_cc_loc_cd" },
        { type: "character", column: "cc_email_id", direction: "IN", alias: "par_cc_email_id" },
        { type: "character", column: "cc_mobile_no", direction: "IN", alias: "par_cc_mobile_no" },
        { type: "character", column: "cc_address", direction: "IN", alias: "par_cc_address" },
        { type: "character", column: "flag", direction: "IN", alias: "par_flag" },
        { type: "character", column: "is_host", direction: "IN", alias: "par_is_host" },
        { type: "character", column: "model", direction: "IN", alias: "par_model" },
        { type: "integer", column: "dash_board", direction: "IN", alias: "par_dash_board" }],
        Server: "PG", Database: "APK_MIS"
    },
    
	getInsUpdUser: {
        SpName: "upr_getinsupd_users",
        Schema: [{ type: "bigint", column: "user_id", direction: "IN", alias: "par_user_id" },
        { type: "character", column: "org_cd", direction: "IN", alias: "par_org_cd" },
        { type: "character", column: "loc_cd", direction: "IN", alias: "par_loc_cd" },
        { type: "character", column: "user_name", direction: "IN", alias: "par_user_name" },
        { type: "character", column: "display_name", direction: "IN", alias: "par_display_name" },
        { type: "bigint", column: "gender_id", direction: "IN", alias: "par_gender_id" },
        { type: "character", column: "role_cd", direction: "IN", alias: "par_role_cd" },
        { type: "bigint", column: "reference_id", direction: "IN", alias: "par_reference_id" },
        { type: "bigint", column: "reference_type_id", direction: "IN", alias: "par_reference_type_id" },
        { type: "character", column: "password", direction: "IN", alias: "par_password" },
        { type: "text", column: "old_password", direction: "IN", alias: "par_old_password" },
        { type: "text", column: "transaction_password", direction: "IN", alias: "par_transaction_password" },
        { type: "character", column: "imei_no", direction: "IN", alias: "par_imei_no" },
        { type: "character", column: "hint2_ans", direction: "IN", alias: "par_hint2_ans" },
        { type: "character", column: "hint3_ans", direction: "IN", alias: "par_hint3_ans" },
        { type: "character", column: "email_id", direction: "IN", alias: "par_email_id" },
        { type: "character", column: "mobile_no", direction: "IN", alias: "par_mobile_no" },
        { type: "bigint", column: "default_cost_center", direction: "IN", alias: "par_default_cost_center" },
        { type: "json", column: "access_orgs", direction: "IN", alias: "par_access_orgs" },
        { type: "json", column: "access_locations", direction: "IN", alias: "par_access_locations" },
        { type: "json", column: "access_cost_centers", direction: "IN", alias: "par_access_cost_centers" },
        { type: "character", column: "flag", direction: "IN", alias: "par_flag" },
        { type: "uuid", column: "uuid", direction: "IN", alias: "par_uuid" },
        { type: "jsonb", column: "user_doc", direction: "IN", alias: "par_user_doc" },
        { type: "character", column: "login_name", direction: "IN", alias: "par_login_name" },
        { type: "integer", column: "device_count", direction: "IN", alias: "par_device_count" }],
        Server: "PG", Database: "APK_MIS"
    },
    insUpdMasterData: {
        SpName: "upr_insupd_stg_md_json",
        Schema: [{ type: "character", column: "ORG_CD", direction: "IN", alias: "par_org_cd" },
        { type: "character", column: "LOC_CD", direction: "IN", alias: "par_loc_cd" },
        { type: "character", column: "COST_CENTER_CD", direction: "IN", alias: "par_cost_center_cd" },
        { type: "timestamp", column: "DATE_VALUE", direction: "IN", alias: "par_date_value" },
        { type: "json", column: "DATA", direction: "IN", alias: "par_stg_md_json" }],
        Server: "PG", Database: "APK_MIS"
    },
	 uprGetMisDataChk: {
        SpName: "upr_get_mis_data_chk",
        Schema: [{ type: "character", column: "org_cd", direction: "IN", alias: "par_org_cd" },
        { type: "character", column: "loc_cd", direction: "IN", alias: "par_loc_cd" },
        { type: "character", column: "cc_cd", direction: "IN", alias: "par_cc_cd" },
        { type: "character", column: "head_cd", direction: "IN", alias: "par_head_cd" },
        { type: "timestamp", column: "dt", direction: "IN", alias: "par_dt" },
        { type: "character", column: "flag", direction: "IN", alias: "par_flag" }],
        Server: "PG", Database: "APK_MIS"
    },
    uprInsupdOrganization: {
        SpName: "upr_insupd_organization",
        Schema: [{ type: "character", column: "org_cd", direction: "IN", alias: "par_org_cd" },
        { type: "character", column: "org_name", direction: "IN", alias: "par_org_name" },
        { type: "character", column: "org_logo", direction: "IN", alias: "par_org_logo" },
        { type: "json", column: "theme", direction: "IN", alias: "par_theme" },
        { type: "character", column: "email_id", direction: "IN", alias: "par_email_id" },
        { type: "character", column: "mobile_no", direction: "IN", alias: "par_mobile_no" },
        { type: "character", column: "address", direction: "IN", alias: "par_address" }],
        Server: "PG", Database: "APK_MIS"
    },
	 uprGetFinanceDet: {
        SpName: "upr_get_finance_det",
        Schema: [{ type: "date", column: "from_dt", direction: "IN", alias: "par_from_dt" },
        { type: "date", column: "to_dt", direction: "IN", alias: "par_to_dt" },
        { type: "character", column: "org_cd", direction: "IN", alias: "par_org_cd" },
		{ type: "character", column: "cos_cd", direction: "IN", alias: "par_cos_cd" },
        { type: "character", column: "type", direction: "IN", alias: "par_type" },
        { type: "character", column: "flag", direction: "IN", alias: "par_flag" }],
        Server: "PG", Database: "APK_MIS"
    }
}