
let _ = require('underscore')


let _filters = [
    {
        form_type_cd: "OTREGSTR",
        label: "Surgery Start Date",
        label_value: "dt",
        controll: "DATE",
        placeholder: "",
        default_value: [],
        is_mandatory: false,
        id: "20",
        data: [],
        match_criteria: "",
        match_criteria_selected: "",
        control_value: "",
        row: "",
        col: ""
    },
    {
        form_type_cd: "OTREGSTR",
        label: "Type Of Surgery",
        label_value: "type_of_surgery_value",
        controll: "CHECKBOX",
        default_value: [],
        placeholder: "",
        is_mandatory: false,
        id: "21",
        data: [{ id: 1, name: "Daycare", value: "Daycare", isVal: "" }, { id: 2, name: "Major", value: "Major", isVal: "" }, { id: 2, name: "Minor", value: "Minor", isVal: "" }],
        match_criteria: "",
        match_criteria_selected: "",
        control_value: "",
        row: "",
        col: ""
    },
    {
        form_type_cd: "OTREGSTR",
        label: "Surgeons",
        label_value: "surgeons_names",
        controll: "MULTI",
        default_value: [],
        placeholder: "",
        is_mandatory: false,
        id: "21",
        data: [{"doc_cd":"DM122","doctor_name":"Dr. A SAI PAVAN MS MCh"},{"doc_cd":"DM121","doctor_name":"Dr. ACHANTA INDRAJA MS (OBG)"},{"doc_cd":"DM99","doctor_name":"Dr. Ameen Ma"},{"doc_cd":"DM144","doctor_name":"Dr. Bala K Davuluri"},{"doc_cd":"DM72","doctor_name":"Dr. C PADMA MD (USA)"},{"doc_cd":"DM129","doctor_name":"Dr. C.R.SETTY"},{"doc_cd":"DM11","doctor_name":"Dr. D SIRISHA MD"},{"doc_cd":"DM14","doctor_name":"Dr. DANDAMUDI SRINIVAS"},{"doc_cd":"DM117","doctor_name":"Dr. EMERGENCY UNIT"},{"doc_cd":"DM8","doctor_name":"Dr. G Ganesh"},{"doc_cd":"DM77","doctor_name":"Dr. G SOMASEKHAR MD DM FEp"},{"doc_cd":"DM1","doctor_name":"Dr. Gopala Krishna Koduru MD DM"},{"doc_cd":"DM85","doctor_name":"Dr. HARIKRISHNA BASINENI MS MCh"},{"doc_cd":"DM26","doctor_name":"Dr. JS THARUN CHOWDARY MD (A&EM)"},{"doc_cd":"DM4","doctor_name":"Dr. K GEETHA DEVI MD DGO"},{"doc_cd":"DM43","doctor_name":"Dr. K PURNACHANDRA RAO MD DM"},{"doc_cd":"DM3","doctor_name":"Dr. K SRINIVAS SAI MS MCh FIACS"},{"doc_cd":"DM50","doctor_name":"Dr. M A V Prasad"},{"doc_cd":"DM106","doctor_name":"Dr. M BOOCHI BABU MD DM FEp"},{"doc_cd":"DM32","doctor_name":"Dr. M HARIKRISHNA MD DNB"},{"doc_cd":"DM128","doctor_name":"Dr. M SREE HARSHA"},{"doc_cd":"DM154","doctor_name":"Dr. MADIREDDI MP KUMAR MBBS DEM (A&EM)"},{"doc_cd":"DM133","doctor_name":"Dr. Marri Truman Srinivas"},{"doc_cd":"DM145","doctor_name":"Dr. MEDASANI SRIDHAR DNB (GM) DNB (NEURO)"},{"doc_cd":"DM7","doctor_name":"Dr. MS GOPALA KRISHNA DNB DTCD FCCP"},{"doc_cd":"DM153","doctor_name":"Dr. N LEELA VENKATA KRISHNA MBBS DEM (A&EM)"},{"doc_cd":"DM105","doctor_name":"Dr. P Raghu Ram Md Dm Pdf"},{"doc_cd":"DM67","doctor_name":"Dr. P RAMA RAO MS"},{"doc_cd":"DM2","doctor_name":"Dr. P S SRINIVASA CHOWDARY MD DM"},{"doc_cd":"DM33","doctor_name":"Dr. P SRIMANNARAYANA MS MCh"},{"doc_cd":"DM82","doctor_name":"Dr. PADMA PARVATHANENI"},{"doc_cd":"DM130","doctor_name":"Dr. Pavan Kumar Kadiyala"},{"doc_cd":"DM156","doctor_name":"Dr. PRE ANAESTHESIA CHECKUP"},{"doc_cd":"DM114","doctor_name":"Dr. PVRS SUBRAHMANYA SARMA MD DM"},{"doc_cd":"DOC23462","doctor_name":"Dr. Ramu Tolla"},{"doc_cd":"DM12","doctor_name":"Dr. S MADHAVI MD"},{"doc_cd":"DM71","doctor_name":"Dr. SAILAJA EDARA MD DM"},{"doc_cd":"DM97","doctor_name":"Dr. Sashidhar Y"},{"doc_cd":"DM68","doctor_name":"Dr. SRIKANTH K.V.N MD (PATH)"},{"doc_cd":"DM157","doctor_name":"Dr. Sudheer Chakravarthi D"},{"doc_cd":"DM83","doctor_name":"Dr. SUMAN PENDYALA MS MCh(ortho) MRCS(UK)"},{"doc_cd":"DM126","doctor_name":"Dr. T PUJITA PHANI SOUNDARYA MD"},{"doc_cd":"DM44","doctor_name":"Dr. T SATISH CHANDRA"},{"doc_cd":"DM89","doctor_name":"Dr. T.V. RAJANI KANTH MS (ENT) JIPMER"},{"doc_cd":"DM79","doctor_name":"Dr. U CHAKRAPANI MS DNB FIAGES FACRSI"},{"doc_cd":"DM22","doctor_name":"Dr. Y  MOHAN KUMAR MD(BIOCHEMISTRY)"}],
        match_criteria: "",
        match_criteria_selected: "",
        control_value: "",
        row: "",
        col: ""
    },
    {
        form_type_cd: "OTREGSTR",
        label: "Theater Number",
        label_value: "theater_names",
        controll: "CHECKBOX",
        default_value: [],
        placeholder: "",
        is_mandatory: false,
        id: "39",
        data: [{ id: 1, name: "CTOT-1", value: "CTOT-1", isVal: "" }, { id: 2, name: "CTOT-2", value: "CTOT-2", isVal: "" }, { id: 3, name: "EROT-1", value: "EROT-1", isVal: "" }, { id: 4, name: "SSOT-1", value: "SSOT-1", isVal: "" }, { id: 5, name: "SSOT-2", value: "SSOT-2", isVal: "" }, { id: 6, name: "SSOT-3", value: "SSOT-3", isVal: "" }, { id: 7, name: "SSOT-4", value: "SSOT-4", isVal: "" }],
        match_criteria: "",
        match_criteria_selected: "",
        control_value: "",
        row: "",
        col: ""
    },
    {
        form_type_cd: "OTREGSTR",
        label: "Category Of Surgeory",
        label_value: "category_surgery_value",
        controll: "DROPDOWN",
        default_value: [],
        placeholder: "Select Category Of Surgeory",
        is_mandatory: false,
        id: "22",
        data: [{ id: 1, name: "Appendectomy", value: "Appendectomy" }, { id: 2, name: "Breast biopsy", value: "Breast biopsy" }, { id: 3, name: "ECWL", value: "ECWL" }, { id: 4, name: "Carotid endarterectomy", value: "Carotid endarterectomy" }, { id: 5, name: "Cesarean section", value: "Cesarean section" }, { id: 6, name: "Cholecystectomy", value: "Cholecystectomy" }, { id: 7, name: "Coronary artery bypass", value: "Coronary artery bypass" }, { id: 8, name: "Valve replacements", value: "Valve replacements" }, { id: 9, name: "Septal closures", value: "Septal closures" }, { id: 10, name: "Other heart surgeries", value: "Other heart surgeries" }, { id: 11, name: "Debridement of wound, burn, or infection", value: "Debridement of wound, burn, or infection" }, { id: 12, name: "Dilation and curettage (D&C)", value: "Dilation and curettage (D&C)" }, { id: 13, name: "Skin graft", value: "Skin graft" }, { id: 14, name: "Arthroscopies", value: "Arthroscopies" }, { id: 15, name: "Joint replacement surgeries", value: "Joint replacement surgeries" }, { id: 16, name: "Spine surgeries", value: "Spine surgeries" }, { id: 17, name: "Orthopedic surgeries", value: "Orthopedic surgeries" }, { id: 18, name: "Hemorrhoidectomy", value: "Hemorrhoidectomy" }, { id: 19, name: "Hysterectomy", value: "Hysterectomy" }, { id: 20, name: "Hysteroscopy", value: "Hysteroscopy" }, { id: 21, name: "Other Gynaecological procedures", value: "Other Gynaecological procedures" }, { id: 22, name: "Inguinal hernia repair", value: "Inguinal hernia repair" }, { id: 23, name: "Colon surgeries", value: "Colon surgeries" }, { id: 24, name: "Gastric surgeries", value: "Gastric surgeries" }, { id: 25, name: "Liver transplant surgeries", value: "Liver transplant surgeries" }, { id: 26, name: "Kidney transplant surgeries", value: "Kidney transplant surgeries" }, { id: 27, name: "AV fistula surgeries", value: "AV fistula surgeries" }, { id: 28, name: "Prostatectomy", value: "Prostatectomy" }, { id: 29, name: "URSL", value: "URSL" }, { id: 30, name: "Laser Lithotripsy", value: "Laser Lithotripsy" }, { id: 31, name: "Tonsillectomy", value: "Tonsillectomy" }, { id: 32, name: "Adenoidectomy", value: "Adenoidectomy" }, { id: 33, name: "Septoplasty", value: "Septoplasty" }, { id: 34, name: "Thyroidectomy", value: "Thyroidectomy" }, { id: 35, name: "Tubectomy", value: "Tubectomy" }, { id: 36, name: "Laparotomy", value: "Laparotomy" }, { id: 37, name: "Oral surgeries", value: "Oral surgeries" }, { id: 38, name: "Dental surgeries", value: "Dental surgeries" }, { id: 39, name: "Ophthalmic surgeries", value: "Ophthalmic surgeries" }, { id: 40, name: "Plastic & reconstructive surgery", value: "Plastic & reconstructive surgery" }],
        match_criteria: [],
        match_criteria_selected: "",
        control_value: "",
        row: "",
        col: ""
    },
    {
        form_type_cd: "OTREGSTR",
        label: "Emergency Surgery",
        label_value: "emergency_surgery",
        controll: "RADIO",
        default_value: [],
        placeholder: "",
        is_mandatory: false,
        id: "23",
        data: [{ id: 1, name: "Yes", value: "1" }, { id: 2, name: "No", value: "0" }],
        match_criteria: [],
        match_criteria_selected: "",
        control_value: "",
        row: "",
        col: ""
    },
    {
        form_type_cd: "OTREGSTR",
        label: "level",
        label_value: "level",
        controll: "RADIO",
        default_value: [],
        placeholder: "",
        is_mandatory: false,
        id: "32",
        data: [{ id: 1, name: "IP", value: "I" }, { id: 2, name: "UMR", value: "U" }],
        match_criteria: [],
        match_criteria_selected: "",
        control_value: "",
        row: "",
        col: ""
    },
    {
        form_type_cd: "OTREGSTR",
        label: "Purpuse Of Surgery",
        label_value: "nature_of_surgery_value",
        controll: "DROPDOWN",
        default_value: [],
        placeholder: "Select Purpuse Of Surgery",
        is_mandatory: false,
        id: "24",
        data: [{ id: 1, name: "Diagnostic", value: "Diagnostic" }, { id: 2, name: "Ablative", value: "Ablative" }, { id: 3, name: "Pallative", value: "Pallative" }, { id: 4, name: "Reconstructive", value: "Reconstructive" }, { id: 5, name: "Transplantation", value: "Transplantation" }, { id: 6, name: "Constructive", value: "Constructive" }],
        match_criteria: [],
        match_criteria_selected: "",
        control_value: "",
        row: "",
        col: ""
    },
    {
        form_type_cd: "OTREGSTR",
        label: "Name Of Surgery",
        label_value: "surgery_names",
        controll: "TEXTBOX",
        default_value: [],
        placeholder: "",
        is_mandatory: false,
        id: "25",
        match_criteria: [],
        match_criteria_selected: "",
        control_value: "",
        data: [],
        row: "",
        col: ""
    },
    {
        form_type_cd: "OTREGSTR",
        label: "Select if the procedure is",
        label_value: "proceudre_name_value",
        controll: "CHECKBOX",
        default_value: [{ id: 1, name: "HR", value: "HR" }],
        is_mandatory: false,
        id: "27",
        match_criteria: [],
        placeholder: "",
        match_criteria_selected: "",
        control_value: "",
        data: [{ id: 1, name: "Caesarean Section", value: "Caesarean Section", isVal: "" }, { id: 2, name: "Coronary Artery Bypass Grafting(cabg)", value: "Coronary Artery Bypass Grafting(cabg)", isVal: "" }, { id: 3, name: "Inguinal Herniorraphy with mesh", value: "Inguinal Herniorraphy with mesh", isVal: "" }, { id: 4, name: "Laproscopic Cholecystectomy", value: "Laproscopic Cholecystectomy", isVal: "" }],
        row: "",
        col: ""
    },
    {
        form_type_cd: "OTREGSTR",
        label: "Performed Anaesthesia",
        label_value: "perf_anaesthesia_value",
        controll: "DROPDOWN",
        default_value: [{ id: 1, name: "HR", value: "HR" }],
        is_mandatory: false,
        id: "28",
        match_criteria: [],
        placeholder: "Select Performed Anaesthesia",
        match_criteria_selected: "",
        control_value: "",
        data: [{ id: 1, name: "Epidural + Spinal Anaesthesia", value: "Epidural + Spinal Anaesthesia" }, { id: 2, name: "General Anaesthesia(GA)", value: "General Anaesthesia(GA)" }, { id: 3, name: "Local Anaesthesia(LA)", value: "Local Anaesthesia(LA)" }, { id: 4, name: "Monitored Anaesthesia Care(MAC)", value: "Monitored Anaesthesia Care(MAC)" }, { id: 5, name: "Regional Anaesthesia(RA)", value: "Regional Anaesthesia(RA)" }, { id: 6, name: "Spinal Anaesthesia", value: "Spinal Anaesthesia" }, { id: 7, name: "Total Intravenous Anaesthesia(TIVA)", value: "Total Intravenous Anaesthesia(TIVA)" }],
        row: "",
        col: ""
    },
    {
        form_type_cd: "OTREGSTR",
        label: "Surgeons",
        label_value: "proceudre_name_value",
        controll: "TEXT",
        default_value: [],
        placeholder: "",
        is_mandatory: false,
        id: "29",
        match_criteria: [],
        match_criteria_selected: "",
        control_value: "",
        data: [],
        row: "",
        col: ""
    },
    {
        form_type_cd: "OTREGSTR",
        label: "Biopsy/Specimen Sent For Histopathology Exam",
        label_value: "histopathology_exam",
        controll: "RADIO",
        default_value: [],
        placeholder: "",
        is_mandatory: false,
        id: "30",
        match_criteria: [],
        match_criteria_selected: "",
        control_value: "",
        data: [{ id: 1, name: "Yes", value: "1" }, { id: 2, name: "No", value: "0" }],
        row: "",
        col: ""
    },
    {
        form_type_cd: "OTREGSTR",
        label: "Blood Transfusion Give",
        label_value: "blood_transfusion_give",
        controll: "RADIO",
        default_value: [],
        placeholder: "",
        is_mandatory: false,
        id: "31",
        match_criteria: [],
        match_criteria_selected: "",
        control_value: "",
        data: [{ id: 1, name: "Yes", value: "1" }, { id: 2, name: "No", value: "0" }],
        row: "",
        col: ""
    },
    {
        form_type_cd: "HNDHYGN",
        label: "Date",
        label_value: "dt",
        controll: "DATE",
        placeholder: "",
        default_value: [],
        is_mandatory: false,
        id: "32",
        data: [],
        match_criteria: "",
        match_criteria_selected: "",
        control_value: "",
        row: "",
        col: ""
    },
    {
        form_type_cd: "HNDHYGN",
        label: "Employee Name",
        label_value: "emp_name",
        controll: "TEXTBOX",
        placeholder: "",
        default_value: [],
        is_mandatory: false,
        id: "33",
        data: [],
        match_criteria: [],
        match_criteria_selected: "",
        control_value: "",
        row: "",
        col: ""
    },
    {
        form_type_cd: "HNDHYGN",
        label: "Designation",
        label_value: "designation",
        controll: "TEXTBOX",
        placeholder: "",
        default_value: [],
        is_mandatory: false,
        id: "34",
        data: [],
        match_criteria: [],
        match_criteria_selected: "",
        control_value: "",
        row: "",
        col: ""
    },
    {
        form_type_cd: "HNDHYGN",
        label: "Area",
        label_value: "area",
        controll: "TEXTBOX",
        placeholder: "",
        default_value: [],
        is_mandatory: false,
        id: "35",
        data: [],
        match_criteria: [],
        match_criteria_selected: "",
        control_value: "",
        row: "",
        col: ""
    },
    {
        form_type_cd: "HNDHYGN",
        label: "Opp Type",
        label_value: "hh_opp_cd",
        controll: "DROPDOWN",
        placeholder: "Select Opp Type",
        default_value: [{ id: 1, name: "Movement 1", value: "MOVEMENT1" }],
        is_mandatory: false,
        id: "36",
        match_criteria: [],
        match_criteria_selected: "",
        control_value: "",
        data: [{ id: 1, name: "Movement 1", value: "MOVEMENT1" }, { id: 2, name: "Movement 2", value: "MOVEMENT2" }, { id: 3, name: "Movement 3", value: "MOVEMENT3" }, { id: 4, name: "Movement 4", value: "MOVEMENT4" }, { id: 5, name: "Movement 5", value: "MOVEMENT5" }],
        row: "",
        col: ""
    },
    {
        form_type_cd: "HNDHYGN",
        label: "Opp Value",
        label_value: "type_name",
        controll: "DROPDOWN",
        placeholder: "Select Opp Value",
        default_value: [{ id: 1, name: "bef-pat", value: "bef-pat" }],
        is_mandatory: false,
        id: "37",
        match_criteria: [],
        match_criteria_selected: "",
        control_value: "",
        data: [{ id: 1, name: "bef-pat", value: "bef-pat" }, { id: 2, name: "bef-asept", value: "bef-asept" }, { id: 3, name: "aft-b.f", value: "aft-b.f" }, { id: 4, name: "aft-pat", value: "aft-pat" }, { id: 5, name: "aft-p.surr", value: "aft-p.surr" }],
        row: "",
        col: ""
    },
    {
        form_type_cd: "HNDHYGN",
        label: "Opp Name",
        label_value: "sub_type_name",
        controll: "DROPDOWN",
        placeholder: "Select Opp Name",
        default_value: [{ id: 1, name: "HR", value: "HR" }],
        is_mandatory: false,
        id: "38",
        match_criteria: [],
        match_criteria_selected: "",
        control_value: "",
        data: [{ id: 1, name: "HR", value: "HR" }, { id: 2, name: "HW", value: "HW" }, { id: 3, name: "Glove", value: "Glove" }, { id: 4, name: "Missed", value: "Missed" }],
        row: "",
        col: ""
    }
];



  let gridColumns = [{ "HNDHYGN": [{ "columns": "hand_hygiene_dt,doc_no,emp_id,emp_name,designation,area,hh_opp_name,type_name,sub_type_name,remarks" }] }, { "OTREGSTR": [{"columns":"perf_sch_dt,umr_no,admn_no,doc_no,patient_name,company_name,surgery_no,surgeons_names,performed_surgery_name,surgery_names,anaesthesiologists_names,perf_anaesthesia_value,anaesthesia_start_dt,duration_of_surgery,modify_by,create_by,create_dt,proceudre_name_value,category_surgery_value,nature_of_surgery_value,emergency_surgery_value,histopathology_exam_value,blood_transfusion_give_value,theater_names,unplnd_rtn_ot_value,re_explored_value,unplanned_ventilation_value,adverse_anaesthesia_value,anaes_reltd_mortality_value,level_value"}] }];
function filtersFn(formTypeCd) {
    let filterData = {
        filterArr: _filters,
        gridColumnArr: gridColumns
    }

    return filterData
}

module.exports = {
    filtersFn
}

