const transformApi = [
    {
        methodName: "getPatientById",
        columnData: [
            {
                "_id": "_id",
                "patientId": "PATIENT_ID",
                "umr": "UMR_NO",
                "cd": "cd",
                "title": "title",
                "fName": "FIRST_NAME",
                "mName": "MIDDLE_NAME",
                "lName": "LAST_NAME",
                "disName": "PATIENT_NAME",
                "mobile": "PAT_MOBILE_NO",
                "gender": "GENDER_CD",
                "dob": "DOB",
                "from": "DATA_FROM",
                "address": "ADDRESS1",
                "cityName": "CITY_NAME",
                "stateName": "STATE_NAME",
                "country": "COUNTRY_NAME",
                "zipCode": "ZIPCODE",
                "admnNo": "ADMN_NO",
                "admnDt": "ADMN_DT",
                "dschrgDt": "DSCHRG_DT",
                "primaryDoctor": "PRIMARY_DOCTOR_NAME",
                "admnStatus":"ADMN_STATUS"
            }
        ]
    },
    {
        methodName: "getPatientByIdWithDOS",
        columnData: [
            {
                "_id": "_id",
                "patientId": "patientId",
                "umr": "umr",
                "cd": "cd",
                "title": "title",
                "fName": "fName",
                "mName": "mName",
                "lName": "lName",
                "disName": "disName",
                "mobile": "phone",
                "gender": "gender",
                "dob": "dob",
                "from": "from",
                "address": "address",
                "cityName": "cityName",
                "stateName": "stateName",
                "country": "country",
                "zipCode": "zipCode",
                "admnNo": "admnNo",
                "admnDt": "admnDt",
                "dschrgDt": "dschrgDt",
                "primaryDoctor": "primaryDoctor",
                "admnStatus":"admnStatus"
            }
        ]
    },
    {
        methodName: "getPatientByUrls",
        columnData: [
            {
                "_id": "_id",
                "patientId": "PATIENT_ID",
                "umr": "UMRNO",
                "cd": "cd",
                "title": "title",
                "fName": "PATIENTNAME",
                "mName": "MIDDLE_NAME",
                "lName": "PATIENTNAME",
                "disName": "PATIENTNAME",
                "mobile": "MOBILE_NUMBER",
                "gender": "GENDER",
                "age":"AGE",
                "dob": "DOB",
                "from": "DATA_FROM",
                "address": "PAT_ADDRESS",
                "cityName": "CITY_NAME",
                "stateName": "STATE_NAME",
                "country": "COUNTRY_NAME",
                "zipCode": "ZIPCODE",
                "admnNo": "ADMISSIONNO",
                "admnDt": "ADMISSIONDT",
                "dschrgDt": "DSCHRG_DT",
                "dschrgDt": "DISCHARGEDT",
                "patientType":"PATIENTTYPE",
                "patientStatus":"PATIENTSTATUS",
                "primaryDoctor": "DOCTORNAME",
                "admnStatus":"ADMN_STATUS",
                "admnStatus":"STATUS",
            }
        ]
    },
    {
        methodName: "getIpClinicalData",
        columnData: [
            {
                flag: 'DIAGNOSIS', childColumns: [
                    {
                        "IP_CLINICAL_TYPE": "IP_CLINICAL_TYPE",
                        "VISIT_DT": "VISIT_DT",
                        "FORMATED_VISIT_DT": "VISIT_DT",
                        "DIAGNOSIS": "DIAGNOSIS",
                        "DIAGNOSIS_TYPE": "DIAGNOSIS_TYPE",
                        "TITLE_CD": "TITLE_CD",
                        "DOCTOR_NAME": "DOCTOR_NAME",
                        "CREATE_BY": "CREATE_BY",
                        "CREATE_DT": "CREATE_DT",
                        "FORMATED_CREATE_DT": "CREATE_DT",
                        "ADMN_NO": "ADMN_NO",
                        "DISPLAY_NAME": "DISPLAY_NAME",
                        "PATIENT_ID": "PATIENT_ID",
                        "FORM_TYPE_NAME": "FORM_TYPE_NAME",
                        "REC_MODIFY_BY": "REC_MODIFY_BY",
                        "REC_CREATE_BY": "REC_CREATE_BY",
                        "SHIFT_FROM_TIME": "SHIFT_FROM_TIME",
                        "SHIFT_TO_TIME": "SHIFT_TO_TIME",
                        "VISIT_ID": "VISIT_ID",
                        "REC_CREATE_BY": "REC_CREATE_BY",
                        "MODIFY_DT": "MODIFY_DT",
                        "FORMATED_MODIFY_DT": "MODIFY_DT",
                        "MODIFY_BY": "MODIFY_BY"
                    }
                ],
                dateColums: ["FORMATED_VISIT_DT", "FORMATED_CREATE_DT", "FORMATED_MODIFY_DT"]

            },
            {
                flag: 'DOCINSTRUCTIONS', childColumns: [
                    {
                        "IP_CLINICAL_TYPE": "IP_CLINICAL_TYPE",
                        "VISIT_DT": "VISIT_DT",
                        "FORMATED_VISIT_DT": "VISIT_DT",
                        "SNO": "SNO",
                        "RECORD_STATUS": "RECORD_STATUS",
                        "RECORD_TYPE_ID": "RECORD_TYPE_ID",
                        "REFERENCE_ID": "REFERENCE_ID",
                        "REFERENCE_TYPE_ID": "REFERENCE_TYPE_ID",
                        "SYSTOLIC": "SYSTOLIC",
                        "SYSTOLIC_SITTING": "SYSTOLIC_SITTING",
                        "SYSTOLIC_STANDING": "SYSTOLIC_STANDING",
                        "SYSTOLIC_UNIT_ID": "SYSTOLIC_UNIT_ID",
                        "SYSTOLIC_UNIT_NAME": "SYSTOLIC_UNIT_NAME",
                        "DIASTOLIC": "DIASTOLIC",
                        "DIASTOLIC_SITTING": "DIASTOLIC_SITTING",
                        "DIASTOLIC_STANDING": "DIASTOLIC_STANDING",
                        "PULSE": "PULSE",
                        "PULSE_UNIT_ID": "PULSE_UNIT_ID",
                        "PULSE_UNIT_NAME": "PULSE_UNIT_NAME",
                        "HEART_RATE": "HEART_RATE",
                        "RESPORATORY_RATE": "RESPORATORY_RATE",
                        "TEMPRATURE": "TEMPRATURE",
                        "SPO2": "SPO2",
                        "WEIGHTS": "WEIGHTS",
                        "BMI": "BMI",
                        "HEIGHT": "HEIGHT",
                        "BSA": "BSA",
                        "PROVIDER_CONTACT_ID": "PROVIDER_CONTACT_ID",
                        "TITLE_CD": "TITLE_CD",
                        "DOCTOR_NAME": "DOCTOR_NAME",
                        "MODIFY_BY": "MODIFY_BY",
                        "MODIFY_DT": "MODIFY_DT",
                        "FORMATED_MODIFY_DT": "MODIFY_DT",
                        "CREATE_BY": "CREATE_BY",
                        "CREATE_DT": "CREATE_DT",
                        "FORMATED_CREATE_DT": "CREATE_DT",
                        "ADMN_NO": "ADMN_NO",
                        "CAPILARY_BLD_GLU": "CAPILARY_BLD_GLU",
                        "HEAD_CIRC": "HEAD_CIRC",
                        "TEMP_SITE": "TEMP_SITE",
                        "BP_SITTING_UNIT_ID": "BP_SITTING_UNIT_ID",
                        "BP_STANDING_UNIT_ID": "BP_STANDING_UNIT_ID",
                        "BP_SUPINE": "BP_SUPINE",
                        "TEMP_UNIT_ID": "TEMP_UNIT_ID",
                        "SPO2_UNIT_ID": "SPO2_UNIT_ID",
                        "O2": "O2",
                        "O2_UNIT_ID": "O2_UNIT_ID",
                        "HEART_TYPE": "HEART_TYPE",
                        "PULSE_TYPE": "PULSE_TYPE",
                        "BP_SIT_MAP": "BP_SIT_MAP",
                        "BP_STND_MAP": "BP_STND_MAP",
                        "BP_SUP_MAP": "BP_SUP_MAP",
                        "WEIGHT_UNIT_ID": "WEIGHT_UNIT_ID",
                        "HEIGHT_UNIT_ID": "HEIGHT_UNIT_ID",
                        "FORM_TYPE_CD": "FORM_TYPE_CD",
                        "MRN_NO": "MRN_NO",
                        "ORG_ID": "ORG_ID",
                        "LOC_ID": "LOC_ID",
                        "DISPLAY_NAME": "DISPLAY_NAME",
                        "PATIENT_ID": "PATIENT_ID",
                        "PAT_ID": "PAT_ID",
                        "UMR_LVL": "UMR_LVL",
                        "DISP_PUBLIC_PRTL": "DISP_PUBLIC_PRTL",
                        "BILL_ID": "BILL_ID",
                        "BILL_NO": "BILL_NO",
                        "SHIFT_TYPE": "SHIFT_TYPE",
                        "SHIFT_FROM_TIME": "SHIFT_FROM_TIME",
                        "SHIFT_TO_TIME": "SHIFT_TO_TIME",
                        "FORM_TYPE_NAME": "FORM_TYPE_NAME",
                        "DOC_CD": "DOC_CD",
                        "TYPE": "TYPE",
                        "VISIT_ID": "VISIT_ID",
                        "REC_MODIFY_BY": "REC_MODIFY_BY",
                        "REC_CREATE_BY": "REC_CREATE_BY",
                        "HANDOVR_BY": "HANDOVR_BY",
                        "TAKENOVR_BY": "TAKENOVR_BY",
                        "UMR_NO": "UMR_NO",
                        "FROM_TYPE": "FROM_TYPE",
                        "WARD": "WARD",
                        "BED": "BED",
                        "ROOM": "ROOM",
                        "URINE_ANALYSIS": "URINE_ANALYSIS",
                        "PAIN_SCORE": "PAIN_SCORE",
                        "FALL_RISK": "FALL_RISK",
                        "MID_UPPER_ARM": "MID_UPPER_ARM",
                        "DEGREES_FMT": "DEGREES_FMT",
                        "SPECIALITY_NAME": "SPECIALITY_NAME",
                        "CAPTURE_DT_TIME": "CAPTURE_DT_TIME",
                        "APPROVED_BY": "APPROVED_BY",
                        "APPROVED_DT": "APPROVED_DT",
                        "FORMATED_APPROVED_DT": "APPROVED_DT",
                        "VISIT_STATUS_CD": "VISIT_STATUS_CD",
                        "FORELIMB_BP": "FORELIMB_BP",
                        "HEAD_LENGTH": "HEAD_LENGTH",
                        "ABSERVING_DT_TM": "ABSERVING_DT_TM",
                        "GCS": "GCS",
                        "IP_VISIT_ID": "IP_VISIT_ID",
                        "PULSE_STANDING": "PULSE_STANDING",
                        "PULSE_STANDING_TYPE": "PULSE_STANDING_TYPE",
                        "PULSE_SITTING": "PULSE_SITTING",
                        "PULSE_SITTING_TYPE": "PULSE_SITTING_TYPE",
                        "GRBS": "GRBS",
                        "BLOOD_GROUP": "BLOOD_GROUP",
                        "CHEST_CIRCUMFERENCE_INSPIRATION": "CHEST_CIRCUMFERENCE_INSPIRATION",
                        "CHEST_CIRCUMFERENCE_INSPIRATION_UNIT": "CHEST_CIRCUMFERENCE_INSPIRATION_UNIT",
                        "CHEST_CIRCUMFERENCE_EXPIRATION": "CHEST_CIRCUMFERENCE_EXPIRATION",
                        "CHEST_CIRCUMFERENCE_EXPIRATION_UNIT": "CHEST_CIRCUMFERENCE_EXPIRATION_UNIT",
                        "HIP": "HIP",
                        "HIP_UNIT": "HIP_UNIT",
                        "WAIST_CIRCUMFERENCE": "WAIST_CIRCUMFERENCE",
                        "DOC_PROGRESS_NOTES": "DOC_PROGRESS_NOTES",
                        "REC_CREATE_BY": "REC_CREATE_BY",
                        "UMR_NO": "UMR_NO",
                        "ADMISSION_NO": "ADMISSION_NO",
                        "PATIENT_ID": "PATIENT_ID",
                        "COMPLETED_BY": "COMPLETED_BY",
                        "COMPLETED_DT": "COMPLETED_DT",
                        "FORMATED_COMPLETED_DT": "COMPLETED_DT",


                    }
                ],
                dateColums: ["FORMATED_VISIT_DT", "FORMATED_MODIFY_DT", "FORMATED_CREATE_DT", "FORMATED_APPROVED_DT"]

            },
            {
                flag: 'PATIENTNOTES', childColumns: [
                    {
                        "IP_CLINICAL_TYPE": "IP_CLINICAL_TYPE",
                        "HANDOVER_DOC_ID": "HANDOVER_DOC_ID",
                        "UMR_NO": "UMR_NO",
                        "ADMN_NO": "ADMN_NO",
                        "VISIT_ID": "VISIT_ID",
                        "FORM_TYPE_CD": "FORM_TYPE_CD",
                        "RECOM_HAND_DOC_TYPE": "RECOM_HAND_DOC_TYPE",
                        "PAT_NOTES": "PAT_NOTES",
                        "PATIENT_ID": "PATIENT_ID",
                        "VISIT_DT": "VISIT_DT",
                        "FORMATED_VISIT_DT": "VISIT_DT",
                        "REFERENCE_TYPE_ID": "REFERENCE_TYPE_ID",
                        "RECORD_STATUS": "RECORD_STATUS",
                        "ORG_ID": "ORG_ID",
                        "LOC_ID": "LOC_ID",
                        "VISIT_STATUS_CD": "VISIT_STATUS_CD",
                        "OLR_ID": "OLR_ID",
                        "ADDED_BY": "ADDED_BY",
                        "REC_CREATE_BY": "REC_CREATE_BY",
                        "WARD": "WARD",
                        "BED": "BED",
                        "ROOM": "ROOM",
                        "LOCATION": "LOCATION",
                        "NRS_STATION_CD": "NRS_STATION_CD",
                        "CREATE_BY": "CREATE_BY",
                        "CREATE_DT": "CREATE_DT",
                        "FORMATED_CREATE_DT": "CREATE_DT",
                        "MODIFY_BY": "MODIFY_BY",
                        "MODIFY_DT": "MODIFY_DT",
                        "FORMATED_MODIFY_DT": "MODIFY_DT"

                    }
                ],
                dateColums: ["FORMATED_VISIT_DT", "FORMATED_MODIFY_DT", "FORMATED_CREATE_DT"]
            },
            {
                flag: 'DOCTORNOTES', childColumns: [
                    {
                        "IP_CLINICAL_TYPE": "IP_CLINICAL_TYPE",
                        "MRN_NO": "MRN_NO",
                        "VISIT_DT": "VISIT_DT",
                        "FORMATED_VISIT_DT": "VISIT_DT",
                        "MANAGEMENT_PLAN": "MANAGEMENT_PLAN",
                        "PHYSICAL_ACTIVITY": "PHYSICAL_ACTIVITY",
                        "DIET": "DIET",
                        "PREVENTIVE_CARE": "PREVENTIVE_CARE",
                        "ADVICE": "ADVICE",
                        "DOCTOR_NAME": "DOCTOR_NAME",
                        "MODIFY_BY": "MODIFY_BY",
                        "MODIFY_DT": "MODIFY_DT",
                        "FORMATED_MODIFY_DT": "MODIFY_DT",
                        "CREATE_DT": "CREATE_DT",
                        "FORMATED_CREATE_DT": "CREATE_DT",
                        "CREATE_BY": "CREATE_BY",
                        "VISIT_ID": "VISIT_ID",
                        "REC_MODIFY_BY": "REC_MODIFY_BY",
                        "REC_CREATE_BY": "REC_CREATE_BY",
                        "SHIFT_FROM_TIME": "SHIFT_FROM_TIME",
                        "SHIFT_TO_TIME": "SHIFT_TO_TIME",
                        "MEDIC_MODIFY": "MEDIC_MODIFY",
                        "DIET_INSTRCT": "DIET_INSTRCT",
                        "UMR_NO": "UMR_NO"

                    }
                ],
                dateColums: ["FORMATED_VISIT_DT", "FORMATED_MODIFY_DT", "FORMATED_CREATE_DT"]
            },
            {
                flag: 'DOCTORHANDOVER', childColumns: [
                    {
                        "IP_CLINICAL_TYPE": "IP_CLINICAL_TYPE",
                        "VISIT_DT": "VISIT_DT",
                        "FORMATED_VISIT_DT": "VISIT_DT",
                        "VISIT_ID": "VISIT_ID",
                        "DIET": "DIET",
                        "UMR_NO": "UMR_NO",
                        "ADMN_NO": "ADMN_NO",
                        "PLAN_OF_CARE": "PLAN_OF_CARE",
                        "HANDOVER_INSTRUCTIONS": "HANDOVER_INSTRUCTIONS",
                        "ADVICE": "ADVICE",
                        "MEDIC_MODIFY": "MEDIC_MODIFY",
                        "PHYSICAL_ACTIVITY": "PHYSICAL_ACTIVITY",
                        "MODIFY_BY": "MODIFY_BY",
                        "MODIFY_DT": "MODIFY_DT",
                        "FORMATED_MODIFY_DT": "MODIFY_DT",
                        "CREATE_BY": "CREATE_BY",
                        "CREATE_DT": "CREATE_DT",
                        "FORMATED_CREATE_DT": "CREATE_DT",
                        "HANDOVERBY_NAME": "HANDOVERBY_NAME",
                        "Clinical_Examination": "CLNEXM",
                        "Critical_Values": "CRITIVALU",
                        "Daily_Progress_Notes": "DALPROGNTS",
                        "Diet": "DIT",
                        "Peding_Orders/Reports": "PENDORDR",
                        "Vitals": "VITALS",
                        "Others": "OTHERS",
                        "Labs": "LABS"

                    }
                ],
                dateColums: ["FORMATED_VISIT_DT", "FORMATED_MODIFY_DT", "FORMATED_CREATE_DT"]
            },
            {
                flag: 'INVESTIGATIONS', childColumns: [
                    {
                        "IP_CLINICAL_TYPE": "IP_CLINICAL_TYPE",
                        "SERVICE_ID": "SERVICE_ID",
                        "SERVICE_NAME": "SERVICE_NAME",
                        "INSTRUCTIONS": "INSTRUCTIONS",
                        "ITEM_FROM": "ITEM_FROM",
                        "QTY": "QTY",
                        "CREATE_DT": "CREATE_DT",
                        "CREATE_BY": "CREATE_BY",
                        "FORMATED_CREATE_DT": "CREATE_DT",
                        "MODIFY_DT": "MODIFY_DT",
                        "FORMATED_MODIFY_DT": "MODIFY_DT",
                        "MODIFY_BY": "MODIFY_BY",
                        "VISIT_DT": "VISIT_DT",
                        "FORMATED_VISIT_DT": "VISIT_DT",
                        "VISIT_ID": "VISIT_ID",
                        "BILL_STATUS": "BILL_STATUS",
                        "STOP": "STOP",
                        "STOP_DESC": "STOP_DESC",
                        "SNO": "SNO"

                    }
                ],
                dateColums: ["FORMATED_CREATE_DT", "FORMATED_MODIFY_DT", "FORMATED_VISIT_DT"]
            },
            {
                flag: 'MEDICATIONS', childColumns: [
                    {
                        "IP_CLINICAL_TYPE": "IP_CLINICAL_TYPE",
                        "VISIT_DT": "VISIT_DT",
                        "FORMATED_VISIT_DT": "VISIT_DT",
                        "MEDICATION_ID": "MEDICATION_ID",
                        "MEDICATION_NAME": "MEDICATION_NAME",
                        "REFERENCE_ID": "REFERENCE_ID",
                        "TITLE_CD": "TITLE_CD",
                        "DOCTOR_NAME": "DOCTOR_NAME",
                        "INSTRUCTIONS": "INSTRUCTIONS",
                        "DAYS": "DAYS",
                        "CONTEXT": "CONTEXT",
                        "QTY": "QTY",
                        "ITEM_FROM": "ITEM_FROM",
                        "FREQUENCY_DESC": "FREQUENCY_DESC",
                        "MODIFY_BY": "MODIFY_BY",
                        "MODIFY_DT": "MODIFY_DT",
                        "FORMATED_MODIFY_DT": "MODIFY_DT",
                        "CREATE_DT": "CREATE_DT",
                        "FORMATED_CREATE_DT": "CREATE_DT",
                        "CREATE_BY": "CREATE_BY",
                        "SEQ_ORDER": "SEQ_ORDER",
                        "VISIT_ID": "VISIT_ID",
                        "FORMATED_VISIT_ID": "VISIT_ID",
                        "STOP_MEDI": "STOP_MEDI",
                        "STOP_MEDI_DESC": "STOP_MEDI_DESC",
                        "BILL_STATUS": "BILL_STATUS",
                        "IS_HOLD": "IS_HOLD",
                        "END_DT": "END_DT",
                        "FORMATED_END_DT": "END_DT",
                        "FROM": "FROM",
                        "CANCEL_REASON": "CANCEL_REASON",
                        "REC_MODIFY_BY": "REC_MODIFY_BY",
                        "SNO": "SNO",
                        "HOLD_CONTINUE_BY": "HOLD_CONTINUE_BY",
                        "HOLD_CONTINUE_DT": "HOLD_CONTINUE_DT",
                        "FORMATED_HOLD_CONTINUE_DT": "HOLD_CONTINUE_DT",
                        "HOLD_CONTINUE_REMARKS": "HOLD_CONTINUE_REMARKS"



                    }
                ],
                dateColums: ["FORMATED_VISIT_DT", "FORMATED_MODIFY_DT", "FORMATED_CREATE_DT", "FORMATED_END_DT", "FORMATED_HOLD_CONTINUE_DT"],
                stringnull: ["CREATE_BY"]
            },
            {
                flag: 'NURSENOTES', childColumns: [
                    {
                        "IP_CLINICAL_TYPE": "IP_CLINICAL_TYPE",
                        "IP_VISIT_DT": "IP_VISIT_DT",
                        "FORMATED_IP_VISIT_DT": "IP_VISIT_DT",
                        "NOTES": "NOTES",
                        "CREATE_DT": "CREATE_DT",
                        "FORMATED_CREATE_DT": "CREATE_DT",
                        "CREATE_BY": "CREATE_BY",
                        "MODIFY_BY": "MODIFY_BY",
                        "MODIFY_DT": "MODIFY_DT",
                        "FORMATED_MODIFY_DT": "MODIFY_DT",
                        "ENTER_NAME": "ENTER_NAME",
                        "APPROVED_BY": "APPROVED_BY",
                        "APPROVED_DT": "APPROVED_DT",
                        "FORMATED_APPROVED_DT": "APPROVED_DT",
                        "SHIFT_TYPE": "SHIFT_TYPE",
                        "LOCATION": "LOCATION",
                        "REC_CREATE_BY": "REC_CREATE_BY",
                        "REC_MODIFY_BY": "REC_MODIFY_BY",

                    }
                ],
                dateColums: ["FORMATED_IP_VISIT_DT", "FORMATED_CREATE_DT", "FORMATED_MODIFY_DT", "FORMATED_APPROVED_DT"]
            },
            {
                flag: 'IOCHART', childColumns: [
                    {
                        "IP_CLINICAL_TYPE": "IP_CLINICAL_TYPE",
                        "UMR_NO": "UMR_NO",
                        "ADMISSION_NO": "ADMISSION_NO",
                        "IO_CHART_TYPE": "IO_CHART_TYPE",
                        "IO_DATE_TIME": "IO_DATE_TIME",
                        "FORMATED_IO_DATE_TIME": "IO_DATE_TIME",
                        "IO_TYPE": "IO_TYPE",
                        "IO_TYPE_DESC_ID": "IO_TYPE_DESC_ID",
                        "AM_ML": "AM_ML",
                        "REMARKS": "REMARKS",
                        "FORM_TYPE_CD": "FORM_TYPE_CD",
                        "VISIT_STATUS_NAME": "VISIT_STATUS_NAME",
                        "ROOM": "ROOM",
                        "IO_TYPE_DESC": "IO_TYPE_DESC",
                        "CREATE_BY": "CREATE_BY"

                    }
                ],
                dateColums: ["FORMATED_IO_DATE_TIME"]
            },
            {
                flag: 'IOCHARTSUM', childColumns: [
                    {
                        "IP_CLINICAL_TYPE": "IP_CLINICAL_TYPE",
                        "IODT": "IODT",
                        "FORMATED_IODT": "IODT",
                        "IN_CUM_TOTAL": "IN_CUM_TOTAL",
                        "OUT_CUM_TOTAL": "OUT_CUM_TOTAL",
                        "BAL_TOTAL": "BAL_TOTAL",
                        "KILO_CAL": "KILO_CAL"
                    }
                ],
                dateColums: ["FORMATED_IODT"]
            },
            {
                flag: 'VITALS', childColumns: [
                    {
                        "IP_CLINICAL_TYPE": "IP_CLINICAL_TYPE",
                        "VISIT_DT": "VISIT_DT",
                        "FORMATED_VISIT_DT": "VISIT_DT",
                        "SNO": "SNO",
                        "SYSTOLIC": "SYSTOLIC",
                        "SYSTOLIC_SITTING": "SYSTOLIC_SITTING",
                        "SYSTOLIC_STANDING": "SYSTOLIC_STANDING",
                        "DIASTOLIC": "DIASTOLIC",
                        "DIASTOLIC_SITTING": "DIASTOLIC_SITTING",
                        "DIASTOLIC_STANDING": "DIASTOLIC_STANDING",
                        "PULSE": "PULSE",
                        "HEART_RATE": "HEART_RATE",
                        "RESPORATORY_RATE": "RESPORATORY_RATE",
                        "TEMPRATURE": "TEMPRATURE",
                        "SPO2": "SPO2",
                        "WEIGHTS": "WEIGHTS",
                        "BMI": "BMI",
                        "HEIGHT": "HEIGHT",
                        "BSA": "BSA",
                        "TITLE_CD": "TITLE_CD",
                        "DOCTOR_NAME": "DOCTOR_NAME",
                        "MODIFY_BY": "MODIFY_BY",
                        "MODIFY_DT": "MODIFY_DT",
                        "FORMATED_MODIFY_DT": "MODIFY_DT",
                        "CREATE_BY": "CREATE_BY",
                        "CREATE_DT": "CREATE_DT",
                        "FORMATED_CREATE_DT": "CREATE_DT",
                        "CAPILARY_BLD_GLU": "CAPILARY_BLD_GLU",
                        "HEAD_CIRC": "HEAD_CIRC",
                        "TEMP_SITE": "TEMP_SITE",
                        "HEART_TYPE": "HEART_TYPE",
                        "PULSE_TYPE": "PULSE_TYPE",
                        "PAIN_SCORE": "PAIN_SCORE",
                        "SPO2_UNIT_ID": "SPO2_UNIT_ID",
                        "BLOOD_GROUP": "BLOOD_GROUP",
                        "HEAD_LENGTH": "HEAD_LENGTH",
                        "CHEST_INSPIRATION": "CHEST_CIRCUMFERENCE_INSPIRATION",
                        "CHEST_INSPIRATION_UNIT": "CHEST_CIRCUMFERENCE_INSPIRATION_UNIT",
                        "CHEST_EXPIRATION": "CHEST_CIRCUMFERENCE_EXPIRATION",
                        "CHEST_EXPIRATION_UNIT": "CHEST_CIRCUMFERENCE_EXPIRATION_UNIT",
                        "HIP": "HIP",
                        "HIP_UNIT": "HIP_UNIT",
                        "WAIST": "WAIST_CIRCUMFERENCE",
                        "GRBS": "GRBS"



                    }
                ],
                dateColums: ["FORMATED_VISIT_DT", "FORMATED_MODIFY_DT", "FORMATED_CREATE_DT"],
                stringArr: ["PAIN_SCORE"]
            },
            {
                flag: 'PROCEDURERECORD', childColumns: [
                    {
                        "IP_CLINICAL_TYPE": "IP_CLINICAL_TYPE",
                        "UMR_NO": "UMR_NO",
                        "VISIT_DT": "VISIT_DT",
                        "FORMATED_VISIT_DT": "VISIT_DT",
                        "ADMN_NO": "ADMN_NO",
                        "VISIT_ID": "VISIT_ID",
                        "MANAGEMENT_PLAN": "MANAGEMENT_PLAN",
                        "PHYSICAL_ACTIVITY": "PHYSICAL_ACTIVITY",
                        "MODIFY_BY": "MODIFY_BY",
                        "MODIFY_DT": "MODIFY_DT",
                        "FORMATED_MODIFY_DT": "MODIFY_DT",
                        "CREATE_BY": "CREATE_BY",
                        "CREATE_DT": "CREATE_DT",
                        "FORMATED_CREATE_DT": "CREATE_DT",
                        "INTRA_PROCDRE_COMPLCTN": "INTRA_PROCDRE_COMPLCTN",
                        "POST_PROCDRE_COMPLCTN": "POST_PROCDRE_COMPLCTN",
                        "REC_MODIFY_BY": "REC_MODIFY_BY",
                        "REC_CREATE_BY": "REC_CREATE_BY"

                    }
                ],
                dateColums: ["FORMATED_VISIT_DT", "FORMATED_MODIFY_DT", "FORMATED_CREATE_DT"]
            },
            {
                flag: 'ICDCODING', childColumns: [
                    {
                        "IP_CLINICAL_TYPE": "IP_CLINICAL_TYPE",
                        "MRN_NO": "MRN_NO",
                        "VISIT_DT": "VISIT_DT",
                        "FORMATED_VISIT_DT": "VISIT_DT",
                        "SNO": "SNO",
                        "RECORD_TYPE_ID": "RECORD_TYPE_ID",
                        "RECORD_STATUS": "RECORD_STATUS",
                        "MC_ID": "MC_ID",
                        "ICD_CODE": "ICD_CODE",
                        "CONDITION_NAME": "CONDITION_NAME",
                        "CONDITION_STATUS_ID": "CONDITION_STATUS_ID",
                        "START_DT": "START_DT",
                        "FORMATED_START_DT": "START_DT",
                        "END_DT": "END_DT",
                        "FORMATED_END_DT": "END_DT",
                        "REFERENCE_ID": "REFERENCE_ID",
                        "REFERENCE_TYPE_ID": "REFERENCE_TYPE_ID",
                        "PROVIDER_CONTACT_ID": "PROVIDER_CONTACT_ID",
                        "TITLE_CD": "TITLE_CD",
                        "DOCTOR_NAME": "DOCTOR_NAME",
                        "HOW_IT_ENDED": "HOW_IT_ENDED",
                        "NOTES": "NOTES",
                        "DURATION": "DURATION",
                        "PERIOD": "PERIOD",
                        "PERIOD_NAME": "PERIOD_NAME",
                        "MODIFY_BY": "MODIFY_BY",
                        "MODIFY_DT": "MODIFY_DT",
                        "FORMATED_MODIFY_DT": "MODIFY_DT",
                        "CREATE_DT": "CREATE_DT",
                        "FORMATED_CREATE_DT": "CREATE_DT",
                        "CREATE_BY": "CREATE_BY",
                        "ORG_ID": "ORG_ID",
                        "LOC_ID": "LOC_ID",
                        "DISPLAY_NAME": "DISPLAY_NAME",
                        "PATIENT_ID": "PATIENT_ID",
                        "UMR_LVL": "UMR_LVL",
                        "DISP_PUBLIC_PRTL": "DISP_PUBLIC_PRTL",
                        "BILL_NO": "BILL_NO",
                        "ADMN_NO": "ADMN_NO",
                        "FORM_TYPE_CD": "FORM_TYPE_CD",
                        "FORM_TYPE_NAME": "FORM_TYPE_NAME",
                        "VISIT_ID": "VISIT_ID",
                        "REC_MODIFY_BY": "REC_MODIFY_BY",
                        "REC_CREATE_BY": "REC_CREATE_BY",
                        "UMR_NO": "UMR_NO",
                        "FROM_TYPE": "FROM_TYPE",
                        "WARD": "WARD",
                        "ROOM": "ROOM",
                        "BED": "BED",
                        "CODE_TYPE": "CODE_TYPE",
                        "SEQ_ORDER": "SEQ_ORDER",
                        "IP_VISIT_ID": "IP_VISIT_ID",
                        "APPROVED_BY": "APPROVED_BY",
                        "APPROVED_DT": "APPROVED_DT",
                        "FORMATED_APPROVED_DT": "APPROVED_DT",
                        "VISIT_STATUS_CD": "VISIT_STATUS_CD"

                    }
                ],

                dateColums: ["FORMATED_VISIT_DT", "FORMATED_MODIFY_DT", "FORMATED_CREATE_DT", "FORMATED_START_DT", "FORMATED_END_DT", "FORMATED_APPROVED_DT"]
            },
            {
                flag: 'DISCHRGSUMNAME', childColumns: [
                    {
                        "IP_CLINICAL_TYPE": "IP_CLINICAL_TYPE",
                        "SUMMARY_ID": "SUMMARY_ID",
                        "RECORD_STATUS": "RECORD_STATUS",
                        "UMR_NO": "UMR_NO",
                        "SUMMARY_NO": "SUMMARY_NO",
                        "SUMMARY_DT": "SUMMARY_DT",
                        "FORMATED_SUMMARY_DT": "SUMMARY_DT",
                        "ADMN_NO": "ADMN_NO",
                        "ADMN_DT": "ADMN_DT",
                        "FORMATED_ADMN_DT": "ADMN_DT",
                        "SPECIALITY_ID": "SPECIALITY_ID",
                        "SPECIALITY_NAME": "SPECIALITY_NAME",
                        "FORMAT_ID": "FORMAT_ID",
                        "WEIGHT": "WEIGHT",
                        "FORMAT_TYPE": "FORMAT_TYPE",
                        "FORMAT_NAME": "FORMAT_NAME",
                        "APPROVE_BY": "APPROVE_BY",
                        "APPROVE_DT": "APPROVE_DT",
                        "FORMATED_APPROVE_DT": "APPROVE_DT",
                        "APPROVED_STATUS": "APPROVED_STATUS",
                        "SERVICE_ID": "SERVICE_ID",
                        "DSUMRY_HDR": "DSUMRY_HDR",
                        "CATH_LAB_INFO": "CATH_LAB_INFO",
                        "DOCTOR_ID": "DOCTOR_ID",
                        "DSCHRG_DT": "DSCHRG_DT",
                        "FORMATED_DSCHRG_DT": "DSCHRG_DT",
                        "PROCEDURE_DT": "PROCEDURE_DT",
                        "FORMATED_PROCEDURE_DT": "PROCEDURE_DT",
                        "REVIEW_DT": "REVIEW_DT",
                        "FORMATED_REVIEW_DT": "REVIEW_DT",
                        "CREATE_BY": "CREATE_BY",
                        "CREATE_DT": "CREATE_DT",
                        "FORMATED_CREATE_DT": "CREATE_DT",
                        "MODIFY_BY": "MODIFY_BY",
                        "MODIFY_DT": "MODIFY_DT",
                        "FORMATED_MODIFY_DT": "MODIFY_DT",
                        "SLOTS_ID": "SLOTS_ID",
                        "ORG_ID": "ORG_ID",
                        "LOC_ID": "LOC_ID",
                        "VERSION_CNT": "VERSION_CNT",
                        "DISCHARGE_DESTINATION": "DISCHARGE_DESTINATION",
                        "SOURCE_OF_REFERRAL": "SOURCE_OF_REFERRAL",
                        "METHOD_OF_ADMISSION": "METHOD_OF_ADMISSION",
                        "HOSPITAL_SITE": "HOSPITAL_SITE",
                        "DISCHARGE_METHOD": "DISCHARGE_METHOD",
                        "PATIENT_DIED": "PATIENT_DIED",
                        "DATE_OF_DEATH": "DATE_OF_DEATH",
                        "POST_MARTEM": "POST_MARTEM",
                        "DISCHARGE_ADDRESS": "DISCHARGE_ADDRESS",
                        "SUMMARY_NAME": "SUMMARY_NAME",
                        "SUMMARY_STATUS": "SUMMARY_STATUS",
                        "SUMMARY_END_DT": "SUMMARY_END_DT",
                        "FORMATED_SUMMARY_END_DT": "SUMMARY_END_DT",
                        "COMPLETED_STATUS": "COMPLETED_STATUS",
                        "COMPLETED_DT": "COMPLETED_DT",
                        "FORMATED_COMPLETED_DT": "COMPLETED_DT",
                        "COMPLETED_BY": "COMPLETED_BY",
                        "FORMAT_TYPE_CD": "FORMAT_TYPE_CD",
                        "PROCEDURE1": "PROCEDURE1",
                        "PROCEDURE1_DT": "PROCEDURE1_DT",
                        "PROCEDURE2": "PROCEDURE2",
                        "PROCEDURE2_DT": "PROCEDURE2_DT",
                        "APPROVED_FROM": "APPROVED_FROM",
                        "APMNT1_DT": "APMNT1_DT",
                        "APMNT1_SLOT": "APMNT1_SLOT",
                        "APMNT1_DOCTOR": "APMNT1_DOCTOR",
                        "APMNT2_DT": "APMNT2_DT",
                        "APMNT2_SLOT": "APMNT2_SLOT",
                        "APMNT2_DOCTOR": "APMNT2_DOCTOR",
                        "STARTED_BY": "STARTED_BY",
                        "STARTED_DT": "STARTED_DT",
                        "FORMATED_STARTED_DT": "STARTED_DT",
                        "MOBILE_NO": "MOBILE_NO",
                        "MLC_NO": "MLC_NO",
                        "PRINT_SPEC": "PRINT_SPEC",
                        "SUM_TITLE": "SUM_TITLE",
                        "REWORK": "REWORK",
                        "REWORK_BY": "REWORK_BY",
                        "REWORK_DT_TIME": "REWORK_DT_TIME",
                        "REWORK_CNT": "REWORK_CNT",
                        "RSRC_ID": "RSRC_ID",
                        "DISS_DOCTOR": "DISS_DOCTOR"

                    }
                ],

                dateColums: ["FORMATED_MODIFY_DT", "FORMATED_CREATE_DT", "FORMATED_SUMMARY_END_DT", "FORMATED_COMPLETED_DT", "FORMATED_STARTED_DT", "FORMATED_SUMMARY_DT", "FORMATED_ADMN_DT", "FORMATED_APPROVE_DT", "FORMATED_DSCHRG_DT", "FORMATED_PROCEDURE_DT", "FORMATED_REVIEW_DT"]
            }, {
                flag: 'DISCHRGSUMMDET', childColumns: [
                    {
                        "IP_CLINICAL_TYPE": "IP_CLINICAL_TYPE",
                        "SUMMARY_NOTE_ID": "SUMMARY_NOTE_ID",
                        "SUB_TITLE": "SUB_TITLE",
                        "SUB_TITLE_DESC": "SUB_TITLE_DESC",
                        "FONT_ID": "FONT_ID",
                        "FONT_SIZE": "FONT_SIZE",
                        "FONT_WEIGHT": "FONT_WEIGHT",
                        "PRINT_ORDER": "PRINT_ORDER",
                        "NOTES": "NOTES",
                        "SUMMARY_ID": "SUMMARY_ID",
                        "SRV_TYPE": "SRV_TYPE",
                        "SRV_ID": "SRV_ID",
                        "RESULT_VALUE": "RESULT_VALUE",
                        "FORMAT_NOTE_ID": "FORMAT_NOTE_ID",
                        "FORMAT_ID": "FORMAT_ID",
                        "APPROVE_BY": "APPROVE_BY",
                        "APPROVE_DT": "APPROVE_DT",
                        "FORMATED_APPROVE_DT": "APPROVE_DT",
                        "STAT": "STAT",
                        "VERSION_CNT": "VERSION_CNT",
                        "PLAIN_NOTES": "PLAIN_NOTES",
                        "FORMAT_TYPE": "FORMAT_TYPE",
                        "ADDENDUM_NOTES": "ADDENDUM_NOTES",
                        "REMARKS": "REMARKS"

                    }
                ],

                dateColums: ["FORMATED_APPROVE_DT"]
            },
            {
                flag: 'SURGEONOPNOTES', childColumns: [
                    {
                        "IP_CLINICAL_TYPE": "IP_CLINICAL_TYPE",
                        "SURG_NT_ID": "SURG_NT_ID",
                        "ADMISSION_NO": "ADMISSION_NO",
                        "UMR_NO": "UMR_NO",
                        "VISIT_ID": "VISIT_ID",
                        "VISIT_DT": "VISIT_DT",
                        "FORMATED_VISIT_DT": "VISIT_DT",
                        "VISIT_STATUS_CD": "VISIT_STATUS_CD",
                        "PATIENT_ID": "PATIENT_ID",
                        "FORM_TYPE_CD": "FORM_TYPE_CD",
                        "SURG_PROCEDURE_NAME": "SURG_PROCEDURE_NAME",
                        "ANAESTHETIST": "ANAESTHETIST",
                        "DATE_OF_OPERATION": "DATE_OF_OPERATION",
                        "FORMATED_DATE_OF_OPERATION": "DATE_OF_OPERATION",
                        "CO_SURGEON_NAME": "CO_SURGEON_NAME",
                        "ASSISTANT_NAME": "ASSISTANT_NAME",
                        "OT": "OT",
                        "PRE_OP_DIAGNOSIS": "PRE_OP_DIAGNOSIS",
                        "POST_OP_DIAGNOSIS": "POST_OP_DIAGNOSIS",
                        "PROCEDURE_FINDINGS": "PROCEDURE_FINDINGS",
                        "PROCEDURE_DETAILS": "PROCEDURE_DETAILS",
                        "POST_OP_PLAN_OF_CARE": "POST_OP_PLAN_OF_CARE",
                        "CREATE_BY": "CREATE_BY",
                        "CREATE_DT": "CREATE_DT",
                        "FORMATED_CREATE_DT": "CREATE_DT",
                        "MODIFY_BY": "MODIFY_BY",
                        "MODIFY_DT": "MODIFY_DT",
                        "FORMATED_MODIFY_DT": "MODIFY_DT",
                        "APPROVED_BYID": "APPROVED_BYID",
                        "APPROVED_BY": "APPROVED_BY",
                        "APPROVED_DT": "APPROVED_DT",
                        "FORMATED_APPROVED_DT": "APPROVED_DT",
                        "SHIFT_FROM_TIME": "SHIFT_FROM_TIME",
                        "SHIFT_TO_TIME": "SHIFT_TO_TIME",
                        "PATH_LOGY": "PATH_LOGY",
                        "PATH_LOGY_REMARKS": "PATH_LOGY_REMARKS",
                        "CYT_LOGY": "CYT_LOGY",
                        "CYT_LOGY_REMARKS": "CYT_LOGY_REMARKS",
                        "MICRO_BIOLOGY": "MICRO_BIOLOGY",
                        "MICRO_BIOLOGY_REMARKS": "MICRO_BIOLOGY_REMARKS",
                        "SPECIMEN_OTHERS": "SPECIMEN_OTHERS",
                        "SPECIMEN": "SPECIMEN",
                        "SPECIMEN_REMARKS": "SPECIMEN_REMARKS",
                        "INTRA_PROCDRE_OPRTVE_EVTS": "INTRA_PROCDRE_OPRTVE_EVTS",
                        "INTRA_PROCDRE_OPRTVE_EVTS_RMKS": "INTRA_PROCDRE_OPRTVE_EVTS_RMKS",
                        "BLOOD_LOSS": "BLOOD_LOSS",
                        "BLOOD_PRODUCT": "BLOOD_PRODUCT",
                        "BLOOD_PRODUCT_REMARKS": "BLOOD_PRODUCT_REMARKS",
                        "IP_VISIT_ID": "IP_VISIT_ID",
                        "STATUS_PAT_AFTSURG": "STATUS_PAT_AFTSURG",
                        "URN_OUTPUT_DURSURG": "URN_OUTPUT_DURSURG",
                        "DOCREGNO": "DOCREGNO",
                        "SPECIALITY": "SPECIALITY",
                        "DESIGNATION": "DESIGNATION",
                        "DEGREES_FMT": "DEGREES_FMT",
                        "DATA_SRC_FROM": "DATA_SRC_FROM"
                    }
                ],
                dateColums: ["FORMATED_VISIT_DT", "FORMATED_CREATE_DT", "FORMATED_MODIFY_DT", "FORMATED_APPROVED_DT", "FORMATED_DATE_OF_OPERATION"]

            },
            {
                flag: 'CHIEFCOMPLAINTS', childColumns: [
                    {
                        "IP_CLINICAL_TYPE": "IP_CLINICAL_TYPE",
                        "MRN_NO": "MRN_NO",
                        "VISIT_DT": "VISIT_DT",
                        "FORMATED_VISIT_DT": "VISIT_DT",
                        "SNO": "SNO",
                        "RECORD_STATUS": "RECORD_STATUS",
                        "REFERENCE_ID": "REFERENCE_ID",
                        "REFERENCE_TYPE_ID": "REFERENCE_TYPE_ID",
                        "RECORD_TYPE_ID": "RECORD_TYPE_ID",
                        "COMPLAINT_TYPE_ID": "COMPLAINT_TYPE_ID",
                        "COMP_TYPE_NAME": "COMP_TYPE_NAME",
                        "COMPLAINT_ID": "COMPLAINT_ID",
                        "COMPLAINT_NAME": "COMPLAINT_NAME",
                        "COMPLAINT_STATUS": "COMPLAINT_STATUS",
                        "DURATION": "DURATION",
                        "PERIOD_ID": "PERIOD_ID",
                        "PERIOD_NAME": "PERIOD_NAME",
                        "START_DT": "START_DT",
                        "FORMATED_START_DT": "START_DT",
                        "END_DT": "END_DT",
                        "FORMATED_END_DT": "END_DT",
                        "PROVIDER_CONTACT_ID": "PROVIDER_CONTACT_ID",
                        "TITLE_CD": "TITLE_CD",
                        "DOCTOR_NAME": "DOCTOR_NAME",
                        "NOTES": "NOTES",
                        "MODIFY_BY": "MODIFY_BY",
                        "MODIFY_DT": "MODIFY_DT",
                        "FORMATED_MODIFY_DT": "MODIFY_DT",
                        "CREATE_DT": "CREATE_DT",
                        "FORMATED_CREATE_DT": "CREATE_DT",
                        "CREATE_BY": "CREATE_BY",
                        "BILL_NO": "BILL_NO",
                        "ADMN_NO": "ADMN_NO",
                        "ORG_ID": "ORG_ID",
                        "LOC_ID": "LOC_ID",
                        "FORM_TYPE_CD": "FORM_TYPE_CD",
                        "FORM_TYPE_NAME": "FORM_TYPE_NAME",
                        "VISIT_ID": "VISIT_ID",
                        "REC_MODIFY_BY": "REC_MODIFY_BY",
                        "REC_CREATE_BY": "REC_CREATE_BY",
                        "PATIENT_ID": "PATIENT_ID",
                        "UMR_NO": "UMR_NO",
                        "WARD": "WARD",
                        "BED": "BED",
                        "ROOM": "ROOM",
                        "APPROVED_BY": "APPROVED_BY",
                        "APPROVED_DT": "APPROVED_DT",
                        "FORMATED_APPROVED_DT": "APPROVED_DT",
                        "VISIT_STATUS_CD": "VISIT_STATUS_CD",
                        "TYPE": "TYPE"
                    }
                ],
                dateColums: ["FORMATED_VISIT_DT", "FORMATED_START_DT", "FORMATED_END_DT", "FORMATED_MODIFY_DT", "FORMATED_CREATE_DT", "FORMATED_APPROVED_DT"]

            },
            {
                flag: 'PREOPANSTH', childColumns: [
                    {
                        "IP_CLINICAL_TYPE": "IP_CLINICAL_TYPE",
                        "ANEST_ID": "ANEST_ID",
                        "ORG_ID": "ORG_ID",
                        "LOC_ID": "LOC_ID",
                        "ADMN_NO": "ADMN_NO",
                        "PATIENT_ID": "PATIENT_ID",
                        "UMR_NO": "UMR_NO",
                        "ENTITY_CODE": "ENTITY_CODE",
                        "ENTITY_VALUE_CODE": "ENTITY_VALUE_CODE",
                        "VAL1": "VAL1",
                        "VAL2": "VAL2",
                        "VAL3": "VAL3",
                        "SURG_PRO_PLAN": "SURG_PRO_PLAN",
                        "COMORBIDITY_PROBLEMS": "COMORBIDITY_PROBLEMS",
                        "MEDI_HIST": "MEDI_HIST",
                        "MEDI_HIST_REMARKS": "MEDI_HIST_REMARKS",
                        "SURG_HIST": "SURG_HIST",
                        "SURG_HIST_REMARKS": "SURG_HIST_REMARKS",
                        "ANST_HIST": "ANST_HIST",
                        "ANST_HIST_REMARKS": "ANST_HIST_REMARKS",
                        "BLOOD_TRAN": "BLOOD_TRAN",
                        "BLOOD_TRAN_REMARKS": "BLOOD_TRAN_REMARKS",
                        "ADHE_MED_DRUG": "ADHE_MED_DRUG",
                        "ADHE_MED_DRUG_REMARKS": "ADHE_MED_DRUG_REMARKS",
                        "PREDN_CORTIS": "PREDN_CORTIS",
                        "PREDN_CORTIS_REMARKS": "PREDN_CORTIS_REMARKS",
                        "COMPL_WITH_ANETH": "COMPL_WITH_ANETH",
                        "COMPL_WITH_ANETH_REMARKS": "COMPL_WITH_ANETH_REMARKS",
                        "DO_YOU_SMOKE": "DO_YOU_SMOKE",
                        "PACKS_PER_DAY": "PACKS_PER_DAY",
                        "SMOKE_QUIT": "SMOKE_QUIT",
                        "SMOKE_FROM_YEARS": "SMOKE_FROM_YEARS",
                        "ALCOHOL_BEVERGES": "ALCOHOL_BEVERGES",
                        "DRINKS_PER_TYPE": "DRINKS_PER_TYPE",
                        "ALCOHOL_QUIT": "ALCOHOL_QUIT",
                        "RECREATIONAL_DRUG": "RECREATIONAL_DRUG",
                        "DRUG_TYPE": "DRUG_TYPE",
                        "DRUG_QUIET": "DRUG_QUIET",
                        "CVS": "CVS",
                        "LUNGS": "LUNGS",
                        "THYROID": "THYROID",
                        "NECK_SPINE": "NECK_SPINE",
                        "COMPLAINT_PROBLEMS": "COMPLAINT_PROBLEMS",
                        "DENTURE": "DENTURE",
                        "DENTURE_REMARKS": "DENTURE_REMARKS",
                        "MPG": "MPG",
                        "ASA": "ASA",
                        "NILL_ORALLY_FROM": "NILL_ORALLY_FROM",
                        "FIT_FOR_SURGERY": "FIT_FOR_SURGERY",
                        "FURTHER_EVALUATION": "FURTHER_EVALUATION",
                        "ANAESTHESIA_TYPE": "ANAESTHESIA_TYPE",
                        "PRE_MED_OP_INSTRCTNS": "PRE_MED_OP_INSTRCTNS",
                        "IVFLUIDS": "IVFLUIDS",
                        "IV_FLUIDS_START": "IV_FLUIDS_START",
                        "BLOOD_PRODUCTS": "BLOOD_PRODUCTS",
                        "SPCL_MON_RQRMNTS": "SPCL_MON_RQRMNTS",
                        "FORM_TYPE_CD": "FORM_TYPE_CD",
                        "WARD": "WARD",
                        "BED": "BED",
                        "ROOM": "ROOM",
                        "CREATE_BY": "CREATE_BY",
                        "CREATE_DT": "CREATE_DT",
                        "FORMATED_CREATE_DT": "CREATE_DT",
                        "APPROVED_BY": "APPROVED_BY",
                        "APPROVED_DT": "APPROVED_DT",
                        "FORMATED_APPROVED_DT": "APPROVED_DT",
                        "IP_VISIT_ID": "IP_VISIT_ID",
                        "VISIT_STATUS_CD": "VISIT_STATUS_CD",
                        "DOCREGNO": "DOCREGNO",
                        "PSY_ASSMNT_OTHERS": "PSY_ASSMNT_OTHERS",
                        "IS_PRSNT_TIME_PRBLMS": "IS_PRSNT_TIME_PRBLMS",
                        "IS_PRSNT_REMARKS": "IS_PRSNT_REMARKS",
                        "SLOTS_ID": "SLOTS_ID",
                        "ASA_E": "ASA_E",
                        "SPECIALITY": "SPECIALITY",
                        "DEGREES_FMT": "DEGREES_FMT",
                        "REC_CREATE_BY": "REC_CREATE_BY",
                        "OTHERS_NEW": "OTHERS_NEW",
                        "TYPE": "TYPE",
                        "FROM_IP_OP": "FROM_IP_OP",
                        "CONVERTED_BY": "CONVERTED_BY",
                        "CONVERTED_DT": "CONVERTED_DT",
                        "FORMATED_CONVERTED_DT": "CONVERTED_DT",
                        "THYROMENTAL_DIST": "THYROMENTAL_DIST",
                        "HEAD_CIRCUMTANCES": "HEAD_CIRCUMTANCES",
                        "TYPE_OF_SURGERY": "TYPE_OF_SURGERY",
                        "SURGEONS_NAME": "SURGEONS_NAME",
                        "SCHEDULED_DT_TIME": "SCHEDULED_DT_TIME",
                        "AIRWAY": "AIRWAY",
                        "CLINICAL_EXAM": "CLINICAL_EXAM",
                        "ANESTHESIA_TYPE_REMARKS": "ANESTHESIA_TYPE_REMARKS",
                        "DIAGNOSIS": "DIAGNOSIS"
                    }
                ],
                dateColums: ["FORMATED_CREATE_DT", "FORMATED_APPROVED_DT", "FORMATED_CONVERTED_DT"]

            }

        ]
    },
]



module.exports = transformApi;